export const FAQ = {
    "GCFAQ":{
        3: [
            { question: 'Is using this checklist sufficient to fill out the N-400?', answer: 'No. Please read and follow the instructions on the N-400 carefully. The checklist, even though it’s provided by USCIS, is for informational purposes only and does not replace the instruction requirements on the form itself. Also, please seek professional guidance from an attorney if needed, to ensure you provide all the required documentation for your specific circumstances.'},
            { question: 'Do I need to submit original documents?', answer: 'Do not send original documents unless it is specifically requested in the form instructions or applicable regulations.'}
        ], 
        4: [
            { question: 'Do I need to keep copies of everything I submit?', answer: ' Yes. You should keep a copy of your completed Form N-400 and any supporting documents you submit with it, for your own records. You should also keep the Form N-400 receipt USCIS will send to you, and other important documents and communications/receipts from USCIS throughout the process.'},
            { question: 'If I request a reduced fee or a fee waiver, can I still file online?', answer: 'No. USCIS requires that people requesting a reduced fee or fee waiver file their N-400 by mail.'},
            { question: 'How much is the filing fee?', answer: 'The filing fee is $710 to file online and $760 to file by mail. If you request a reduced fee, it is $380.'},
            { question: 'What’s the earliest time I can file?', answer: 'Use the following USCIS Early Filing Calculator to calculate the earliest date you can file.'}
        ],
        5: [ 
            { question: 'How do I know if I need a biometrics appointment?', answer: 'USCIS will send you an appointment notice, if it is applicable.'},
            { question: 'What if I need to reschedule my appointment?', answer: 'That’s fine, as long as you reschedule it before the original appointment date and time, and establish good cause for rescheduling. Otherwise, your application could be denied.'}
        ], 
        6: [
            { question: 'How should I prepare for the interview?', answer: 'Study for the English and civic tests, unless you are exempt. We have three sources listed under this step, as provided by https://www.usa.gov/naturalization. Also be prepared to answer any questions about your N-400. Don’t forget to bring the appointment notice to your interview!'}
        ], 
        7: [
            { question: 'What happens if my N-400 is continued?', answer: 'USCIS will inform you of what you need to do before your Form N-400 can be granted.'},
            { question: 'What happens if my N-400 is denied?', answer: 'If you believe you’ve been wrongly denied, you can request a hearing to appeal the decision by filing Form N-336 within 30 days of receiving the decision.'}
        ],
        8: [
            { question: 'What is the Oath of Allegiance?', answer: 'From the Code of Federal Regulations, the following is the Oath of Allegiance as of April 14, 2025: I hereby declare, on oath, that I absolutely and entirely renounce and abjure all allegiance and fidelity to any foreign prince, potentate, state, or sovereignty, of whom or which I have heretofore been a subject or citizen; that I will support and defend the Constitution and laws of the United States of America against all enemies, foreign and domestic; that I will bear true faith and allegiance to the same; that I will bear arms on behalf of the United States when required by the law; that I will perform noncombatant service in the Armed Forces of the United States when required by the law; that I will perform work of national importance under civilian direction when required by the law; and that I take this obligation freely, without any mental reservation or purpose of evasion; so help me God.'}
        ], 
        9: [
            {question: 'What else will I have to do at this ceremony?', answer: 'You will have to turn in your Permanent Resident Card and receive a Certificate of Naturalization. Make sure you check the Certificate and identify any errors before you leave the ceremony, so they can be corrected.'}
        ]
    }, 
    "SFAQ":{
        1: [
            {}
        ], 
        2: [
            {}
        ],
        3: [
            { question: 'How can I check the status of my I-130 petition?', answer: 'You can enter your receipt number on the USCIS “Case Status Online” page to see updates. Initially, you’ll see “Case Received.” Later it might show “ actively being reviewed” and finally “Approved” or a notice if an RFE is issued. You can also call USCIS Contact Center, but online status is the quickest. Creating a USCIS online account (for paper-filed cases you can use the Online Access Code from your mailer) allows you to track and receive electronic updates.'},
            { question: 'How long does it take for the I-130 to be approved?', answer: 'It varies. USCIS processing times fluctuate based on their backlog. As of early 2025, many spousal I-130s for immediate relatives are taking roughly 10–16 months to get approved. Some cases are faster (especially if filed online or if USCIS prioritizes them) and some slower. USCIS’s official stance is that case timelines cannot be guaranteed. You can monitor the USCIS processing times for the service center handling your case on the USCIS website. If your case exceeds normal processing times, you can submit an “outside normal processing time” service request.'},
            { question: 'I received a Request for Evidence (RFE). Does this mean my case is in trouble?', answer: ' Not necessarily. An RFE simply means USCIS needs additional information before deciding. Common RFEs for spousal petitions include requests for missing documents (e.g. a properly certified marriage certificate, or proof of a legal name change) or more evidence of a bona fide marriage if what was provided was not sufficient. It’s important to respond by the deadline (usually 87 days) with everything requested. Once USCIS receives your response, your case will resume processing. Most RFEs are resolved by sending the needed info and do not indicate a denial, as long as you comply fully.'},
            { question: 'What happens after my I-130 is approved?', answer: 'If your spouse will immigrate from overseas, USCIS will send the approved petition to the National Visa Center (NVC), which coordinates the next steps (fee payment and visa application). You will get a Notice of Approval (I-797) from USCIS and then, a few weeks later, a welcome communication from NVC with a case number. If your spouse is adjusting status in the U.S., there’s no NVC step – instead, your I-130 approval will be matched with the pending I-485 case. In either scenario, the approval of the petition is a big milestone: it means USCIS recognizes the qualifying relationship. The next steps will be either consular processing or adjustment of status, which we cover in the following steps.'},
            { question: 'Will my spouse get any visa or travel document after the I-130 approval?', answer: 'Not from the I-130 alone. The approved I-130 is not a visa or green card – it’s the petition that allows your spouse to move forward in obtaining the immigrant visa/green card. If your spouse is abroad, they must wait for the NVC and consulate to issue an immigrant visa in their passport before they can travel to the U.S. as a resident. If your spouse is in the U.S. adjusting status, they can obtain work and travel permits while the I-485 is pending (if you filed those applications), but the actual green card comes only after adjustment is approved. The I-130 approval by itself doesn’t grant any interim benefits.'}
        ],
        4: [
            { question: 'How will I know the case has reached the National Visa Center?', answer: 'USCIS will send you (the petitioner) a Form I-797 approval notice. Shortly after, NVC will send a Welcome Letter by email (or physical mail if email wasn’t provided). The welcome letter includes your NVC case number and an Invoice ID, which you’ll use to log into the CEAC system. If you don’t hear from NVC within a few weeks of the I-130 approval, you can reach out to NVC by phone or online inquiry to check status. Remember that NVC will use the contact info provided on the I-130 (so if you changed your email or address, inform NVC or USCIS).' },
            { question: 'What is the Form DS-261 and do I need to wait for it?', answer: 'DS-261, Choice of Address and Agent, is a simple online form where the visa applicant designates who will receive communications from NVC/Embassy. If you (the beneficiary) are going to handle your own case and use your own email, you fill out DS-261 to confirm that. If you have an attorney, the attorney often is the agent. Many times, by the time you get the NVC welcome, you can proceed directly to paying fees and the DS-261 is either pre-filled or not required explicitly (especially since most correspondence is done via email now). Follow the NVC’s instructions – your online account will indicate if you need to submit DS-261. It’s done entirely online and has no fee.'},
            { question: 'What fees do I have to pay to NVC and can I pay online?', answer: 'For spousal immigrant visa cases, there are two primary fees at NVC: the Immigrant Visa Application fee (for DS-260) and the Affidavit of Support fee. Yes, you will pay them online in the CEAC system (using a US bank account or credit card). Once you log in, you’ll see invoices for each fee. After you submit the payments, each will show as “In Process” then “Paid.” Only after a fee is marked paid can you move on to the next steps (submitting forms or documents). The exact fee amounts are set by the government and can be found on the State Department’s website (as of now, $325 + $120 for these two). NVC will not review your documents until fees are paid. Tip: Pay both fees at once if possible to avoid delays, since you’ll need both cleared to finish the process.'},
            { question: 'If my spouse is in the U.S. and we are doing Adjustment of Status, do we skip the NVC entirely?', answer: 'Yes. If filing for a green card through Adjustment of Status (AOS), the NVC and consular steps do not apply. The approved I-130 will remain with USCIS. You will deal with your local USCIS office for the interview. However, if you indicated on the I-130 that the beneficiary was intending consular processing and later decide to do AOS (or vice versa), you should notify USCIS or NVC of the change. If the petition was already sent to NVC but the spouse is now eligible to adjust in the U.S., you may need to request the petition be sent back to USCIS (this can be done via Form I-824 or sometimes via NVC’s public inquiry). It’s simpler if you decide the path (AOS vs CP) at the start and proceed accordingly.'},
            { question: 'I’m a U.S. citizen living abroad – what is this about domicile for the Affidavit of Support?', answer: 'U.S. citizens can file petitions from abroad, but when it comes to the Affidavit of Support (Form I-864), the sponsor must have a domicile in the United States (meaning your principal residence is in the U.S.). If you’ve been living abroad, you need to show you either maintain a U.S. residence or you intend to re-establish domicile in the U.S. by the time your spouse immigrates. You can prove intent to re-establish domicile by showing steps like a lease in the U.S., a job offer in the U.S., or other evidence that you’re moving back. If you truly have no domicile in the U.S. and won’t move back, you cannot fulfill the I-864 obligations – in such cases, a joint sponsor (who does live in the U.S.) would be required.'}
        ], 
        5: [
            { question: 'What exactly is the Affidavit of Support and why is it needed?', answer: 'The Affidavit of Support (Form I-864) is a contract in which the petitioner (and any joint sponsor) promises the U.S. government to support the intending immigrant if necessary. It’s required by law for family-based immigrants. By signing, the sponsor agrees to keep the immigrant at an income above 125% of poverty and reimburse the government if the immigrant accesses certain need-based public benefits. This helps ensure the immigrant will not become a financial burden on taxpayers. The form requires financial information to show the sponsor can meet this obligation. It’s essentially a guarantee of financial support.'}, 
            { question: 'How do I know if my income is enough to sponsor my spouse?', answer: 'You need to compare your household income against the current 125% poverty guideline for your household size. Household size includes you, your spouse, any dependents, any immigrants you’ve already sponsored with I-864 (if obligations still in effect), and the new beneficiary. USCIS and NVC publish poverty guidelines (which update each year). For example, if it’s just you and your spouse, household size = 2. If 125% of poverty for 2 is (say) $22,887, and your current income as shown on your job letter or recent pay stubs is $30,000, you’re fine. If you earned less, say $20,000, you’d need a joint sponsor or assets. Note: they primarily look at the most recent tax return income (AGI) as a baseline, but you should also show you’re currently earning at or above that level. If there was a one-time dip in income last year but now you have a better job, explain and document it. NVC’s feedback will simply be “meets/does not meet requirements.” If it does not meet, adding a joint sponsor is the common solution.'}, 
            { question: 'What if I didn’t file taxes last year or I filed jointly with my spouse?', answer: 'If you weren’t required to file taxes (e.g., low income or student), you should provide a written explanation. NVC expects a tax return or transcript for the most recent year. If you filed jointly with your spouse (the immigrant) or someone else, and that income is used, that person (e.g., the immigrant if they had U.S. income) might need to sign an I-864A as a household member. However, in most spousal cases, the immigrant hasn’t been earning U.S. income yet (unless they were in the U.S. on a work visa). If you filed jointly, include all W-2s and clearly show who earned what. The key is to satisfy the consular officer or USCIS that there are sufficient financial resources.'}, 
            { question: 'Can assets be used if income is not enough?', answer: 'Yes, assets can supplement income. Assets must be liquid or easily convertible to cash within one year and located in the US (for the petitioner’s assets) or, if it’s the immigrant’s assets, accessible in the US. Common assets: cash in bank accounts, stocks/bonds, real estate equity, etc. The total net value of assets must equal 5 times the shortfall (for a spouse of a US citizen). For example, if you are $5,000 short of the required income, you’d need $25,000 in assets. For the spouse of a permanent resident, it’s 3 times if using assets, but in IR cases it’s 5 times unless the intending immigrant is a child. You will list these assets in the I-864 and provide evidence (like bank statements, appraisals). Using a joint sponsor is often simpler if available, but assets can work too.' },
            { question: 'Do I need to submit the actual bank statements and tax returns, or just mention figures on the I-864?', answer: 'You must submit evidence. Simply stating an income on the form isn’t enough – NVC (or USCIS) wants to see proof. At a minimum, submit your federal tax transcript or tax return for the most recent year. Additionally, provide proof of current employment/income (letter from employer and pay stubs). For any assets listed, provide documentation (for example, bank statements for the last 12 months for savings accounts, or a valuation for property along with evidence of ownership and any mortgage balance). The more complete your documentation, the smoother this step will go. If documents are missing, NVC will “kick back” the affidavit for you to correct.'},
            { question: 'What happens if my income still isn’t enough even with a joint sponsor?', answer: 'Each sponsor (you and any joint sponsor) must individually meet the income requirement for their household. You can’t combine two sponsors’ incomes to meet one threshold. If even a joint sponsor with sufficient income cannot be found, it will be difficult to get the visa issued because the financial support requirement is a statutory one. The consular officer must have a sufficient I-864 to issue the visa. In practice, virtually everyone finds a solution – either a joint sponsor or using assets. In rare cases, if no adequate sponsor is available, the visa could be refused under public charge grounds. It’s crucial to sort out the financial sponsorship now. Remember that the petitioning spouse is required to submit an I-864 even if unemployed or having zero income, but if they don’t meet the guideline, a joint sponsor can save the day.'}
        ], 
        6: [
            { question: 'What is the DS-260 and how is it different from the I-130?', answer: 'The DS-260 is the actual immigrant visa application that the beneficiary fills out (electronically) after the I-130 petition is approved. Think of the I-130 as the petitioner’s request to classify a relationship, and the DS-260 as the beneficiary’s own application for an immigrant visa. The DS-260 asks about the beneficiary’s biographical details, address and work history, and security-related questions (similar to other visa applications). The beneficiary will answer questions about criminal history, immigration violations, etc. It’s an important form that the consular officer will review. You must complete it for the case to proceed. The printed confirmation is required for the interview.'}, 
            { question: 'Do I need police certificates from every country I’ve lived in?', answer: ' Police certificates are required from: your country of nationality (if you resided there at all after age 16) and any country of residence for more than 6 months since age 16. Additionally, any country where you spent 12+ months (even if not continuous residence, but typically it means actual residence) since age 16. Also, any country where you were arrested or convicted, no matter how long you lived there. However, some countries’ police certificates are considered unavailable or not required by the U.S. (for example, if a country doesn’t issue them to non-residents). You should consult the State Department’s Reciprocity Schedule for each country to see how to obtain the police cert and if there are exceptions. NVC will list “Police Certificate: Available” or “Not available” accordingly. If a police certificate is not obtainable, you’ll provide proof of trying and perhaps a statement from the police (or the reciprocity info) saying it’s unavailable. If you have a common name, sometimes multiple certificates or aliases may be needed; follow instructions.'}, 
            { question: 'The birth certificate from my country has a different format / was issued by a local authority – will it be accepted?', answer: 'Each country has specific acceptable civil documents. Check the U.S. embassy’s instructions or the State Department Reciprocity and Civil Documents guide. For example, some countries have both short-form and long-form birth certificates; the U.S. usually requires the long-form that includes parent names. If your document is not in English, include a certified translation. The document should be an official copy. If the embassy finds an issue (e.g., a church baptism in lieu of a civil birth record), they may require additional proof. It’s best to get the exact document type NVC asks for. If the one you have might not be correct (say, it lacks a signature or official seal), try to obtain a proper one from the issuing authority.'}, 
            { question: 'After uploading all the civil documents, do I need to mail anything to NVC?', answer: 'No, the NVC process is now mostly electronic for most countries. You should not mail physical documents to NVC (unless explicitly instructed, which is rare now). Simply ensure all scans are legible and submitted. You will bring the originals of these civil documents to your visa interview. The consular officer will need to see the originals and will return them to you after the interview. So, while NVC doesn’t need physical copies, the interview is where originals matter. Keep everything organized in a file to carry to the embassy.'}, 
            { question: 'How long does NVC take to review my DS-260 and documents?', answer: 'It can vary. NVC often posts on their website the dates of cases they are currently reviewing. In recent times, it’s been a few weeks up to a couple of months. If you uploaded everything correctly and meet all requirements, NVC will mark your case Documentarily Qualified (DQ) once review is complete. You will be notified that you are in the queue for an interview. If NVC finds an issue (missing or incorrect document), they will send a notice and your CEAC portal will show a checklist of items to fix. You then correct those and it takes additional time for review. To avoid delays, double-check requirements before submitting.'},
            { question: 'What does “Documentarily Qualified” mean?', answer: '“Documentarily Qualified” (also called “Case Complete”) means NVC has reviewed all your submitted forms (DS-260) and documents (civil docs and financials) and found everything in order. In other words, your file is complete and just waiting for an interview slot. NVC will not schedule an interview until the case is documentarily qualified. Once you get that status, you’re essentially in line for the next available interview appointment at the designated consulate. NVC will then work with the embassy to set your interview date (which might take some time depending on the post’s backlog).'}
        ], 
        7: [
            { question: 'How will I be informed of my interview date?', answer: 'NVC will send you an email (or physical mail if no email on file) once an interview is scheduled. This notice includes the interview date, time, and location, along with instructions on scheduling your medical exam and what to bring. For USCIS (AOS) interviews, you’ll get a mailed notice (Form I-797C) with the appointment details. In either case, if you log into CEAC (for NVC cases) after scheduling, you will see the interview date there as well. Keep an eye on your email’s spam folder as well, just in case. If it’s been a long time since case completed, you can inquire with NVC or check the U.S. Embassy’s website – some post their current interview wait times.'}, 
            { question: 'My case has been complete at NVC for a while – why haven’t I got an interview yet?', answer: 'Interview scheduling depends on the U.S. consulate’s capacity. Immediate relatives are prioritized over other categories, but if the embassy is very busy or dealing with backlogs (sometimes due to pandemic backlogs or limited staffing), it can take longer. Some consulates have a queue of documentarily qualified cases waiting for interviews. Unfortunately, there’s not much you can do to expedite unless there’s an urgent situation (see next Q). Rest assured, if you’ve gotten the “Case Complete” notice, your case is simply in line. If a very long time passes (several months) and no word, you might contact NVC or the consulate to ensure you didn’t miss a notice.'}, 
            { question: 'Can I request an earlier interview or expedite the interview date?', answer: 'You can request an expedited service in certain circumstances. For example, military deployment, severe medical emergencies, or other humanitarian reasons might justify an expedited. To do so, you or the petitioner can contact NVC (if case still at NVC) or the embassy (if case is already scheduled or in their queue) with a detailed request and supporting evidence. Expedited requests are granted rarely and only for strong reasons. If approved, your case might skip ahead to the next available interview slot. Without an expedited, you generally cannot change the interview date to be earlier. If you absolutely must reschedule due to a conflict, you usually can (through the consulate’s visa appointment system or by emailing them), but the new date might be later than the original. Always try to attend the original interview date if at all possible.'}, 
            { question: 'What do I need to do before the interview (aside from documents)?', answer: 'Schedule your medical exam with an authorized panel physician (for consular) – usually 1-2 weeks before the interview (Step 8 will cover this). Some embassies require you to register your appointment on their site or register for courier service for passport return – the instructions in your appointment notice will tell you. Follow any such steps, like creating an account on the embassy’s visa appointment page to register your address. Also, prepare for potential interview questions – review your whole case (the information on your forms) so you’re ready to answer questions about your relationship, background, etc. If you have any updated information (e.g., a new child was born, or your address changed), be prepared to mention that at the interview and have documentation. For AOS interviews, also update your Form I-864 or bring the latest financial evidence if the one on file is more than a year old or if circumstances have changed (this isn’t strictly required but is often recommended).'}, 
            { question: 'Will the petitioner (U.S. spouse) be required at the interview?', answer: 'For consular interviews, the U.S. citizen petitioner is not required to attend. In fact, most embassies do not allow the petitioner into the interview (some may let them accompany as a guest, but it’s consulate-specific). The interview is primarily for the applicant. However, the petitioner can attend as support at certain posts if the embassy allows it – it’s best to check the consulate’s policy or FAQs. That said, it’s optional, and not attending won’t hurt the case. For the Adjustment of Status (USCIS interview), the U.S. petitioner should absolutely attend. USCIS will interview both spouses together (or sometimes separately) to verify the marriage. The interview notice for marriage-based AOS usually explicitly says the petitioner must come. If the U.S. spouse cannot attend an AOS interview, you should reschedule, as the officer will almost always require their presence to answer questions about the relationship.'}, 
            { question: 'What if I need to reschedule the interview?', answer: 'If it’s a consular interview, instructions to reschedule are often provided on the embassy’s website (usually via the same portal where nonimmigrant visa appointments are managed). Be cautious: rescheduling can lead to significant delays, as you’ll get the next available slot, which might be far out. Only reschedule if necessary. If you must, do it before the interview date – a missed interview without notice can trigger termination of your case after a period of no contact. For a USCIS AOS interview, the notice has instructions for requesting a new date (you typically have to write to the office or call the USCIS hotline before the interview). Again, this will delay your case by potentially months. Whenever possible, try to attend the scheduled interview. If an emergency (illness, etc.) prevents you from attending, communicate with the consulate or USCIS as soon as possible.'},
        ], 
        8: [
            { question: 'What vaccines are required for the immigrant medical exam?', answer: 'U.S. immigration law requires a set of vaccinations for immigrant visa applicants and adjustment applicants. These include (for adults): MMR (measles, mumps, rubella), Td or Tdap (tetanus, diphtheria, pertussis), Varicella (chickenpox), Influenza (during flu season), COVID-19 vaccine, and others like Hepatitis B, Pneumococcal, etc., depending on age and risk. The panel physician will review your vaccine history and the current CDC guidelines for required vaccines. If you lack any, they will offer to administer them (or you can get them beforehand and show proof). It’s best to bring any vaccine records to avoid unnecessary re-vaccination. If you have a medical contraindication to a vaccine (allergy, etc.), the doctor can note that. If you object on religious or moral grounds, you might seek a waiver, but that’s a separate process. Most people just get the needed shots to comply.'},
            { question: 'What happens if the doctor finds something abnormal in the medical exam?', answer: ' It depends on what it is. For example, if you test positive for tuberculosis exposure (positive skin or blood test), the panel physician will likely require a chest X-ray to check for active TB. If the X-ray is clear (no active TB), you’ll be fine – they’ll include the findings. If something like active TB is suspected, you might have to undergo treatment and delay the visa until cleared (active TB is a temporary ineligibility until treated). If you have a treatable STD (like syphilis), you must get treatment and show proof (the doctor can administer required antibiotics). For other conditions, like well-managed chronic diseases, it’s usually not an issue – just ensure you’re under care. Mental health: if there’s a history of issues that could pose a danger (e.g., violent behavior or substance abuse), the doctor will evaluate and note it. Drug testing is not standard except for suspected drug abuse cases. The medical exam is mostly about infectious diseases and vaccines; most findings won’t derail your visa, but some can delay it for additional steps. The doctor will either hand you the sealed results or tell you if any follow-up is needed before they can clear you.'}, 
            { question: 'How do I find the list of panel physicians and schedule the exam?', answer: 'The U.S. Embassy/Consulate’s website for your country will list the approved panel physicians with contact info. It may also be linked in the interview letter. You typically call the clinic to schedule and let them know it’s for a U.S. immigrant visa medical. Some large cities have multiple choices; others maybe just one clinic. Schedule early enough to get an appointment at a good time. For USCIS (AOS) exams, use the USCIS find a civil surgeon tool on their website to locate doctors near you. Then call and ask for an “I-693 immigration medical exam” appointment. Prices can vary, so you can shop around a bit for civil surgeons, whereas panel physician fees are usually set.'}, 
            { question: 'Should I prep for interview questions? What do they typically ask?', answer: 'It’s a good idea to mentally prepare. Consular officers often ask: “How did you meet your spouse?,” “When did you get married?,” “How often have you visited each other?,” or details about each other’s lives (like “What does your husband do for a living? Where does he live? Have you met his family?”). They might ask about wedding details or even trivial things like favorite foods – usually just to gauge the genuineness of the relationship. They may also review the DS-260 and ask about any prior U.S. visits (“Have you ever been to the U.S.?”), work history, or if you have children. For USCIS interviews, expect similar relationship questions, possibly in more depth. The officer might go through the I-485 yes/no questions with you as well (regarding eligibility, like criminal or security questions). If your case is bona fide, answer confidently and consistently. Don’t be nervous – just tell the truth. It’s okay if you don’t remember a minor detail, but you should know the big picture of your own relationship story. Practicing by going over timelines (dates of meeting, engagement, marriage, etc.) with your spouse can be helpful.'},
            { question: 'What is the “Visa Rights” pamphlet and will I be asked about it?', answer: 'The U.S. Government has an informational pamphlet titled “Information for Visa Applicants about Domestic Violence and Legal Rights.” It’s required to be given to foreign fiancé(e)s and spouses coming to the U.S. It outlines your rights in the U.S. regarding domestic violence, sexual assault, and child abuse, and lists resources for help. At the interview, the consular officer may ask the beneficiary, “Have you received and read the IMBRA rights pamphlet? Do you understand your rights in the U.S.?” They ask this to ensure you’re aware that you do not have to stay in an abusive situation to keep your status, etc. You should indeed read it (it’s often provided with your NVC interview notice or available on the embassy site). If you didn’t get a copy, you can find it online (search “DOS domestic violence visa pamphlet”). AOS interviews might not mention this, as it’s more a consular requirement, but being aware is beneficial regardless.'}, 
            { question: 'My spouse and I have been living together abroad – will that be an issue at the interview?', answer: 'Not at all, as long as you, the petitioner, can prove intent to re-establish domicile in the U.S. (since you need domicile for the I-864). The interviewing officer’s focus will be on the legitimacy of the marriage and the visa eligibility. If you both appear at the consular interview, the officer might appreciate seeing you together, though officially, the petitioner isn’t required. Be ready to explain your plans for moving to the U.S. (for example, “We plan to travel together shortly after the visa is issued, and we’ll reside at XYZ address, and I (petitioner) have already arranged a job/start work”). The consulate just wants to ensure the visa, if granted, will be used and the immigrant will indeed go to the U.S. to reside. Living together abroad is fine; many couples do so to avoid separation during the process. Just ensure all other aspects (financial support, etc.) are in order.'}
        ], 
        9: [
            { question: 'What kinds of questions will the consular officer ask in a spousal visa interview?', answer: 'They typically ask about your relationship history and background. Examples: “When and where did you meet your spouse?”, “How long did you date before deciding to marry?”, “How many times has your spouse visited you (or vice versa) after marriage?”, “Where does your spouse live and work?”, “Have either of you been married before?” They may also ask about day-to-day knowledge: “What do you like about your spouse?” or “What is your spouse’s favorite hobby/food?” The idea is to see if you have a normal marriage. They might ask the petitioner’s family members’ names, or if you had a honeymoon. Every interview is different; some officers are very friendly and only ask a couple of questions, while others are more thorough. Since you’ve provided extensive paperwork, often they already have a sense of your case. Just answer honestly. If you don’t recall an exact date or detail, say “I’m not sure, but approximately…” It’s okay. It’s not an interrogation, but rather a verification.'}, 
            { question: 'Will the officer review our photos or chat messages?', answer: 'If you offer them, often yes, they will take a quick look. Many consular officers appreciate seeing a few photos (especially wedding pictures or photos of you together with family). It humanizes the case and can dispel doubts. Some officers might not ask for them if they already believe the marriage is bona fide. You can politely mention, “I have our photo album here if you’d like to see it,” and they may say yes or no. Chat logs or call records can be offered if you spent long periods apart, to show you kept in touch. In high-fraud areas, officers sometimes do ask for these. In a USCIS interview, the officer will want to see some joint documents (lease, joint bills) and photos; they often ask you to hand over what you’ve brought, and they’ll flip through and perhaps ask questions. So, yes, have them ready. They likely won’t keep your photos or personal correspondence – they’ll just review and give back. Only copies of formal documents might be kept.'},
            { question: 'What is a 221(g) refusal?', answer: 'A 221(g) is a section of the law under which a consular officer can refuse a visa temporarily due to missing information or further processing. If you get a 221(g) letter, it will usually either ask you to submit additional documents or just state that the case is under administrative processing. It is not a final denial. It means something is pending. For example, if you forgot to bring an original document, they might give 221(g) instructing you how to send it in (often via the consulate’s courier or email). Or if your background checks are not finished (common for certain common names or certain countries), they issue 221(g) to administratively process – you just have to wait. In some cases, they might require a follow-up action (like a DNA test if there’s a question on a relationship, though for a spouse that’s rare). The letter will guide you. If you get 221(g), respond as quickly and accurately as possible. If it’s just waiting on the U.S. government’s side, unfortunately, you just have to wait. Keep communication lines open in case they need something else.'}, 
            { question: 'What if my visa is approved? What do I receive?', answer: 'If approved at a consulate, the officer will keep your passport to place the immigrant visa foil (stamp) in it. Typically, you’ll get your passport back with the visa within a week or so (depending on the consulate’s process – either pick up at a courier location or delivered to you). Along with the passport, you may receive a sealed immigrant packet containing your civil documents and immigration documents. Nowadays, many consulates are switching to electronic processing, so sometimes there is no big packet and the info is sent electronically to CBP. However, if you do get a physical packet, do not open it. You will hand it to the CBP officer at the U.S. port of entry. The visa in your passport will have an expiration date (usually 6 months from medical exam) and a notation if you paid the USCIS Immigrant Fee or not. For AOS (USCIS) approvals, typically you get an approval notice and then the green card by mail – no visa since you’re already inside the US. The officer might stamp your passport with a temporary I-551 stamp if urgent (proof of residence for travel/work) or you can wait for the card.'},
            { question: 'What are the most common reasons a spousal visa would be denied at the interview?', answer: 'Common temporary denials: missing documents (221(g)), incomplete medical, or administrative processing required (like a security check hit). These are resolvable. Actual denials (under Section 212) could be for: Marriage not believed to be genuine – if the officer suspects fraud, they can deny under INA 212(a)(6)(C)(i) for misrepresentation or INA 204(c) (permanent bar for marriage fraud). Inadmissibility issues: If the beneficiary has a serious criminal record, a prior immigration violation, or is found inadmissible for some other reason (e.g., prior visa overstay if they’re a spouse of a USC, that’s forgiven; but if a spousal case of an LPR, overstay could matter). If there are inadmissibilities, sometimes a waiver can be filed. Another possible denial reason: not meeting the Affidavit of Support requirement, though usually they’d give a chance for a joint sponsor (221(g)). If the sponsor flat out doesn’t qualify and no joint sponsor, the visa can’t be issued. But that’s avoidable by having a joint sponsor. In summary, outright denials are rare for well-prepared spousal cases; most issues can be fixed via additional evidence or waivers.'},
            { question: 'Will I get my original documents back after the interview?', answer: 'Yes, any original civil documents (birth, marriage certificates, etc.) you bring to the interview will be returned to you either immediately or with your visa packet. The consulate might keep photocopies if they need them, but they return originals. The only thing they keep is your passport (temporarily for visa stamping). USCIS interviews will similarly return originals at the end (they might take your photo albums to photocopy a couple of pictures for the file and hand back everything). If, for some reason, an original is not returned, you can usually inquire, but standard procedure is you keep your original documents. Always double-check you have them back before leaving if they were passed through the window.'}
        ]
    }
}