const GreencardGlossary = {
  "Lawful nonimmigrant": "Not a U.S. citizen and also not a Lawful Permanent Resident (Green Card holder). People who enter the U.S. on a temporary basis—whether for tourism, business, temporary work, or study.",
  "Lawful Permanent Resident": "Also known as Green Card holder. A person authorized to live and work in the U.S. indefinitely.",
  "LPR": "Lawful Permanent Resident/Green Card holder. A person authorized to live and work in the U.S. indefinitely.",
  "Permanent Resident Card": "Also known as Green Card. Form of identification proving LPR status.",
  "Green Card": "Permanent Resident Card. Form of identification proving LPR status.",
  "A-Number": "Alien Registration Number.",
  "IRS": "Internal Revenue Service.",
  "Statutory period": "The period of time required by law. For naturalization, it refers to the 3–5 years of continuous residence in the U.S.",
  "Civics": "U.S. history and government.",
  "VAWA": "Violence Against Women Act.",
  "N-470": "Application to Preserve Residence for Naturalization Purposes.",
  "N-648": "Medical Certification for Disability Exceptions.",
  "N-400": "Application for Naturalization.",
  "G-1450": "Authorization for Credit Card Transaction.",
  "I-90": "Application to Replace Permanent Resident Card.",
  "G-28": "Notice of Entry of Appearance as Attorney or Representative.",
  "FS-240": "Report of Birth Abroad of a Citizen of the United States of America.",
  "N-426": "Request for Certification of Military or Naval Service.",
  "DD Form 214": "Certificate of Release or Discharge from Active Duty.",
  "NGB Form 22": "National Guard Report of Separation and Record of Service.",
  "I-912": "Request for Fee Waiver.",
  "I-797C": "Notice of Action. It is often an appointment notice or a receipt.",
  "N-14": "Request for Additional Information, Documents, or Forms.",
  "N-336": "Request for a Hearing on a Decision in Naturalization Proceedings.",
  "N-445": "Notice of Naturalization Oath Ceremony.",
  "SEVP": "Student and Exchange Visitors Program.",
  "CPT": "Curricular Practical Training.",
  "OPT": "Optional Practical Training.",
  "I-20": "Certificate of Eligibility for Nonimmigrant Student Status.",
  "DS-160": "Online Nonimmigrant Visa Application.",
  "I-901": "SEVIS fee.",
  "I-94": "Electronic Arrival/Departure Record for foreign visitors.",
  "INA Section 221(g)": "Temporary visa denial due to incomplete application or documentation.",
  "I-765": "Application for Employment Authorization.",
  "DSO": "Designated School Official.",
  "EIN": "Employer Identification Number.",
  "I-983": "Training Plan for STEM OPT Students.",
  "EAD": "Employment Authorization Document.",
  "I-130": "Petition for Alien Relative.",
  "I-130A": "Supplemental Information for Spouse Beneficiary.",
  "I-864": "Affidavit of Support.",
  "I-751": "Petition to Remove Conditions on Residence.",
  "G-1145": "E-Notification of Application/Petition Acceptance.",
  "I-485": "Application to Register Permanent Residence or Adjust Status.",
  "I-797": "Notice of Action. Receipt or approval of an application or petition.",
  "I-290B": "Notice of Appeal or Motion.",
  "AR-11": "Alien’s Change of Address Card.",
  "DS-261": "Choice of Address and Agent.",
  "I-944": "Declaration of Self-Sufficiency.",
  "I-131": "Application for Travel Document.",
  "I-693": "Report of Immigration Medical Examination and Vaccination Record.",
  "DS-260": "Immigrant Visa Electronic Application.",
  "I-824": "Application for Action on an Approved Application or Petition.",
  "I-601": "Application for Waiver of Grounds of Inadmissibility.",
  "I-551": "Permanent Resident Card, also known as the Green Card. Renewable every 10 years.",
  "I-551 Stamp": "Passport stamp serving as temporary proof of permanent residence.",
  "IRS Form 1040": "U.S. Individual Income Tax Return.",
  "I-864A": "Contract Between Sponsor and Household Member.",
  "Petition": "Form I-130 request establishing the qualifying family relationship.",
  "Petitioner": "U.S. citizen or resident who files the family-based petition.",
  "Sponsor": "Same as Petitioner. U.S. citizen or resident who files the family-based petition.",
  "Beneficiary": "Relative being sponsored for the green card.",
  "Applicant": "Same as Beneficiary at the visa stage.",
  "Immediate Relative": "Spouse, unmarried child < 21, or parent of a U.S. citizen.",
  "Adjustment of Status": "Applying for the green card inside the U.S. with Form I-485.",
  "AOS": "Adjustment of Status. Applying for the green card inside the U.S. with Form I-485.",
  "Affidavit of Support": "Form I-864. Sponsor’s financial support promise.",
  "NVC": "National Visa Center. Schedules consular interviews and collects documents.",
  "Consular Processing": "Completing the immigrant-visa process abroad at a U.S. embassy.",
  "USCIS": "Agency that adjudicates immigration petitions inside the U.S.",
  "Documentarily Qualified": "NVC has accepted all forms and documents; case awaits interview.",
  "DQ": "Documentarily Qualified. Same as above.",
  "Visa Number": "Available immigrant-visa slot.",
  "Request for Evidence": "USCIS request for missing or clarifying documents.",
  "Service Center": "Specific USCIS facility processing the petition.",
  "Priority Date": "Filing date that establishes a case’s position in line.",
  "Consular Electronic Application Center": "Online portal for CEAC-related immigration case tracking.",
  "CEAC": "Same as Consular Electronic Application Center.",
  "Invoice ID Number": "NVC login code for CEAC.",
  "Affidavit of Support Fee": "Fee for processing Form I-864.",
  "Biometrics": "Fingerprints, photo, and signature collected for background checks.",
  "Federal Poverty Guidelines": "Chart setting sponsor’s minimum earnings (125%).",
  "Household Size": "People counted to determine required income on I-864.",
  "Joint Sponsor": "Second sponsor who meets income rules if primary does not.",
  "Public Charge": "Standard to assess if immigrant may rely on public aid.",
  "Civil Documents": "Official records supporting the case (e.g., birth, marriage).",
  "Police Certificate": "Record of applicant’s criminal history.",
  "Certified Translation": "Signed English translation asserting accuracy.",
  "Interview Appointment Letter": "Notice of interview date, time, and place.",
  "Panel Physician": "Overseas doctor approved for immigration medical exams.",
  "Civil Surgeon": "U.S.-based doctor approved for immigration medical exams.",
  "Class A Condition": "Medical issue making applicant inadmissible until resolved.",
  "Class B Condition": "Medical issue noted but not inadmissible.",
  "Sealed Medical Envelope": "Tamper-proof exam results packet.",
  "Vaccination Requirements": "Required shots per CDC guidelines.",
  "IMBRA Pamphlet": "Rights and resources for immigrant spouses and fiancés.",
  "Consular Officer": "Interviews and decides consular visa cases.",
  "Administrative Processing": "Extra security/background review after interview.",
  "Visa Issuance": "Immigrant visa printed and placed in passport.",
  "Green Card Stamp": "I-551 stamp. Temporary proof of permanent residence.",
  "Immigrant Visa": "Visa granting permanent residence upon U.S. entry.",
  "IV": "Same as Immigrant Visa.",
  "USCIS Immigrant Fee": "$220 fee for producing and mailing the green card.",
  "Notice of Intent to Deny": "USCIS warning letter about possible denial.",
  "NOID": "Same as Notice of Intent to Deny.",
  "Board of Immigration Appeals": "Court hearing appeals of USCIS denials.",
  "BIA": "Same as Board of Immigration Appeals.",
  "Port of Entry": "Where CBP admits immigrants into the U.S.",
  "CBP": "Customs and Border Protection. Activates immigrant visas at entry.",
  "Social Security Number": "Nine-digit ID used for work, taxes, and credit.",
  "Conditional Permanent Resident": "Two-year green-card holder in specific categories.",
  "CPR": "Same as Conditional Permanent Resident.",
  "Conditional Residence": "Two-year green-card status for certain applicants.",
  "Naturalization": "Process of becoming a U.S. citizen from LPR status.",
  "Continuous Residence": "Time spent in U.S. before applying for citizenship.",
  "Good Moral Character": "Legal behavior standard for naturalization.",
  "Selective Service": "Draft registration for male residents aged 18–25.",
  "Certified Copy": "Government-issued duplicate with legal validity.",
  "I-130 Petition": "Form proving parent-child relationship for immigration.",
  "Notice of Action": "USCIS receipt or approval notice.",
  "Concurrent Filing": "Submitting I-130 and I-485 together.",
  "ACH Payment": "Electronic bank transfer for NVC fees.",
  "Domicile": "Sponsor’s principal U.S. residence.",
  "Visa Availability": "Whether an immigrant-visa number is open.",
  "Immigrant Visa Fee": "Fee for visa issuance.",
  "CEAC Confirmation Page": "Proof that a CEAC form was submitted.",
  "Checklist": "NVC list of deficiencies to correct.",
  "Principal Applicant": "Main green card applicant.",
  "Derivative Applicant": "Family member immigrating under same petition.",
  "Sponsor’s Obligation Period": "Time sponsor remains financially responsible.",
  "Reciprocity Schedule": "Guide to acceptable civil documents by country.",
  "Technical Instructions": "CDC medical guidelines for immigration.",
  "Adjustment Interview": "In-person USCIS interview for I-485 cases.",
  "Visa Packet": "Sealed or digital file accompanying an immigrant visa.",
  "Welcome Notice": "USCIS letter confirming green card approval.",
  "Immigrant Fee": "Same as USCIS Immigrant Fee.",
  "Admissibility": "Lack of legal barriers to enter the U.S.",
  "Eligibility": "Meeting the criteria for a category.",
  "Identification": "State ID or license after becoming an LPR.",
  "Integration": "Steps to settle into life in the U.S.",
  "Re-entry Permit": "Travel document that protects LPR status abroad."
};

export default GreencardGlossary;