import Link from '@mui/material/Link';

export const paSteps = [
    { id: 1, label: 'Step 1: Confirm Eligibility and Relationship' },
    { id: 2, label: 'Step 2: Gather Required Documents for the Petition' },
    { id: 3, label: 'Step 3: File Form I-130 Petition and Receive Approval' },
    { id: 4, label: 'Step 4: File Adjustment of Status (I-485)' },
    { id: 5, label: 'Step 5: Pay Required Fees' },
    { id: 6, label: 'Step 6: Submit Adjustment Application (I-485)' },
    { id: 7, label: 'Step 7: Complete Affidavit of Support (Form I-864) & Financial Documents' },
    { id: 8, label: 'Step 8: Collect and Submit Civil Documents' },
    { id: 9, label: 'Step 9: Complete the Medical Examination' },
    { id: 10, label: 'Step 10: Prepare for the Interview' },
    { id: 11, label: 'Step 11: Attend the Interview and Receive Decision' },
    { id: 12, label: 'Step 12: U.S. Entry and Post-Arrival Next Steps' }
]

export const paChecklist = {
    1: [
        { section: 'Eligibility Checklist' },
        { id: 1.1, label: 'Verify Sponsor’s Status/Age:', checked: false },
        { id: 1.2, label: 'Confirm the petitioner is a U.S. citizen', checked: false, nested: true },
        { id: 1.3, label: 'At least 21 years old', checked: false, nested: true },
        { id: 1.4, label: 'Lawful permanent residents cannot sponsor a parent', checked: false, nested: true },
        { id: 1.5, label: 'Confirm Relationship: Ensure the person you plan to sponsor is legally your parent (biological mother or father, adoptive parent, or step-parent) as recognized by U.S. immigration law', checked: false },
        { id: 1.6, label: 'If sponsoring a step-parent: The marriage between your natural parent and step-parent must have occurred before your 18th birthday', checked: false, nested: true },
        { id: 1.7, label: 'If sponsoring an adoptive parent: The adoption must have been finalized before your 16th birthday', checked: false, nested: true },
        { id: 1.8, label: 'Check Parent’s Location: Note whether:', checked: false },
        { id: 1.9, label: 'Your parent is in the U.S. and must apply for Adjustment of Status (AOS) or', checked: false },
        { id: 1.101, label: 'Your parent is abroad and will require consular processing', checked: false },
        { id: 1.11, label: 'Parent is not inadmissible for a reason that cannot be resolved (e.g. serious criminal or immigration violations). (Minor inadmissibility issues can often be addressed with waivers later, but consider consulting an immigration attorney if any potential issues.)', checked: false },
        { id: 1.12, label: 'Review Visa Category: Recognize that parents of U.S. citizens qualify as immediate relatives (IR-5), which means visas are immediately available – there is no annual cap or waitlist for visa numbers', checked: false },
        { section: 'Required Documents' },
        { id: 1.13, label: 'Proof of U.S. Citizenship (Sponsor), one of the following:', checked: false },
        { id: 1.14, label: 'U.S. birth certificate', checked: false, nested: true },
        { id: 1.15, label: 'U.S. passport', checked: false, nested: true },
        { id: 1.16, label: 'Certificate of Naturalization/Citizenship', checked: false, nested: true },
        { id: 1.17, label: 'Proof of Parent-Child Relationship:', checked: false },
        { id: 1.18, label: 'Your birth certificate naming your parent. If sponsoring father, this certificate should show both parents’ names.', checked: false, nested: true },
        { id: 1.19, label: 'If sponsoring the father and your parents were ever married: their marriage certificate (to establish the legal paternal relationship).', checked: false, nested: true },
        { id: 1.201, label: 'If sponsoring a step-parent: your birth certificate (showing your birth parents) and the marriage certificate of your birth parent and step-parent (showing marriage before your 18th birthday). Include proof of termination of any prior marriages (divorce/death certificates) for your natural parent or step-parent.', checked: false, nested: true },
        { id: 1.21, label: 'If sponsoring an adoptive parent: adoption decree showing the adoption was finalized before you turned 16, and evidence of any prior custody if applicable.', checked: false, nested: true },
        { id: 1.22, label: 'Proof of Petitioner’s Age: Your birth certificate or passport (to show you are 21 or older).', checked: false },
        { id: 1.23, label: 'Name Change Documents (if applicable): Legal documents for any name changes for you or your parent (marriage certificate, court order, etc.).', checked: false }
    ],
    2: [
        { section: 'Task Checklist' },
        { id: 2.1, label: 'Obtain Official Documents: Collect current, certified copies of all civil documents needed for the petition.', checked: false },
        { id: 2.2, label: 'This includes those listed in Step 1 Ensure you have originals or certified copies on hand; you will submit copies with the petition and later need originals for the interview.', checked: false, nested: true },
        { id: 2.3, label: 'Translations: If any document (birth certificate, marriage certificate, etc.) is not in English (or the official language of the country where you’re applying), get a certified English translation', checked: false },
        { id: 2.4, label: 'Photographs: Prepare passport-style photos if required.', checked: false },
        { id: 2.5, label: 'USCIS requires two recent identical color passport photos of the parent for the adjustment of status application (submitted later with Form I-485), but for the I-130 petition, photos are not required. (Photos will also be needed for visa processing later in consular processing, per Department of State instructions.)', checked: false, nested: true },
        { id: 2.6, label: 'Form I-130 Preparation: Download and read the latest instructions for Form I-130, Petition for Alien Relative. Familiarize yourself with each part of the form and the supporting evidence requirements. You can choose to file online through USCIS’s website or by mailing a paper form.', checked: false },
        { id: 2.7, label: 'Fees: Be prepared to pay the I-130 filing fee (currently $535 for each parent petition). If filing online, have a credit/debit card or bank info ready; if by mail, you’ll typically pay by check or money order (follow USCIS payment instructions).', checked: false },
        { section: 'Required Documents' },
        { id: 2.8, label: 'Form I-130 Petition (completed and signed by the petitioner)', checked: false },
        { id: 2.9, label: 'Filing fee $535 (check, money order, or credit card payment authorization, as applicable).', checked: false },
        { id: 2.101, label: 'Petitioner’s proof of U.S. citizenship: e.g., copy of U.S. passport, naturalization certificate, or U.S. birth certificate.', checked: false },
        { id: 2.11, label: 'Beneficiary’s civil documents: copy of your parent’s birth certificate (and marriage certificate if petition is for father or step-parent as described in Step 1). If names have changed, include legal name change documents.', checked: false },
        { id: 2.12, label: 'Evidence of relationship: your birth certificate naming your parent (and for father/step-parent cases, marriage certificates or legitimation proof as required). If you are petitioning your father and were born out of wedlock, include proof of legitimation or evidence of a bona fide parent-child relationship before age 21 (such as correspondence, photos, financial support).', checked: false },
        { id: 2.13, label: 'Two passport-style photos of the petitioner and beneficiary (if specifically required). (USCIS no longer requires photos for I-130 petitions for parents, but double-check form instructions. Photos will be needed later for visa or adjustment steps.)', checked: false },
        { id: 2.14, label: 'Form G-1145 (optional): If filing by mail, you can attach Form G-1145 to request email/text notification when USCIS accepts your petition.', checked: false }
    ],
    3: [
        { section: 'Task Checklist' },
        { id: 3.1, label: 'Submit the I-130 to USCIS: File the petition with USCIS either online via your USCIS account or by mailing the paper form to the address in the instructions (usually the Chicago Lockbox for family petitions)', checked: false },
        { id: 3.2, label: 'Double-check that you signed the form and included all supporting documents and the correct fee.', checked: false, nested: true },
        { id: 3.3, label: 'Online filing: Upload scanned copies of supporting documents and pay electronically.', checked: false, nested: true },
        { id: 3.4, label: 'By mail: Assemble the application packet with all required copies and the check or money order for the fee. It’s good practice to use a trackable mailing service.', checked: false, nested: true },
        { id: 3.5, label: 'USCIS Receipt Notice: Wait for a Form I-797C Notice of Action (receipt notice) from USCIS confirming they received your petition and assigning a case number.', checked: false }, { id: 3.6, label: 'If you filed online, you will get an electronic receipt immediately; if by mail, the paper receipt arrives in a few weeks. The receipt is proof that your case is in process.', checked: false, nested: true },
        { id: 3.7, label: 'USCIS Processing: During this period, USCIS will review your petition.', checked: false },
        { id: 3.8, label: 'They may send a Request for Evidence (RFE) if something is missing or unclear – if so, respond by the deadline with the requested info to avoid denial. You can check your case status online using the receipt number.', checked: false, nested: true },
        { id: 3.9, label: 'Approval Notice: If USCIS approves the I-130, you (the petitioner) will get an approval notice by mail (Form I-797).', checked: false },
        { section: 'Required Documents' },
        { id: 3.11, label: 'USCIS Approval Notice: Keep the I-797 approval notice safe. You’ll need the receipt number and case details for NVC or for filing AOS.', checked: false },
        { id: 3.12, label: 'Form I-485 & Supporting Docs: If not already filed, prepare the I-485 packet (Step 4) to submit with a copy of the I-130 approval notice.', checked: false }
    ],
    4: [
        { section: 'Task Checklist' },
        { id: 4.1, label: 'File Form I-485 Package: If your parent is eligible to adjust status (was inspected & admitted to the U.S., and no bars apply), file Form I-485, Application to Register Permanent Residence or Adjust Status with USCIS to start the green card application. You can file the I-485 at the same time as the I-130 (concurrently) since parent visas are immediately available, or file it after I-130 approval. Include all required forms and evidence in the packet (see below).', checked: false },
        { id: 4.2, label: 'Include Required Forms: Along with Form I-485, include:', checked: false },
        { id: 4.3, label: 'Form I-864 (Affidavit of Support) completed by the sponsor – this shows you have sufficient financial means to support your parent. (Details on this in Step 7.)', checked: false, nested: true },
        { id: 4.4, label: 'Form I-693 (Medical Exam Report) – a sealed report from a USCIS-certified civil surgeon. USCIS currently instructs applicants to submit the medical exam with the I-485 to avoid delays. (Details in Step 9.)', checked: false, nested: true },
        { id: 4.5, label: 'Form I-765 (Work Permit) and Form I-131 (Advance Parole travel document), if your parent wants to work or travel while the I-485 is pending. Note: As of 2025, separate fees may be required for these applications. Filing them is optional, but it’s common to do so your parent can get a work permit and re-entry travel document during the wait.', checked: false, nested: true },
        { id: 4.6, label: 'Supporting documents: Copies of your parent’s passport (photo page + entry stamp/visa page to prove lawful entry), birth certificate, marriage certificates (if applicable), and your proof of citizenship – basically much of the same evidence as the I-130, plus any additional documents USCIS requires (like Form I-94 admission record, etc.).', checked: false, nested: true },
        { id: 4.7, label: 'Fee payment: The I-485 filing fee (check USCIS’s Fee Schedule for the current amount; it has been around $1,140 plus an $85 biometrics fee) must be included (if not filing fee-waived). If filing concurrently with I-130 by mail, separate payments for each form are usually required.', checked: false, nested: true },
        { id: 4.8, label: 'Obtain Receipt and Biometrics Notice: After filing, USCIS will issue a receipt for the I-485 and schedule a biometrics appointment for your parent (for fingerprinting and photo). This is usually within a month or two of filing. Make sure your parent attends the biometrics appointment at the USCIS Application Support Center on the date given (reschedule if necessary, using the instructions on the notice).', checked: false },
        { id: 4.9, label: 'AOS Processing: Your parent can remain in the U.S. while the I-485 is processed. If you filed for a work permit (Form I-765) and travel document (Form I-131), those are typically processed in a few months and mailed as interim benefits. USCIS will review the background checks, and eventually schedule an interview at your local USCIS field office (see Steps 10–11 for interview preparation).', checked: false },
        { section: 'Required Documents' },
        { id: 4.101, label: 'Completed Form I-485 (with all pages signed/filled).', checked: false },
        { id: 4.11, label: 'Form I-864 Affidavit of Support (from petitioner) + supporting financial evidence (tax returns, W-2s, job letter – see Step 7).', checked: false },
        { id: 4.12, label: 'Form I-693 Medical Exam (sealed envelope from civil surgeon).', checked: false },
        { id: 4.13, label: 'Form I-765 and I-131, if applying for EAD/Advance Parole (optional, with photos if required and any additional fees or the I-485 fee receipt as applicable).', checked: false },
        { id: 4.14, label: 'Copy of I-130 receipt or approval notice (to tie the cases together, especially if filing after I-130 approval).', checked: false },
        { id: 4.15, label: 'Parent’s documents:', checked: false },
        { id: 4.16, label: 'Copy of passport biographic page', checked: false, nested: true },
        { id: 4.17, label: 'Copy of visa and I-94 record to prove lawful entry', checked: false, nested: true },
        { id: 4.18, label: 'Birth certificate', checked: false, nested: true },
        { id: 4.19, label: 'Marriage certificate(s) if any', checked: false, nested: true },
        { id: 4.201, label: 'Any certified police court records if the parent has an arrest history (required to prove admissibility)', checked: false, nested: true },
        { id: 4.21, label: 'Petitioner’s documents:', checked: false },
        { id: 4.22, label: 'Proof of citizenship', checked: false, nested: true },
        { id: 4.23, label: 'Any evidence already submitted with I-130 (to ensure the AOS file has it).', checked: false, nested: true },
        { label: 'Fee payment: Check or money order for the I-485 fee (and biometrics), or credit card form if allowed. (Currently around $1,225 total for I-485 with biometrics, but verify current fee).', textOnly: true },
    ],
    5: [
        { label: 'This step is largely Not Applicable – the main fees (I-130 and I-485 filing fees) are paid to USCIS at filing. However, note these AOS-related fee points:', textOnly: true },
        { section: 'Task Checklist' },
        { id: 5.1, label: 'The Form I-485 filing fee (approximately $1,225 including biometrics as of recent fee schedule) is paid when you submit the adjustment applicationuscis.gov. Make sure you paid the correct amount to avoid rejection', checked: false },
        { id: 5.2, label: 'If you opted to file Forms I-765 or I-131 with the I-485, check if additional fees are needed (after April 2024, new USCIS rules require separate fees for those forms). Historically, these were free with a paid I-485 (for filings before 2024)', checked: false },
        { id: 5.3, label: 'There is a USCIS Immigrant Fee of $220 that new immigrants coming via consular processing must pay for green card production – AOS applicants do not pay this, since they will already have paid all fees with the I-485 and will receive their green card directly without entering on an immigrant visa.', checked: false },
        { section: 'Required Documents/Information for Fee Payment' },
        { id: 5.4, label: 'AOS Case Number and Invoice ID (from your welcome letter) – needed to log in and confirm you’re paying for the correct case.', checked: false },
        { id: 5.5, label: 'U.S. Bank Routing Number and Account Number – for the account from which fees will be withdrawn.', checked: false },
        { id: 5.6, label: 'Sufficient funds in the account to cover the fees (ensure the payment won’t bounce).', checked: false },
        { id: 5.7, label: 'A printer or PDF saver (optional) to keep records of the payment confirmations.', checked: false },
        { id: 5.8, label: '(No physical documents need to be sent for fees – it’s all online. Just keep the receipts.)', checked: false }
    ],
    6: [
        { id: 6.1, label: 'If you filed the I-485 in Step 4, you’ve essentially completed the “visa application” on the USCIS side. Your parent’s pending I-485 is their green card application. In this step, there’s nothing additional to submit for AOS except responding to any USCIS requests. (Skip to Step 7 for affidavit requirements, which you already handled in the I-485 packet.)', checked: false }
    ],
    7: [
        { label: 'Purpose: The Affidavit of Support is a legally binding document to ensure your parent will not become a public charge. As the petitioner, you must submit this and demonstrate you have sufficient income or assets to support your parent at 125% of the federal poverty guidelines (income threshold depends on household size).', textOnly: true },
        { label: 'You would have included the Form I-864 in the I-485 packet already. If this is the case, you can skip the checklist. If not yet filed, prepare it now to include by following the checklist in this step. If USCIS issues an RFE for it, respond promptly. Generally, for AOS you don’t need to update the I-864 later unless the interview is long delayed and circumstances change.', textOnly: true },
        { section: 'Task Checklist' },
        { id: 7.1, label: 'Choose the Correct I-864 Form: Most petitioners use the standard Form I-864. If your income is very high relative to requirements, you may qualify to use the shorter I-864EZ (check its instructions). But typically, use I-864. Download it from USCIS.gov to ensure you have the latest version.', checked: false },
        { id: 7.2, label: 'Fill Out Form I-864: Fill in your (sponsor’s) information: name, address, employment, and household size. List your parent as the intending immigrant. Be sure to include yourself, your parent, and any other dependents in household size as required by form instructions.', checked: false },
        { id: 7.3, label: 'Income Information: Provide your total income as shown on your most recent federal tax return (Form 1040). You must certify you either filed taxes or were not required to file. You’ll answer questions on current employment and income. If your current income is above the required level for your household size, great. If it’s borderline or below, you might need a joint sponsor or to use assets (see below).', checked: false },
        { id: 7.4, label: 'Attach Financial Evidence: You need to upload (or include, for AOS) supporting documents:', checked: false },
        { id: 7.5, label: 'Federal Tax Transcripts or Tax Returns: NVC usually requires the most recent tax year’s federal tax transcript or a copy of the return (with W-2s/1099s). You can get transcripts from the IRS website. Providing transcripts is often preferable. You may optionally include the last 3 years of tax returns if it strengthens your case, but only the most recent is required.', checked: false, nested: true },
        { id: 7.6, label: 'Proof of Current Employment: e.g., an employment verification letter from your employer stating your position, salary, and job stability; or if self-employed, business license or self-authored statement. Recent pay stubs (last 3–6 months) are also good evidence to show ongoing income.', checked: false, nested: true },
        { id: 7.7, label: 'Proof of Assets (if needed): If your income doesn’t meet the requirement, you can use assets (yours, your parent’s, or household members). Assets could be savings, stocks, property equity, etc. You’d need documentation of the assets’ value (bank statements, appraisals, etc.), and typically the assets must be worth 5 times the difference between your income and the requirement (3 times if sponsoring a spouse or child of a U.S. citizen – but for a parent it’s 5x) (INA 213A rules).', checked: false, nested: true },
        { id: 7.8, label: 'Joint Sponsor (if needed): If you cannot meet the requirement alone, you can find a joint sponsor – another U.S. citizen or resident who meets the income requirements and is willing to also sponsor your parent. A joint sponsor submits their own I-864 and financial docs. They are equally responsible for supporting the immigrant, so this is a serious commitment. (Each joint sponsor covers one immigrant; since you’re sponsoring one parent, only one joint sponsor max would be allowed if needed.)', checked: false, nested: true },
        { id: 7.9, label: 'Household Member Contribution: If a relative in your household wants to contribute their income, they can file form I-864A as a household member. This is less common for parent cases but an option if, for example, your spouse or adult child living with you wants to add their income to meet the requirement.', checked: false, nested: true },
        { id: 7.101, label: 'Domicile: You must affirm on the I-864 that your domicile is in the United States. If you live abroad, provide an explanation and evidence of how you still maintain U.S. domicile or will re-establish it by the time your parent immigrates. Examples: voting record, maintaining a U.S. residence, or a letter explaining you’re moving back to the U.S. for your parent’s relocation. Upload evidence if necessary (e.g., job offer in U.S., lease, etc.).', checked: false },
        { id: 7.11, label: 'Review and Submit: After uploading all required financial docs and civil docs (next step), you’ll formally submit the documents.', checked: false },
        { section: 'Required Documents (Financial):' },
        { id: 7.12, label: 'Form I-864 (completed and signed)', checked: false },
        { id: 7.13, label: 'Most recent Federal Tax Transcript (or copy of tax return + W2s)', checked: false },
        { id: 7.14, label: 'Evidence of current employment/income: e.g., employment letter, recent pay stubs, or if self-employed, Schedule C/K-1, etc., to confirm current income.', checked: false },
        { id: 7.15, label: 'Proof of assets (if using assets): bank statements for savings, property appraisals, etc., plus proof of ownership of those assets.', checked: false },
        { id: 7.16, label: 'Joint Sponsor’s I-864 and documents (if you have a joint sponsor) – similar set of documents for them.', checked: false },
        { id: 7.17, label: 'Household Member’s I-864A and documents (if using household member income).', checked: false },
        { id: 7.18, label: 'Proof of U.S. domicile (if needed): evidence that you maintain a U.S. residence or intend to resume domicile (for sponsors living abroad)', checked: false }
    ],
    8: [
        { label: 'Purpose: These are the personal documents that prove your parent’s identity, family relationships, and any required background records. Many of these were already submitted with the I-485. ', textOnly: true },
        { section: 'Task Checklist' },
        { id: 8.1, label: 'Gather Required Civil Documents: Each immigrant must have certain documents. For a parent (IR-5) case, prepare:', checked: false },
        { id: 8.2, label: 'Birth Certificate of the Parent (Beneficiary): Must be the full birth certificate from the official registry in the country of birth, showing the parent’s name, date of birth, and parents’ names. If only short form is available, see country-specific instructions. If unavailable, obtain a certificate of non-availability and other secondary evidence.', checked: false, nested: true },
        { id: 8.3, label: 'Marriage Certificate: If your parent is or ever was married, obtain their marriage certificate(s). If widowed, a death certificate of spouse; if divorced, divorce decrees for all prior marriages. (Even if the prior spouse is not relevant to the petition, they need to show those marriages were legally terminated.)', checked: false, nested: true },
        { id: 8.4, label: 'Court and Prison Records: If your parent has ever been convicted of a crime, certified copies of court records and any prison records are needed . This includes even expunged cases or pardoned cases – they should bring records and certified English translations if applicable.', checked: false, nested: true },
        { id: 8.5, label: 'Military Records: If your parent served in the military of any country, get a copy of their military record/discharge if available.', checked: false, nested: true },
        { id: 8.6, label: 'Petitioner’s Birth Certificate: Because this is a parent case, your birth certificate (the petitioner’s) is crucial evidence of the relationship. Even though you submitted it for the I-130', checked: false, nested: true },
        { id: 8.7, label: 'Other Civil Docs: e.g., adoption papers (if parent is adoptive), name change documents, etc., if applicable to your parent’s situation. Basically, any document establishing identity or relationships that are pertinent.', checked: false, nested: true },
        { id: 8.8, label: 'Translation of Documents: Ensure any document not in English (or not in the official language of the country of the consulate) has a certified English translation. Commonly, birth, marriage, police certs etc., if issued in another language, must be translated. Upload the translation together with the document.', checked: false },
        { id: 8.9, label: 'Document Keeping: Keep the physical originals of all civil documents in a safe place. Your parent will need to bring originals or certified copies of each of these to the visa interview. For AOS, your parent should bring originals to the USCIS interview as well (especially birth certificates, marriage/divorce certs).', checked: false },
        { section: 'Required Documents' },
        { id: 8.101, label: 'Birth Certificate (long form) – plus translation if not in English', checked: false },
        { id: 8.11, label: 'Marriage Certificate(s) – for any marriage your parent has had, current or prior (and spouse’s death certificate or divorce decree for each marriage that ended)', checked: false },
        { id: 8.12, label: 'Court/Criminal Records – if applicable (any convictions, police reports if available, etc.)', checked: false },
        { id: 8.13, label: 'Military Record – if applicable', checked: false },
        { id: 8.14, label: 'Petitioner’s Birth Certificate (your birth certificate, to prove relationship)', checked: false },
        { id: 8.15, label: 'Any other relevant civil docs – e.g., adoption decree (if parent is adoptive), legal name change documents, etc.', checked: false },
        { id: 8.16, label: 'Certified Translations for any above not in English', checked: false }
    ],
    9: [
        { label: 'Before the final interview, your parent must undergo a medical exam by an authorized physician to ensure they have required vaccinations and no inadmissible health conditions.', textOnly: true },
        { label: 'The medical exam is done by a USCIS-designated civil surgeon. Ideally, you completed this in Step 4 and submitted the Form I-693 sealed envelope with the I-485. If not, you must get it done before the interview and either submit the sealed results via RFE or bring to the interview.', textOnly: true },
        { section: 'Task Checklist' },
        { label: 'Schedule the Exam:', textOnly: true },
        { id: 9.1, label: 'Find a civil surgeon in your area via the USCIS tool or list.', checked: false, nested: true },
        { id: 9.2, label: 'Call to schedule a Form I-693 medical exam. Mention it’s for a green card (adjustment of status) so they know to follow USCIS guidelines.', checked: false, nested: true },
        { id: 9.3, label: 'Try to do this well before the interview (or earlier, as you may have filed it with the application).', checked: false, nested: true },
        { label: 'Prepare Required Items for Exam: Typically, your parent should bring:', textOnly: true },
        { id: 9.4, label: 'ID', checked: false, nested: true },
        { id: 9.5, label: 'Vaccination records', checked: false, nested: true },
        { id: 9.6, label: 'Any prior medical records of significance (like chest X-ray or TB treatment records if applicable).', checked: false, nested: true },
        { id: 9.7, label: 'The I-693 form for the doctor to fill, although most civil surgeons have them.', checked: false, nested: true },
        { id: 9.8, label: 'Fees for the exam vary and are usually paid by the applicant.', checked: false, nested: true },
        { label: 'Undergo the Examination: The doctor will review medical history, administer needed vaccinations, do a physical exam, and conduct required tests (blood tests, possibly chest X-ray for TB, etc.).', textOnly: true },
        { id: 9.9, label: 'Vaccinations: Required immunizations include those for measles, mumps, rubella, polio, tetanus, varicella, influenza, COVID-19 (as of early 2023; note: as of 2025 COVID vaccine is no longer required per updated CDC guidelines), and others as per CDC technical instructions. The doctor will assess and give any missing vaccines.', checked: false, nested: true },
        { id: 9.101, label: 'Communicable diseases: The exam includes tests for tuberculosis (TB blood test or skin test, and chest X-ray if needed) and syphilis (blood test), etc. If TB test is positive, a chest X-ray will confirm if active TB – this can add time, so doing exam 1-2 weeks before interview is wise.', checked: false, nested: true },
        { label: 'Result Handling:', textOnly: true },
        { id: 9.11, label: 'The doctor will give a sealed envelope with Form I-693 and test results. Do not open it. If you haven’t submitted it to USCIS yet, you’ll either mail it as response to an RFE or hand-carry it to the interview as directed. (USCIS may reject the form if the envelope is tampered.) The doctor may also give an extra copy for your records – you can open that one.', checked: false, nested: true },
        { label: 'Follow Any Special Instructions:', textOnly: true },
        { id: 9.12, label: 'If the doctor finds a health issue that requires follow-up (e.g., sputum testing for TB which takes 8 weeks, or needing additional vaccine doses), follow instructions carefully.', checked: false, nested: true },
        { id: 9.13, label: 'This could mean delaying the visa issuance until clearance is obtained. Minor issues like a cold won’t affect visa issuance, but certain conditions (active TB, untreated syphilis, drug addiction, etc.) can delay or make one inadmissible until treated.', checked: false, nested: true },
        { label: 'Obtain Vaccination Record:', textOnly: true },
        { id: 9.14, label: 'The medical report will include a vaccination supplement listing which vaccines your parent has received or which are not medically appropriate. For consular cases, the panel physician’s report suffices.', checked: false, nested: true },
        { id: 9.15, label: 'The civil surgeon will complete the vaccination record on Form I-693. Make sure all required vaccines are addressed to avoid an RFE.', checked: false, nested: true },
        { section: 'Required Documents/Items for Medical Exam:' },
        { id: 9.16, label: 'Passport or government ID (panel physicians will require a passport for consular cases; civil surgeons need ID, preferably passport).', checked: false },
        { id: 9.17, label: 'Appointment notice: just tell them it’s for Form I-693).', checked: false },
        { id: 9.18, label: 'Immunization records: any childhood or adult vaccine records to avoid re-vaccination.', checked: false },
        { id: 9.19, label: 'Medical history list: medications, known health issues – to share with doctor honestly.', checked: false },
        { id: 9.201, label: 'Cash/Credit for fee: payment as required by the clinic.', checked: false },
        { id: 9.21, label: '2-4 passport photos (some doctors require photos to attach to the forms, though digital photo is often taken). Check clinic instructions.', checked: false }
    ],
    10: [
        { label: 'Now your parents are nearing the finish line. Preparation is key for the interview.', textOnly: true },
        { section: 'Task Checklist' },
        { label: 'Await Interview Notice', textOnly: true },
        { id: 10.1, label: 'USCIS will send an Interview Notice (Form I-797) with the date, time, and location (your local USCIS Field Office).', checked: false, nested: true },
        { id: 10.2, label: 'This usually comes several weeks in advance and the notice will also list what to bring.', checked: false, nested: true },
        { label: 'Review Your Application', textOnly: true },
        { id: 10.3, label: 'Go through the I-485 and all forms you submitted.', checked: false, nested: true },
        { id: 10.4, label: 'Make sure your parent is familiar with all the information (dates, addresses, etc.). The officer may ask about details from the forms.', checked: false, nested: true },
        { label: 'Gather Originals: Prepare a file with original documents', textOnly: true },
        { id: 10.5, label: 'Your parent’s passport (with the visa and I-94 if applicable)', checked: false, nested: true },
        { id: 10.6, label: 'Birth certificate', checked: false, nested: true },
        { id: 10.7, label: 'Marriage/divorce certificates', checked: false, nested: true },
        { id: 10.8, label: 'Your birth certificate (to prove relationship)', checked: false, nested: true },
        { id: 10.9, label: 'Any other civil docs submitted, and the I-797 approval notices.', checked: false, nested: true },
        { id: 10.101, label: 'USCIS will likely want to see original proof of the parent-child relationship (birth certificate) and your proof of citizenship (they might ask for your passport or certificate if not already in file).', checked: false, nested: true },
        { label: 'Bring Updated Documents', textOnly: true },
        { id: 10.11, label: 'If any circumstances changed or any document has been updated (e.g., your parent renewed their passport, or you have a newer financial document), bring those.', checked: false, nested: true },
        { id: 10.12, label: 'Also bring an updated Affidavit of Support supporting evidence (like latest pay stubs, maybe latest tax return if a new year has passed) in case the officer asks.', checked: false, nested: true },
        { id: 10.13, label: 'For example, if it’s now 2026 and your I-864 had 2024 taxes, having 2025 tax info wouldn’t hurt.', checked: false, nested: true },
        { label: 'Medical Exam Results', textOnly: true },
        { id: 10.14, label: 'If the I-693 was not submitted earlier or if USCIS specifically requests a new one, bring the sealed medical envelope to the interview.', checked: false, nested: true },
        { label: 'Prepare Your Parent', textOnly: true },
        { id: 10.15, label: 'Go over common interview questions.', checked: false, nested: true },
        { id: 10.16, label: 'For parent cases, the interview is usually straightforward – the officer will verify identity, review the relationship (they may ask you about your birth, your upbringing, etc., to confirm bona fides), and go through the yes/no admissibility questions from the I-485 (questions about crimes, immigration violations, etc.).', checked: false, nested: true },
        { id: 10.17, label: 'If English is a problem, your parent can bring an interpreter for the USCIS interview.', checked: false, nested: true },
        { id: 10.18, label: 'Since you (the petitioner) are the child, you can also attend as a supporter; sometimes field offices allow petitioners in family cases to accompany (check the notice – it often says the petitioning relative “may attend” especially if the applicant isn’t fluent in English).', checked: false, nested: true },
        { label: 'Interpreter (if needed)', textOnly: true },
        { id: 10.19, label: 'If your parent isn’t comfortable in English, line up an interpreter (not a derivative beneficiary, but could be any fluent person).', checked: false, nested: true },
        { id: 10.201, label: 'Some USCIS offices might provide language assistance by phone, but best not to rely on that.', checked: false, nested: true },
        { label: 'Logistics', textOnly: true },
        { id: 10.21, label: 'Plan to arrive at the field office 15-30 minutes early (but not more, due to security and limited waiting space).', checked: false, nested: true },
        { id: 10.22, label: 'Bring the interview notice and government-issued ID to enter the building.', checked: false, nested: true },
        { id: 10.23, label: 'Dress neatly (no need for formal suit, but business casual is good).', checked: false, nested: true },
        { id: 10.24, label: 'Expect airport-like security screening. Phones usually allowed but silenced.', checked: false, nested: true },
        { label: 'During Interview', textOnly: true },
        { id: 10.25, label: 'Both you (petitioner) and your parent (applicant) may be sworn in.', checked: false, nested: true },
        { id: 10.26, label: 'The officer will likely ask your parent questions first. They might confirm your parent’s basic info, then ask about your relationship (for example, “When was your son/daughter born? Where? How often do you see each other?” etc.).', checked: false, nested: true },
        { id: 10.27, label: 'Unlike spousal cases, parent/child relationships are less likely to be scrutinized for fraud unless something seems off.', checked: false, nested: true },
        { id: 10.28, label: 'The officer will also review the medical, affidavit, and eligibility questions. Be ready to provide any missing evidence if they ask (hence having the documents).', checked: false, nested: true },
        { label: 'Honesty', textOnly: true },
        { id: 10.29, label: 'If the officer asks a question and your parent doesn’t know or is unsure, it’s okay to say “I don’t know” or ask for clarification.', checked: false, nested: true },
        { id: 10.301, label: 'Do not guess or lie. If needed, you as petitioner can respectfully clarify answers if your parent is confused (especially if there’s a language issue).', checked: false, nested: true },
        { section: 'Required Items at Interview:' },
        { id: 10.31, label: 'Interview Notice / Appointment Letter (entry ticket to interview).', checked: false },
        { id: 10.32, label: 'Passport (valid, plus any old passports if they contain U.S. visas or travel history – consular might ask for them).', checked: false },
        { id: 10.33, label: 'Original civil documents: Birth, marriage, divorce, police certs, etc. (and translations)', checked: false },
        { id: 10.34, label: 'Petitioner’s proof of citizenship: e.g., original U.S. birth cert or naturalization certificate of the child (for consular interview). For AOS, the officer might ask to see petitioner’s ID or citizenship proof as well, so have it if attending.', checked: false },
        { id: 10.35, label: 'Medical exam results: Sealed I-693 for AOS if not submitted; panel physician envelope for consular if given.', checked: false },
        { id: 10.36, label: 'Photos: Typically two passport photos ( sometimes not needed unless RFE, but bring 2 in case).', checked: false },
        { id: 10.37, label: 'Financial updates: Recent pay stubs, job letter, latest tax return (optional but smart to have in case).', checked: false },
        { id: 10.38, label: 'Supporting evidence of relationship: In parent cases, usually the birth certificate suffices. Rarely, if there’s any adoption or unusual family situation, any custody or adoption papers, family photos, etc., could be useful – but usually not required.', checked: false },
        { id: 10.39, label: 'Interpreter (if applicable): and their ID, if USCIS interview and non-English speaking.', checked: false },
        { id: 10.401, label: 'Pen and notepad: sometimes useful to jot info or in case forms need to be filled at consulate (usually not, but good to have).', checked: false }

    ],
    11: [
        { section: 'Task Checklist At Interview' },
        { id: 11.1, label: 'Your parent (and you, if attending) will check in at the field office, go through security, and wait for your number to be called. In the officer’s office, your parent will be placed under oath to tell the truth. The officer will likely first go over the application: verifying name, address, etc., and asking the yes/no questions from the I-485 about admissibility. They may ask casual questions about the family: e.g., “When did your son become a U.S. citizen?” or “How often do you see your daughter and grandkids?” This is usually just to put the parent at ease and double-check relationship authenticity. Since you provided documents, the officer mostly checks those and might ask to see originals (they often specifically ask for the original birth certificate that shows the petitioner’s birth). Provide any document they request from your organized file.', checked: false },
        { id: 11.2, label: 'The officer may also ask if your parent plans to live with you and if they have ever worked in the U.S. etc. (Unauthorized work is forgiven for immediate relatives, but it’s best to be honest if asked; it won’t bar approval, it’s just part of the record.)', checked: false },
        { id: 11.3, label: 'If everything is in order, many officers will tell you at the end of the interview that the case is recommended for approval or even “Welcome to the United States, you are approved.” Some officers cannot verbally approve on the spot (perhaps needing supervisor review or additional checks). In that case, they might give a paper saying the case is being held for review. Don’t be discouraged; this is common.', checked: false },
        { id: 11.4, label: 'If there were any missing items (like you didn’t bring a required original or the medical exam wasn’t done), the officer might issue a Request for Evidence and give instructions on how to submit that (usually via mail). Once you submit the missing item, they can finalize the case without a second interview typically.', checked: false },
        { id: 11.5, label: 'After Interview: If approved, USCIS will update the online case status to “New Card Is Being Produced” within days, and then “Case Approved.” An approval notice (I-797) will be mailed to your address. The actual green card (plastic card) is generally mailed within 2 to 4 weeks after approval to the address on file. Sometimes it comes sooner. If more than 90 days pass after approval and no card, you can inquire, but that’s rare. If not outright approved at interview, USCIS will usually decide within 120 days. You can follow up if it takes longer.', checked: false },
        { section: 'Post-Interview Outcome:' },
        { label: 'If Approved: Congratulations! Your parent is now a permanent resident. USCIS may stamp the passport with a temporary I-551 stamp if immediate proof is needed (not always done; usually only if you request it for urgent travel/work). Otherwise, the welcome notice and card will come soon.', textOnly: true },
        { label: 'If Pending/221(g): Address whatever is needed as quickly as possible. If it’s just administrative processing with no action required from you, then monitor the status online. Keep your parent’s petitioner contact info updated in case consulate needs to reach out.', textOnly: true },
        { label: 'If Denied: In parent cases, denials are uncommon unless there’s a major issue (like ineligibility or misrepresentation). If it happens, the letter will explain if there’s an appeal or waiver. For I-485 denials, you can file a motion to reopen or appeal in some cases. For visa refusals under certain sections, sometimes a waiver can be applied for. Consult legal help if this occurs.', textOnly: true },
    ],
    12: [
        { section: 'Task Checklist' },
        { id: 12.1, label: 'Approval Notification: Your parent’s status automatically changes to LPR upon approval. There’s no additional entry process since they’re already here. They do not need to leave the country. USCIS will mail the green card to your address on file.', checked: false },
        { id: 12.2, label: 'I-551 Stamp (if needed): If your parent needs urgent proof of status (for example, for a job or emergency travel) before the card comes, you can schedule an InfoPass appointment at a local USCIS office to get a temporary I-551 passport stamp. However, most of the time this isn’t necessary as the card comes quickly and the approval notice plus ID often suffices temporarily for things like driver’s license or jobs (employers can accept the I-797 approval as temporary I-551 for 90 days, though the actual rule is a bit technical).', checked: false },
        { id: 12.3, label: 'Social Security Number: If your parent didn’t have an SSN and you requested one on the I-485 (there’s a box that allows USCIS to notify SSA), they should get a Social Security card in the mail automatically, usually a few weeks after the green card approval. If not, they can take their passport/green card to a SSA office to apply for one about 2-3 weeks after getting the green card (to allow systems to update).', checked: false },
        { id: 12.4, label: 'Green Card Details: The card is typically valid for 10 years (if your parent is granted unconditional permanent residence, which IR-5 is – not conditional). Check the expiration date on the card when it arrives. Note: If your parent had any conditional status (not in this case), there’d be a 2-year card with conditions to remove. For IR-5, it’s a 10-year card.', checked: false },
        { id: 12.5, label: 'Name/Info: If there’s any error on the card (spelling, DOB), you’ll need to file for a replacement (Form I-90) to correct it. Double-check the card upon receipt.', checked: false },
        { id: 12.6, label: 'Rights and Responsibilities: Your parent can now live and work in the U.S. permanentlyuscis.gov. They should carry proof of status (the actual green card) at all times (the law requires it)uscis.gov. They can work for any employer (no EAD needed). They can travel outside the U.S., but should not stay abroad for prolonged periods without precautions (see below).', checked: false },
        { id: 12.7, label: 'Address Change Requirement: If your parent moves, they must file Form AR-11 (Alien’s Change of Address) with USCIS within 10 days of moving, for the rest of their time as an LPR. It’s an online simple form or mail. This is required by law to keep address updated.', checked: false },
        { id: 12.8, label: 'Re-Entry and Trips Abroad: If your parent will travel abroad, trips under 6 months are generally fine. Trips over 6 months may raise questions of abandonment when re-entering; trips over 1 year without a Re-entry Permit can automatically trigger loss of residency. So, if your parent plans to be outside the U.S. for a long time (more than 6 months), consult about getting a re-entry permit (Form I-131, applied from within the U.S. before travel) to preserve status. They should ideally make the U.S. their primary home now.', checked: false },
        { id: 12.9, label: 'Benefits and Naturalization: As an LPR, your parent may qualify for certain benefits (like Medicare or Social Security if they worked enough, etc.) after some time, but note that using needs-based public assistance could invoke the I-864 obligations on you. They should consult before using any such benefits, though most federal benefits require 5 years of residency or citizenship. Importantly, after 5 years of being an LPR, your parent will be eligible to apply for U.S. citizenship (naturalization)uscis.gov, provided they meet the residence and physical presence requirements (generally 30 months in US out of those 5 years, and no single trip out >6 months without preservation). If your parent wants to become a citizen, mark the date – they can file the N-400 application 90 days before the 5-year anniversary of residency. Naturalization will remove the need to renew the green card and also frees you from the affidavit of support obligations (since they’ll no longer be a “sponsored immigrant” once a citizen).', checked: false },
        { id: 12.101, label: 'Identification: Your parent should consider getting a state ID or driver’s license now that they are an LPR, which will be useful for daily identification. The green card itself is also an ID but safer to keep at home except when needed.', checked: false },
        { id: 12.11, label: 'Integration: Help your parent get settled – such as adding them to a bank account, or getting them enrolled in health insurance (new LPRs can buy insurance and may qualify for certain programs). This goes beyond immigration, but it’s part of the journey.', checked: false }
    ]
}