const ParentCGlossary = {
  "Green Card Process": "The steps involved in becoming a lawful permanent resident of the United States.",
  "Lawful nonimmigrant": "Not a U.S. citizen and not a lawful permanent resident. People who enter the U.S. on a temporary basis—for tourism, business, work, or study.",
  "Permanent Resident Card": "Also known as a Green Card.",
  "Green card": "Another term for Permanent Resident Card.",
  "A-Number": "Alien Registration Number assigned to non-citizens by USCIS.",
  "IRS": "Internal Revenue Service, the U.S. government agency responsible for tax collection.",
  "Statutory period": "The legally required period (usually 3–5 years) of continuous residence in the U.S. for naturalization.",
  "Civics": "U.S. history and government knowledge required for the naturalization test.",
  "VAWA": "Violence Against Women Act, which allows certain noncitizens to apply for immigration relief without their abuser's knowledge.",
  "Form N-470": "Application to Preserve Residence for Naturalization Purposes.",
  "Form N-648": "Medical Certification for Disability Exceptions.",
  "N-400": "Application for Naturalization.",
  "Form G-1450": "Authorization for Credit Card Transaction.",
  "Form I-90": "Application to Replace Permanent Resident Card.",
  "Form G-28": "Notice of Entry of Appearance as Attorney or Representative.",
  "Form FS-240": "Report of Birth Abroad of a Citizen of the United States of America.",
  "Form N-426": "Request for Certification of Military or Naval Service.",
  "DD Form 214": "Certificate of Release or Discharge from Active Duty.",
  "NGB Form 22": "National Guard Report of Separation and Record of Service.",
  "Form I-912": "Request for Fee Waiver.",
  "Form I-797C": "Notice of Action. Often used for appointment notices or receipt confirmations.",
  "Form N-14": "Request for Additional Information, Documents, or Forms.",
  "Form N-336": "Request for a Hearing on a Decision in Naturalization Proceedings.",
  "Form N-445": "Notice of Naturalization Oath Ceremony.",
  "Immediate Relative": "Spouse, unmarried child (< 21), or parent of a U.S. citizen; always visa-current.",
  "Petitioner": "U.S. citizen or resident who files the family-based petition.",
  "Sponsor": "Same as Petitioner.",
  "Beneficiary": "Relative being sponsored for the green card.",
  "Applicant": "Same as Beneficiary at the visa stage.",
  "Petition": "Form I-130 request establishing the qualifying family relationship.",
  "USCIS": "Agency that decides immigration petitions and green-card applications.",
  "Certified Copy": "Government-issued duplicate carrying the same legal force as the original.",
  "Certified Translation": "Translator-signed English version attesting to complete and accurate translation.",
  "I-130": "Petition for Alien Relative",
  "Form I-130A": "Supplemental Information for Spouse Beneficiary",
  "Form I-485": "Application to Register Permanent Residence or Adjust Status",
  "Form G-1145": "E-Notification of Application/Petition Acceptance",
  "Form I-797C": "Notice of Action. It is often an appointment notice or a receipt.",
  "Form I-797": "Notice of Action. Receipt or Approval of an Application or Petition.",
  "Form I-290B": "Notice of Appeal or Motion",
  "Form AR-11": "Alien’s Change of Address Card",
  "Form DS-261": "Choice of Address and Agent",
  "Form I-944": "Declaration of Self-Sufficiency",
  "Form I-765": "Application for Employment Authorization",
  "Form I-131": "Application for Travel Documents, Parole Documents, and Arrival/Departure Records",
  "Form I-693": "Report of Immigration Medical Examination and Vaccination Record",
  "Form DS-260": "Immigrant Visa Electronic Application",
  "Form I-864": "Affidavit of Support",
  "Form I-864A": "Contract Between Sponsor and Household Member. To promise to make your income and/or assets available to help support a sponsored immigrant.",
  "Form I-824": "Application for Action on an Approved Application or Petition",
  "Form I-601": "Application for Waiver of Grounds of Inadmissibility",
  "Form I-90": "Application to Replace Permanent Resident Card",
  "Form I-551": "Permanent Resident Card, also known as the Green Card",
  "IRS Form 1040": "US Individual Income Tax Return",
  "Adjustment of Status": "Applying for the green card inside the United States with Form I-485.",
  "AOS": "Same as Adjustment of Status.",
  "Consular Processing": "Completing the immigrant-visa process at a U.S. embassy abroad.",
  "Concurrent Filing": "Filing I-130 and I-485 together for immediate relatives.",
  "Request for Evidence": "USCIS letter asking for additional documents by a deadline.",
  "Notice of Action": "USCIS receipt or approval notice containing the case number.",
  "Service Center": "Specific USCIS facility processing the petition.",
  "Priority Date": "Filing date that fixes a case’s place in line for quota categories.",
  "NVC": "State-Department center that collects fees, documents, and schedules consular interviews.",
  "Consular Electronic Application Center": "Online portal to pay NVC fees and submit forms.",
  "CEAC": "Same as Consular Electronic Application Center.",
  "CEAC Confirmation Page": "Barcode receipt proving a CEAC form was submitted.",
  "Invoice ID Number": "Code from NVC used with the case number to log into CEAC.",
  "Documentarily Qualified": "NVC has accepted all forms and documents; case awaits interview.",
  "DQ": "Same as Documentarily Qualified.",
  "Checklist": "NVC notice listing deficiencies that must be corrected.",
  "Principal Applicant": "Main person applying for the immigrant visa.",
  "Derivative Applicant": "Family member immigrating on the same petition.",
  "Household Size": "People counted on Form I-864 to determine required income.",
  "Federal Poverty Guidelines": "HHS income chart testing the sponsor’s 125% requirement.",
  "Joint Sponsor": "Extra sponsor who meets income rules when the primary sponsor does not.",
  "Public Charge": "Person likely to depend on certain means-tested benefits.",
  "Sponsor’s Obligation Period": "Time the sponsor remains financially liable under Form I-864.",
  "Civil Documents": "Official records (birth, marriage, police, court, etc.) supporting the case.",
  "Reciprocity Schedule": "Country-by-country guide to acceptable civil documents.",
  "Certified Copy vs. Original": "Either an original or government-certified duplicate is acceptable.",
  "Civil Surgeon": "U.S. doctor authorized to perform the AOS medical exam.",
  "Panel Physician": "Overseas doctor authorized to perform the immigrant-visa medical exam.",
  "Class A Condition": "Medical issue that renders an applicant inadmissible until resolved.",
  "Class B Condition": "Significant medical issue recorded but not inadmissible.",
  "Sealed Medical Envelope": "Tamper-evident packet containing medical exam results.",
  "Technical Instructions": "CDC guidelines doctors follow during immigration exams.",
  "Vaccination Requirements": "CDC-mandated shots that must be current for immigration.",
  "IMBRA Pamphlet": "Rights-and-resources sheet given to immigrant spouses and fiancés.",
  "Interview Appointment Letter": "Notice giving the date, time, and place of the visa or AOS interview.",
  "Adjustment Interview": "In-person USCIS interview to decide Form I-485.",
  "Consular Officer": "State-Department official who interviews and decides visa cases.",
  "221(g)": "Temporary refusal pending documents or administrative checks.",
  "Administrative Processing": "Additional security or background review after the interview.",
  "Visa Issuance": "Printing and placing the immigrant visa in the passport.",
  "Visa Packet": "Sealed or electronic file that accompanies an immigrant visa for CBP.",
  "Visa Availability": "Whether an immigrant-visa number is open; always yes for IR-5 parents.",
  "Visa Number": "Immigrant-visa slot made available by law.",
  "Green Card Stamp": "Passport stamp serving as temporary proof of permanent residence.",
  "I-551 Stamp": "Same as Green Card Stamp.",
  "Welcome Notice": "USCIS letter confirming approval of permanent residence.",
  "Immigrant Visa": "Visa that, once used to enter the U.S., confers permanent-resident status.",
  "IV": "Same as Immigrant Visa.",
  "USCIS Immigrant Fee": "$220 payment for producing and mailing the green card.",
  "Immigrant Visa Fee": "State-Department charge to print the visa.",
  "Notice of Intent to Deny": "USCIS letter warning of a forthcoming denial unless issues are rebutted.",
  "NOID": "Same as Notice of Intent to Deny.",
  "Board of Immigration Appeals": "Administrative court that hears appeals of USCIS denials.",
  "BIA": "Same as Board of Immigration Appeals.",
  "Port of Entry": "Airport or border crossing where CBP admits the immigrant.",
  "CBP": "Agency that inspects travelers and activates immigrant visas at entry.",
  "I-94": "Electronic Arrival/Departure Form for foreign visitors.",
  "I-94 Record": "Electronic arrival/departure record showing entry date and status.",
  "Re-entry Permit": "Travel document that preserves LPR status during long absences.",
  "Lawful Permanent Resident": "Person authorized to live and work in the U.S. indefinitely.",
  "LPR": "Same as Lawful Permanent Resident.",
  "Permanent Resident Card": "Physical \"green card\" proving LPR status.",
  "Green Card": "Same as Permanent Resident Card.",
  "Conditional Permanent Resident": "Green-card holder with two-year conditional status.",
  "CPR": "Same as Conditional Permanent Resident.",
  "Conditional Residence": "Two-year green-card status given to certain categories, not parents.",
  "Naturalization": "Process by which a permanent resident becomes a U.S. citizen.",
  "Continuous Residence": "Required span of U.S. residence before applying for citizenship.",
  "Good Moral Character": "Legal standard of behavior needed for naturalization approval.",
  "Selective Service": "Draft registration required of male permanent residents ages 18-25.",
  "AR-11": "Online form for reporting a new address to USCIS.",
  "Identification": "State ID or driver’s license obtained after becoming an LPR.",
  "Integration": "Practical steps to settle into U.S. life (banking, insurance, etc.).",
  "Admissibility": "Absence of statutory bars to entry.",
  "Eligibility": "Meeting category rules."
};

export default ParentCGlossary;