import Link from '@mui/material/Link';

export const paSteps = [
    { id: 1, label: 'Step 1: Confirm Eligibility and Relationship' },
    { id: 2, label: 'Step 2: Gather Required Documents for the Petition' },
    { id: 3, label: 'Step 3: File Form I-130 Petition and Receive Approval' },
    { id: 4, label: 'Step 4: Begin NVC Processing' },
    { id: 5, label: 'Step 5: Pay Required Fees' },
    { id: 6, label: 'Step 6: Submit Visa Application (DS-260)' },
    { id: 7, label: 'Step 7: Complete Affidavit of Support (Form I-864) & Financial Documents' },
    { id: 8, label: 'Step 8: Collect and Submit Civil Documents' },
    { id: 9, label: 'Step 9: Complete the Medical Examination' },
    { id: 10, label: 'Step 10: Prepare for the Interview' },
    { id: 11, label: 'Step 11: Attend the Interview and Receive Decision' },
    { id: 12, label: 'Step 12: U.S. Entry and Post-Arrival Next Steps' }
]

export const paChecklist = {
    1: [
        { section: 'Eligibility Checklist' },
        { id: 1.1, label: 'Verify Sponsor’s Status/Age:', checked: false },
        { id: 1.2, label: 'Confirm the petitioner is a U.S. citizen', checked: false, nested: true },
        { id: 1.3, label: 'At least 21 years old', checked: false, nested: true },
        { id: 1.4, label: 'Lawful permanent residents cannot sponsor a parent', checked: false, nested: true },
        { id: 1.5, label: 'Confirm Relationship: Ensure the person you plan to sponsor is legally your parent (biological mother or father, adoptive parent, or step-parent) as recognized by U.S. immigration law', checked: false },
        { id: 1.6, label: 'If sponsoring a step-parent: The marriage between your natural parent and step-parent must have occurred before your 18th birthday', checked: false, nested: true },
        { id: 1.7, label: 'If sponsoring an adoptive parent: The adoption must have been finalized before your 16th birthday', checked: false, nested: true },
        { id: 1.8, label: 'Check Parent’s Location: Note whether:', checked: false },
        { id: 1.9, label: 'Your parent is in the U.S. and must apply for Adjustment of Status (AOS) or', checked: false },
        { id: 1.10, label: 'Your parent is abroad and will require consular processing', checked: false },
        { id: 1.11, label: 'Parent is not inadmissible for a reason that cannot be resolved (e.g. serious criminal or immigration violations). (Minor inadmissibility issues can often be addressed with waivers later, but consider consulting an immigration attorney if any potential issues.)', checked: false },
        { id: 1.12, label: 'Review Visa Category: Recognize that parents of U.S. citizens qualify as immediate relatives (IR-5), which means visas are immediately available – there is no annual cap or waitlist for visa numbers', checked: false },
        { section: 'Required Documents' },
        { id: 1.13, label: 'Proof of U.S. Citizenship (Sponsor), one of the following:', checked: false },
        { id: 1.14, label: 'U.S. birth certificate', checked: false, nested: true },
        { id: 1.15, label: 'U.S. passport', checked: false, nested: true },
        { id: 1.16, label: 'Certificate of Naturalization/Citizenship', checked: false, nested: true },
        { id: 1.17, label: 'Proof of Parent-Child Relationship:', checked: false },
        { id: 1.18, label: 'Your birth certificate naming your parent. If sponsoring father, this certificate should show both parents’ names.', checked: false, nested: true },
        { id: 1.19, label: 'If sponsoring the father and your parents were ever married: their marriage certificate (to establish the legal paternal relationship).', checked: false, nested: true },
        { id: 1.20, label: 'If sponsoring a step-parent: your birth certificate (showing your birth parents) and the marriage certificate of your birth parent and step-parent (showing marriage before your 18th birthday). Include proof of termination of any prior marriages (divorce/death certificates) for your natural parent or step-parent.', checked: false, nested: true },
        { id: 1.21, label: 'If sponsoring an adoptive parent: adoption decree showing the adoption was finalized before you turned 16, and evidence of any prior custody if applicable.', checked: false, nested: true },
        { id: 1.22, label: 'Proof of Petitioner’s Age: Your birth certificate or passport (to show you are 21 or older).', checked: false },
        { id: 1.23, label: 'Name Change Documents (if applicable): Legal documents for any name changes for you or your parent (marriage certificate, court order, etc.).', checked: false }
    ],
    2: [
        { section: 'Task Checklist' },
        { id: 2.1, label: "Obtain Official Documents: Collect current, certified copies of all civil documents needed for the petition.", checked: false },
        { id: 2.2, label: "This includes those listed in Step 1 Ensure you have originals or certified copies on hand; you will submit copies with the petition and later need originals for the interview.", checked: false, nested: true },
        { id: 2.3, label: "Translations: If any document (birth certificate, marriage certificate, etc.) is not in English (or the official language of the country where you’re applying), get a certified English translation", checked: false },
        { id: 2.4, label: "Photographs: Prepare passport-style photos if required.", checked: false },
        { id: 2.5, label: "USCIS requires two recent identical color passport photos of the parent for the adjustment of status application (submitted later with Form I-485), but for the I-130 petition, photos are not required. (Photos will also be needed for visa processing later in consular processing, per Department of State instructions.)", checked: false, nested: true },
        { id: 2.6, label: "Form I-130 Preparation: Download and read the latest instructions for Form I-130, Petition for Alien Relative. Familiarize yourself with each part of the form and the supporting evidence requirements. You can choose to file online through USCIS’s website or by mailing a paper form.", checked: false },
        { id: 2.7, label: "Fees: Be prepared to pay the I-130 filing fee (currently $535 for each parent petition). If filing online, have a credit/debit card or bank info ready; if by mail, you’ll typically pay by check or money order (follow USCIS payment instructions).", checked: false },
        { section: 'Required Documents' },
        { id: 2.8, label: "Form I-130 Petition (completed and signed by the petitioner)", checked: false },
        { id: 2.9, label: "Filing fee $535 (check, money order, or credit card payment authorization, as applicable).", checked: false },
        { id: 2.10, label: "Petitioner’s proof of U.S. citizenship: e.g., copy of U.S. passport, naturalization certificate, or U.S. birth certificate.", checked: false },
        { id: 2.11, label: "Beneficiary’s civil documents: copy of your parent’s birth certificate (and marriage certificate if petition is for father or step-parent as described in Step 1). If names have changed, include legal name change documents.", checked: false },
        { id: 2.12, label: "Evidence of relationship: your birth certificate naming your parent (and for father/step-parent cases, marriage certificates or legitimation proof as required). If you are petitioning your father and were born out of wedlock, include proof of legitimation or evidence of a bona fide parent-child relationship before age 21(such as correspondence, photos, financial support).", checked: false },
        { id: 2.13, label: "Two passport-style photos of the petitioner and beneficiary (if specifically required). (USCIS no longer requires photos for I-130 petitions for parents, but double-check form instructions. Photos will be needed later for visa or adjustment steps.)", checked: false },
        { id: 2.14, label: "Form G-1145 (optional): If filing by mail, you can attach Form G-1145 to request email/text notification when USCIS accepts your petition.", checked: false }
    ],
    3: [
        { section: 'Task Checklist' },
        { id: 3.1, label: "Submit the I-130 to USCIS: File the petition with USCIS either online via your USCIS account or by mailing the paper form to the address in the instructions (usually the Chicago Lockbox for family petitions)", checked: false },
        { id: 3.2, label: "Double-check that you signed the form and included all supporting documents and the correct fee.", checked: false, nested: true },
        { id: 3.3, label: "Online filing: Upload scanned copies of supporting documents and pay electronically.", checked: false, nested: true },
        { id: 3.4, label: "By mail: Assemble the application packet with all required copies and the check or money order for the fee. It’s good practice to use a trackable mailing service.", checked: false, nested: true },
        { id: 3.5, label: "USCIS Receipt Notice: Wait for a Form I-797C Notice of Action (receipt notice) from USCIS confirming they received your petition and assigning a case number.", checked: false },
        { id: 3.6, label: "If you filed online, you will get an electronic receipt immediately; if by mail, the paper receipt arrives in a few weeks. The receipt is proof that your case is in process.", checked: false, nested: true },
        { id: 3.7, label: "USCIS Processing: During this period, USCIS will review your petition.", checked: false },
        { id: 3.8, label: "They may send a Request for Evidence (RFE) if something is missing or unclear – if so, respond by the deadline with the requested info to avoid denial. You can check your case status online using the receipt number.", checked: false, nested: true },
        { id: 3.9, label: "Approval Notice: If USCIS approves the I-130, you (the petitioner) will get an approval notice by mail (Form I-797).", checked: false },
        { id: 3.10, label: "If your parent is outside the U.S., the approved petition will be forwarded to the National Visa Center (NVC) for the next steps. (NVC will contact you with a welcome letter – see Step 4.)", checked: false, nested: true },
        { section: 'Required Documents' },
        { id: 3.11, label: "USCIS Approval Notice: Keep the I-797 approval notice safe. You’ll need the receipt number and case details for NVC or for filing AOS.", checked: false },
        { id: 3.12, label: "NVC Welcome Letter (Consular cases): This will be sent via email or mail a few weeks after I-130 approval. It contains your NVC Case Number and Invoice ID, which you’ll use to log in to the Consular Electronic Application Center (CEAC) for further processing.", checked: false }
    ],
    4: [
        { section: 'Task Checklist' },
        { id: 4.1, label: "NVC Case Creation:", checked: false },
        { id: 4.2, label: "After I-130 approval, wait for the NVC Welcome Letter (sent via email or mail) indicating your case number and a link to start online processing", checked: false, nested: true },
        { id: 4.3, label: "Log in to CEAC:", checked: false },
        { id: 4.4, label: "Use the case number and Invoice ID from the welcome letter to log in to the Consular Electronic Application Center (CEAC) online.", checked: false, nested: true },
        { id: 4.5, label: "This is where you will manage the visa application process – paying fees, submitting the visa application (DS-260), and uploading documents.", checked: false, nested: true },
        { id: 4.6, label: "Choose Agent (if applicable):", checked: false },
        { id: 4.7, label: "In some cases, the first step in CEAC is to confirm who will be managing the case (often the petitioner or the applicant themselves).", checked: false, nested: true },
        { id: 4.8, label: "Many times the petitioner and applicant handle it without a formal “agent,” but follow the prompts on CEAC.", checked: false, nested: true },
        { id: 4.9, label: "Pay NVC Fees:", checked: false },
        { id: 4.10, label: "The NVC will require payment of two fees: the Immigrant Visa Application Processing Fee and the Affidavit of Support Fee. Together these total $445 in most cases ( $325 + $120, though amounts can change – refer to the fee information on CEAC).", checked: false, nested: true },
        { id: 4.11, label: "Pay these online through CEAC using a U.S. bank account (routing and account number). The system will prompt you to pay each fee one at a time.", checked: false, nested: true },
        { id: 4.12, label: "Await Fee Confirmation:", checked: false },
        { id: 4.13, label: "After paying, it takes about 10 days for NVC to process the fees. You cannot proceed to the next steps (filling out the DS-260) until the fees show as paid, so mark your calendar ~10 business days out to check CEAC again.", checked: false, nested: true },
        { id: 4.14, label: "Start DS-260 Application:", checked: false },
        { id: 4.15, label: "Once fees are cleared, the online DS-260 Immigrant Visa Application will unlock in CEAC.", checked: false, nested: true },
        { id: 4.16, label: "You can begin filling it out (details in Step 6). NVC will also prompt you to submit the Affidavit of Support and civil documents (Steps 7–8).", checked: false, nested: true },
        { id: 4.17, label: "Scheduling can take another few weeks to a few months depending on the consulate’s backlog.", checked: false },
        { section: 'Required Documents' },
        { id: 4.18, label: "NVC Welcome Letter: (with Case Number and Invoice ID).", checked: false },
        { id: 4.19, label: "Financial Sponsor Info: You’ll need your Social Security Number or Tax ID, and access to your recent financial documents when preparing the Affidavit of Support in Step 7.", checked: false },
        { id: 4.20, label: "[The specific documents to submit to NVC (affidavit, civil docs) will be covered in Steps 7–8.]", checked: false }
    ],
    5: [
        { section: 'Task Checklist' },
        { id: 5.1, label: "Immigrant Visa Fee: Pay the Immigrant Visa Application Processing Fee through the CEAC website. This covers the processing of your parent’s visa application by the consulate. (As of now this fee is $325, but always follow the amount shown in CEAC.)", checked: false },
        { id: 5.2, label: "Affidavit of Support Fee: Pay the separate Affidavit of Support (I-864) fee (about $120) through CEAC. Note: In a few rare cases, this fee might not be required (for example, if the applicant already has 40 quarters of work in the U.S.), but for a parent it almost always applies. CEAC will indicate if the fee is required.", checked: false },
        { id: 5.3, label: "Use U.S. Bank Account: Payments must be made from a U.S. checking or savings account via ACH transfer. Have your routing and account number ready. (If you don’t have a U.S. bank account, you may need to arrange payment through a friend/relative or another method – contact NVC if this is an issue.)", checked: false },
        { id: 5.4, label: "Pay One at a Time: CEAC will only allow one fee to be paid at once (first the affidavit fee, then the visa fee, or vice versa). Complete the first payment, then repeat for the second.", checked: false },
        { id: 5.5, label: "Confirmation: After payment, note the payment confirmation numbers or print the CEAC confirmation page for your records.", checked: false },
        { id: 5.6, label: "Wait for NVC to Process Fees: It typically takes up to 10 business days (about 2 weeks) for the bank payments to clear and for NVC to mark them as “PAID” in the system. Do not try to proceed to the DS-260 or document upload until the fees show as paid – the DS-260 will remain locked until then.", checked: false },
        { id: 5.7, label: "Email Notifications: You may get an email from NVC when each fee is processed. Alternatively, keep checking CEAC after a week. Once both fees are listed as PAID, you can move on to Step 6 (DS-260 application) and Step 7 (Affidavit of Support upload).", checked: false },
        { section: 'Required Documents/Information for Fee Payment' },
        { id: 5.8, label: "NVC Case Number and Invoice ID (from your welcome letter) – needed to log in and confirm you’re paying for the correct case.", checked: false },
        { id: 5.9, label: "U.S. Bank Routing Number and Account Number – for the account from which fees will be withdrawn.", checked: false },
        { id: 5.10, label: "Sufficient funds in the account to cover the fees (ensure the payment won’t bounce).", checked: false },
        { id: 5.11, label: "A printer or PDF saver (optional) to keep records of the payment confirmations.", checked: false },
        { id: 5.12, label: "(No physical documents need to be sent for fees – it’s all online. Just keep the receipts.)", checked: false }
    ],
    6: [
        { label: 'Now that your fees are paid (Step 5), the DS-260 Immigrant Visa Application becomes available in CEAC. This is the actual online form your parent (beneficiary) must submit to apply for the immigrant visa.', textOnly: true },
        { section: 'Task Checklist' },
        { label: "Complete Form DS-260 Online:", textOnly: true, },
        { id: 6.1, label: "Log in to CEAC and click on the “Start DS-260” (or “Immigrant Visa Application”) link for the applicant.", checked: false, nested: true },
        { id: 6.2, label: "This is a comprehensive form – it will ask for your parent’s personal information, address history, work/education history, and various security/background questions (similar to questions on other visa applications or the I-485).", checked: false, nested: true },
        { id: 6.3, label: "Tip: Have your parent’s passport and any prior travel/history documents handy. You’ll need details like passport number, dates of previous visits to the U.S., etc.", checked: false, nested: true },
        { id: 6.4, label: "Fill out all mandatory fields. If something doesn’t apply (e.g., middle name and they have none), use “N/A” as instructed.", checked: false, nested: true },
        { label: "Petitioner Info:", textOnly: true, },
        { id: 6.5, label: "The DS-260 will ask for the petitioner’s name and contact information (that’s you).", checked: false, nested: true },
        { id: 6.6, label: "It may also ask for your U.S. address where the parent will live and where the green card should be mailed.", checked: false, nested: true },
        { id: 6.7, label: "Provide the U.S. address (it can be your address) where your parent intends to reside.", checked: false, nested: true },
        { label: "Review and Sign:", textOnly: true, },
        { id: 6.8, label: "At the end, there’s a sign and submit section.", checked: false, nested: true },
        { id: 6.9, label: "Important: The applicant (your parent) is the one legally signing this form, even if you help fill it out.", checked: false, nested: true },
        { id: 6.10, label: "If you, the petitioner, are completing it on their behalf, make sure the answers are accurate to your parent’s knowledge.", checked: false, nested: true },
        { id: 6.11, label: "At submission, you’ll electronically sign with your parent’s case ID and passport info.", checked: false, nested: true },
        { label: "Print Confirmation:", textOnly: true, },
        { id: 6.12, label: "After submitting DS-260, a confirmation page will appear. Print this confirmation or save it as PDF.", checked: false, nested: true },
        { id: 6.13, label: "Your parent will need to bring the DS-260 confirmation page to the visa interview as proof of submission.", checked: false, nested: true },
        { label: "Troubleshooting:", textOnly: true, },
        { id: 6.14, label: "If you need to correct something after submitting, you must contact NVC to unlock the form – so double-check before you hit submit.", checked: false, nested: true },
        { id: 6.15, label: "Minor errors can be corrected at the interview if needed, but it’s best to be thorough now.", checked: false, nested: true },
        { label: "Notify NVC of Any Changes:", textOnly: true, },
        { id: 6.16, label: "If any key information changes after submission (for example, your parent’s address or phone number, or a new family member to add), let NVC know via the CEAC or public inquiry so they can update the case.", checked: false, nested: true },
        { id: 6.17, label: "Some changes can be made at the interview too, but notifying in advance is ideal.", checked: false, nested: true },
        { section: 'Required Information for DS-260' },
        { id: 6.18, label: "Passport details of the parent: passport number, date of issuance/expiration, issuing country.", checked: false },
        { id: 6.19, label: "Personal details: full name (including native script if applicable), other names used, date and place of birth, gender, marital status, etc.", checked: false },
        { id: 6.20, label: "Address history: last five addresses and how long lived there.", checked: false },
        { id: 6.21, label: "Work and education history: names and addresses of employers for last 10 years, schools attended, etc.", checked: false },
        { id: 6.22, label: "Children information: If your parent has other children (your siblings), their names and locations (even if not immigrating).", checked: false },
        { id: 6.23, label: "Previous U.S. travel info: dates of any visits to U.S., visa types, or past overstays if any.", checked: false },
        { id: 6.24, label: "Security and background questions: (These cover topics like health, criminal history, immigration violations, etc. – answer Yes/No accordingly and be prepared to explain any “Yes” answers with details.)", checked: false },
        { id: 6.25, label: "Petitioner’s info: your name, address, contact, and relationship (son or daughter).", checked: false },
        { id: 6.26, label: "Immigrant visa address: Address in the U.S. where your parent plans to live and where the green card should be mailed (often your address).", checked: false },
        { id: 6.27, label: "Social media: usernames for any social media platforms your parent has used in the last 5 years (a newer requirement on visa applications).", checked: false },
        { id: 6.28, label: "Contact info: email and phone for your parent. NVC/Embassy may use the email for communication.", checked: false }
    ],
    7: [
        { label: 'Purpose: The Affidavit of Support is a legally binding document to ensure your parent will not become a public charge. As the petitioner, you must submit this and demonstrate you have sufficient income or assets to support your parent at 125% of the federal poverty guidelines (income threshold depends on household size).', textOnly: true },
        { section: 'Task Checklist' },
        { id: 7.1, label: "You will submit the I-864 and financial evidence to NVC via CEAC.", checked: false },
        { id: 7.2, label: "Choose the Correct I-864 Form: Most petitioners use the standard Form I-864. If your income is very high relative to requirements, you may qualify to use the shorter I-864EZ (check its instructions). But typically, use I-864. Download it from USCIS.gov to ensure you have the latest version.", checked: false },
        { id: 7.3, label: "Fill Out Form I-864: Fill in your (sponsor’s) information: name, address, employment, and household size. List your parent as the intending immigrant. Be sure to include yourself, your parent, and any other dependents in household size as required by form instructions.", checked: false },
        { id: 7.4, label: "Income Information: Provide the sponsor’s total income as shown on the most recent federal tax return (Form 1040). They must certify you either filed taxes or were not required to file. They’ll answer questions on current employment and income. If the current income is above the required level for the household size, great. If it’s borderline or below, the sponsor might need a joint sponsor or to use assets (see below).", checked: false },
        { id: 7.5, label: "Attach Financial Evidence: You need to upload supporting documents:", checked: false },
        { id: 7.6, label: "Federal Tax Transcripts or Tax Returns: NVC usually requires the most recent tax year’s federal tax transcript or a copy of the return (with W-2s/1099s). You can get transcripts from the IRS website. Providing transcripts is often preferable. You may optionally include the last 3 years of tax returns if it strengthens your case, but only the most recent is required.", checked: false, nested: true },
        { id: 7.7, label: "Proof of Current Employment: e.g., an employment verification letter from your employer stating your position, salary, and job stability; or if self-employed, business license or self-authored statement. Recent pay stubs (last 3–6 months) are also good evidence to show ongoing income.", checked: false, nested: true },
        { id: 7.8, label: "Proof of Assets (if needed): If your income doesn’t meet the requirement, you can use assets (yours, your parent’s, or household members). Assets could be savings, stocks, property equity, etc. You’d need documentation of the assets’ value (bank statements, appraisals, etc.), and typically the assets must be worth 5 times the difference between your income and the requirement (3 times if sponsoring a spouse or child of a U.S. citizen – but for a parent it’s 5x) (INA 213A rules).", checked: false, nested: true },
        { id: 7.9, label: "Joint Sponsor (if needed): If you cannot meet the requirement alone, you can find a joint sponsor – another U.S. citizen or resident who meets the income requirements and is willing to also sponsor your parent. A joint sponsor submits their own I-864 and financial docs. They are equally responsible for supporting the immigrant, so this is a serious commitment. (Each joint sponsor covers one immigrant; since you’re sponsoring one parent, only one joint sponsor max would be allowed if needed.)", checked: false, nested: true },
        { id: 7.10, label: "Household Member Contribution: If a relative in your household wants to contribute their income, they can file form I-864A as a household member. This is less common for parent cases but an option if, for example, your spouse or adult child living with you wants to add their income to meet the requirement.", checked: false, nested: true },
        { id: 7.11, label: "Domicile: You must affirm on the I-864 that your domicile is in the United States. If you live abroad, provide an explanation and evidence of how you still maintain U.S. domicile or will re-establish it by the time your parent immigrates. Examples: voting record, maintaining a U.S. residence, or a letter explaining you’re moving back to the U.S. for your parent’s relocation. Upload evidence if necessary (e.g., job offer in U.S., lease, etc.).", checked: false },
        { id: 7.12, label: "Upload to CEAC (Consular): Scan or PDF the signed I-864 and all supporting documents. Then log into CEAC, go to the “Affidavit of Support Documents” section. Upload the I-864 and each piece of evidence in the appropriate slots (CEAC will have categories like “Federal Income Tax Return,” “Proof of Employment,” etc.). Ensure scans are clear. After uploading, mark them as “Submitted”.", checked: false },
        { id: 7.13, label: "CEAC Tips: If you have a joint sponsor, there will be additional slots to upload their I-864 and documents as well. Be careful to upload under the correct sponsor’s name. If the petitioner and a joint sponsor are both sponsoring, you’ll submit two sets of documents.", checked: false },
        { id: 7.14, label: "Review and Submit: After uploading all required financial docs and civil docs (next step), you’ll formally submit the documents to NVC for review (CEAC usually has a “Submit Documents” button once everything is uploaded).", checked: false },
        { section: 'Required Documents (Financial):' },
        { id: 7.15, label: "Form I-864 (completed and signed)", checked: false },
        { id: 7.16, label: "Most recent Federal Tax Transcript (or copy of tax return + W2s)", checked: false },
        { id: 7.17, label: "Evidence of current employment/income: e.g., employment letter, recent pay stubs, or if self-employed, Schedule C/K-1, etc., to confirm current income.", checked: false },
        { id: 7.18, label: "Proof of assets (if using assets): bank statements for savings, property appraisals, etc., plus proof of ownership of those assets.", checked: false },
        { id: 7.19, label: "Joint Sponsor’s I-864 and documents (if you have a joint sponsor) – similar set of documents for them.", checked: false },
        { id: 7.20, label: "Household Member’s I-864A and documents (if using household member income).", checked: false },
        { id: 7.21, label: "Proof of U.S. domicile (if needed): evidence that you maintain a U.S. residence or intend to resume domicile (for sponsors living abroad)", checked: false },
        { id: 7.22, label: "Copy of sponsor’s U.S. passport or birth certificate: The embassy may want proof of the sponsor’s citizenship at the interview to verify the petitioner’s status and domicile. It’s good to have uploaded or have available a copy of your passport or certificate of naturalization as part of the supporting documents, although NVC doesn’t always explicitly ask for it in the upload list.)", checked: false }
    ],
    8: [
        { label: 'Purpose: These are the personal documents that prove your parent’s identity, family relationships, and any required background records. NVC requires scans of these documents, and the consulate will want to see originals at the interview.', textOnly: true },
        { section: 'Task Checklist' },
        { id: 8.1, label: 'Gather Required Civil Documents: Each immigrant must have certain documents. For a parent (IR-5) case, prepare:', checked: false },
        { id: 8.2, label: "Birth Certificate of the Parent (Beneficiary): Must be the full birth certificate from the official registry in the country of birth, showing the parent’s name, date of birth, and parents’ names. If only short form is available, see country-specific instructions. If unavailable, obtain a certificate of non-availability and other secondary evidence.", checked: false, nested: true },
        { id: 8.3, label: "Marriage Certificate: If your parent is or ever was married, obtain their marriage certificate(s). If widowed, a death certificate of spouse; if divorced, divorce decrees for all prior marriages. (Even if the prior spouse is not relevant to the petition, they need to show those marriages were legally terminated.)", checked: false, nested: true },
        { id: 8.4, label: "Police Certificates: Required for consular processing for every country where your parent lived for over 6 months since age 16 (and the current country of residence if different, and any country where arrested). These are clearances from law enforcement showing any criminal record. They must be obtained according to the State Department’s country guidelines (check the U.S. Embassy’s instructions via the reciprocity by country tool for how to get police certs).", checked: false, nested: true },
        { id: 8.5, label: "Court and Prison Records: If your parent has ever been convicted of a crime, certified copies of court records and any prison records are needed (for consular cases, and also wise to include in AOS). This includes even expunged cases or pardoned cases – they should bring records and certified English translations if applicable.", checked: false, nested: true },
        { id: 8.6, label: "Military Records: If your parent served in the military of any country, get a copy of their military record/discharge if available.", checked: false, nested: true },
        { id: 8.7, label: "Petitioner’s Birth Certificate: Because this is a parent case, your birth certificate (the petitioner’s) is crucial evidence of the relationship. Even though you submitted it for the I-130, the consulate expects to see the original at the interview. Upload a copy to NVC as well – NVC specifically lists “Petitioner’s birth certificate” for IR5 cases.", checked: false, nested: true },
        { id: 8.8, label: "Copy of Parent’s Passport biographic page: This is often requested to verify identity. Even if not explicitly listed, submit a clear copy of the passport photo page for your parent. The passport should be valid for at least 6 months beyond the intended entry date.", checked: false, nested: true },
        { id: 8.9, label: "Other Civil Docs: e.g., adoption papers (if parent is adoptive), name change documents, etc., if applicable to your parent’s situation. Basically, any document establishing identity or relationships that are pertinent.", checked: false, nested: true },
        { id: 8.10, label: "Translation of Documents: Ensure any document not in English (or not in the official language of the country of the consulate) has a certified English translation. Commonly, birth, marriage, police certs etc., if issued in another language, must be translated. Upload the translation together with the document.", checked: false },
        { id: 8.11, label: "Upload to CEAC: For consular cases, scan each document and upload it in CEAC under the appropriate category (e.g., “Birth Certificate – Applicant”, “Marriage Certificate”, “Police Certificate”). Use PDF format if possible and make sure scans are legible and include any stamps/seals. If a document has multiple pages, scan all pages into one file. For translations, you can either combine the translation with the original into one file or use the separate upload slot if provided.", checked: false },
        { id: 8.12, label: "Country-Specific Notes: Check the Reciprocity and Civil Documents page for each country for special requirements (e.g., some countries have multiple types of birth extracts, or specific police departments to request from). CEAC’s Document Finder link (or travel.state.gov) will have instructions per country – follow those to avoid an NVC checklist.", checked: false },
        { id: 8.13, label: "After Upload – Submit Documents: Once all required civil documents and the affidavit support docs (from Step 7) are uploaded, go ahead and submit them for NVC review (CEAC should show a “Submit” button when all mandatory items are uploaded). NVC will then review the entire package.", checked: false },
        { id: 8.14, label: "Document Keeping: Keep the physical originals of all civil documents in a safe place. Your parent will need to bring originals or certified copies of each of these to the visa interview. For AOS, your parent should bring originals to the USCIS interview as well (especially birth certificates, marriage/divorce certs).", checked: false },
        { section: 'Required Documents' },
        { id: 8.15, label: "Birth Certificate (long form) – plus translation if not in English", checked: false },
        { id: 8.16, label: "Marriage Certificate(s) – for any marriage your parent has had, current or prior (and spouse’s death certificate or divorce decree for each marriage that ended)", checked: false },
        { id: 8.17, label: "Police Certificate(s) – from each required country (see above), with translation if needed.", checked: false },
        { id: 8.18, label: "Court/Criminal Records – if applicable (any convictions, police reports if available, etc.).", checked: false },
        { id: 8.19, label: "Military Record – if applicable", checked: false },
        { id: 8.20, label: "Petitioner’s Birth Certificate (your birth certificate, to prove relationship)", checked: false },
        { id: 8.21, label: "Copy of parent’s Passport (biographical page) – ensure passport will be valid for 6+ months beyond the interview.", checked: false },
        { id: 8.22, label: "Any other relevant civil docs – e.g., adoption decree (if parent is adoptive), legal name change documents, etc.", checked: false },
        { id: 8.23, label: "Certified Translations for any above not in English", checked: false },
        { id: 8.24, label: "Original documents ready – you don’t send originals to NVC, but have them organized to bring to the interview.", checked: false }
    ],
    9: [
        { label: 'Before the final interview, your parent must undergo a medical exam by an authorized physician to ensure they have required vaccinations and no inadmissible health conditions.', textOnly: true },
        { label: 'The exam must be done by a Panel Physician approved by the U.S. Embassy/Consulate, after you get the interview appointment letter (some embassies allow it slightly earlier). The exam results will be sent directly to the consulate or given to your parent in a sealed packet to bring to the interview.', textOnly: true },
        { section: 'Task Checklist' },
        { label: 'Schedule the Exam:', textOnly: true },
        { id: 9.1, label: "Once you receive the interview appointment notice from NVC/consulate (with the interview date), immediately check the consulate’s instructions for medical exams.", checked: false, nested: true },
        { id: 9.2, label: "They will list specific panel physicians (often a list on the embassy’s website). Call and schedule the exam as soon as possible before the interview – ideally 5–7 days prior to ensure results are ready.", checked: false, nested: true },
        { id: 9.3, label: "Some clinics require the appointment letter to schedule; others can be scheduled with case number.", checked: false, nested: true },
        { label: 'Prepare Required Items for Exam: Typically, your parent should bring:', textOnly: true },
        { id: 9.4, label: "passport (or photo ID),", checked: false, nested: true },
        { id: 9.5, label: "appointment letter", checked: false, nested: true },
        { id: 9.6, label: "vaccination records", checked: false, nested: true },
        { id: 9.7, label: "any prior medical records of significance (like chest X-ray or TB treatment records if applicable).", checked: false, nested: true },
        { id: 9.8, label: "Fees for the exam vary and are usually paid by the applicant.", checked: false, nested: true },
        { label: 'Undergo the Examination: The doctor will review medical history, administer needed vaccinations, do a physical exam, and conduct required tests (blood tests, possibly chest X-ray for TB, etc.).', textOnly: true },
        { id: 9.9, label: 'Vaccinations: Required immunizations include those for measles, mumps, rubella, polio, tetanus, varicella, influenza, COVID-19 (as of early 2023; note: as of 2025 COVID vaccine is no longer required per updated CDC guidelines), and others as per CDC technical instructions. The doctor will assess and give any missing vaccines.', checked: false, nested: true },
        { id: 9.10, label: 'Communicable diseases: The exam includes tests for tuberculosis (TB blood test or skin test, and chest X-ray if needed) and syphilis (blood test), etc. If TB test is positive, a chest X-ray will confirm if active TB – this can add time, so doing exam 1-2 weeks before interview is wise.', checked: false, nested: true },
        { label: 'Result Handling:', textOnly: true },
        { id: 9.11, label: "Depending on the country, the panel physician will either send the results electronically to the consulate or give your parent a sealed envelope to bring to the interview.", checked: false, nested: true },
        { id: 9.12, label: "If an envelope is given, do not open it. In some cases they also give a CD of the chest X-ray or a copy of the vaccination record – those can be carried but usually not needed for the officer, except the consulate might instruct to bring the X-ray disc for US arrival.", checked: false, nested: true },
        { label: 'Follow Any Special Instructions:', textOnly: true },
        { id: 9.12, label: 'If the doctor finds a health issue that requires follow-up (e.g., sputum testing for TB which takes 8 weeks, or needing additional vaccine doses), follow instructions carefully.', checked: false, nested: true },
        { id: 9.13, label: 'This could mean delaying the visa issuance until clearance is obtained. Minor issues like a cold won’t affect visa issuance, but certain conditions (active TB, untreated syphilis, drug addiction, etc.) can delay or make one inadmissible until treated.', checked: false, nested: true },
        { label: 'Obtain Vaccination Record:', textOnly: true },
        { id: 9.14, label: 'The medical report will include a vaccination supplement listing which vaccines your parent has received or which are not medically appropriate. For consular cases, the panel physician’s report suffices.', checked: false, nested: true },
        { section: 'Required Documents/Items for Medical Exam:' },
        { id: 9.15, label: "Passport or government ID (panel physicians will require a passport for consular cases; civil surgeons need ID, preferably passport).", checked: false },
        { id: 9.16, label: "Appointment notice to prove eligibility for exam", checked: false },
        { id: 9.17, label: "Immunization records: any childhood or adult vaccine records to avoid re-vaccination.", checked: false },
        { id: 9.18, label: "Medical history list: medications, known health issues – to share with doctor honestly.", checked: false },
        { id: 9.19, label: "Cash/Credit for fee: payment as required by the clinic.", checked: false },
        { id: 9.20, label: "2-4 passport photos (some doctors require photos to attach to the forms, though digital photo is often taken). Check clinic instructions.", checked: false }
    ],
    10: [
        { label: 'Now your parents are nearing the finish line. Preparation is key for the interview.', textOnly: true },
        { section: 'Task Checklist' },
        { id: 10.1, label: "NVC will send an email when the interview is scheduled, containing the date, time, and location of the interview.", checked: false, nested: true },
        { id: 10.2, label: "The letter will often have instructions and a list of documents to bring. Print this letter – your parent will need it to enter the embassy.", checked: false, nested: true },
        { label: "Interview Appointment Letter:", textOnly: true, },
        { id: 10.3, label: "Some embassies require registering for a courier service or scheduling a passport pickup option before the interview. Others might require you to upload any remaining documents or bring extra photos.", checked: false, nested: true },
        { id: 10.4, label: "Read the embassy’s instructions carefully (usually provided on their website or in the appointment letter). For example, certain consulates want you to register on their visa appointment website for return document delivery.", checked: false, nested: true },
        { label: "Complete Pre-Interview Requirements:", textOnly: true, },
        { id: 10.5, label: "Your parent must bring the originals or certified copies of all civil documents submitted: birth certificates, marriage/divorce certs, police certificates, etc.", checked: false, nested: true },
        { label: "Gather Originals and Final Documents:", textOnly: true, },
        { id: 10.6, label: "Also bring the petitioner's original proof of citizenship (e.g., your original birth certificate or passport – some consulates specifically list “Petitioner’s original birth certificate” on the checklist).", checked: false, nested: true },
        { id: 10.7, label: "Bring the DS-260 confirmation page and NVC appointment letter. Two new passport-size photographs of your parent (per instructions, typically 2x2 inch) should be brought – even though photos were uploaded, consulates often ask for physical photos.", checked: false, nested: true },
        { label: "Medical Exam:", textOnly: true, },
        { id: 10.8, label: "Ensure the medical exam is completed as in Step 9, and your parent has the sealed medical envelope or confirmation that the panel doctor sent results to the consulate.", checked: false, nested: true },
        { label: "Financial Evidence:", textOnly: true, },
        { id: 10.9, label: "While NVC already reviewed the Affidavit of Support, your parent should bring a copy of the signed I-864 and any updated financial documents.", checked: false, nested: true },
        { id: 10.10, label: "The consular officer may ask about the petitioner’s ability to support. It’s not always requested if NVC qualified it, but carrying a set of the financials (tax returns, job letter, etc.) is wise in case.", checked: false, nested: true },
        { label: "Travel Arrangements:", textOnly: true, },
        { id: 10.11, label: "Do not make final travel bookings until the visa is actually issued.", checked: false, nested: true },
        { id: 10.12, label: "However, do have a general plan for travel since the visa, once issued, will have an expiration (often 6 months).", checked: false, nested: true },
        { id: 10.13, label: "Also, arrange how your parent will get to the consulate on interview day. Some consulates are strict about not allowing electronics, so your parent might need to leave phone at hotel or with someone. Check security rules of that consulate.", checked: false, nested: true },
        { label: "Accompanying the Parent:", textOnly: true, },
        { id: 10.14, label: "Most embassies do not allow the petitioner to attend the interview, because the petitioner is not the applicant (exception: if the applicant needs assistance due to age or disability, or if a minor child, a parent can accompany).", checked: false, nested: true },
        { id: 10.15, label: "As a son/daughter, you likely will not be allowed in unless the consulate explicitly permits it.", checked: false, nested: true },
        { id: 10.16, label: "Your parent should be prepared to interview alone. (However, they’ll have all your information and you’ve prepared them well!)", checked: false, nested: true },
        { id: 10.17, label: "If you live in the same country, you can go with them to the embassy and wait outside for moral support, but don’t expect to be in the room.", checked: false, nested: true },
        { label: "Practice Questions:", textOnly: true, },
        { id: 10.18, label: "Have your parent practice answering simple questions in English or their preferred language (the interview will usually be in the local language or English, depending on the consulate – many consular officers speak the local language).", checked: false, nested: true },
        { id: 10.19, label: "Typical questions for a parent’s immigrant visa: “Who is petitioning for you and what is their relationship to you?” “When did your son/daughter move to the U.S.?” “How often do you communicate or visit?” and verifying the information in the application (like “Have you ever been to the U.S.?” or “Do you have any other children?” etc.).", checked: false, nested: true },
        { id: 10.20, label: "The officer may also ask about the petitioner’s job or where they live in the U.S., to gauge that the parent has thought about their move. These are usually straightforward.", checked: false, nested: true },
        { label: "Attend any Pre-interview Checks:", textOnly: true, },
        { id: 10.21, label: "Some consulates require a finger-printing or document-check station before the actual interview (often on the same day).", checked: false, nested: true },
        { id: 10.22, label: "Your parent will likely have fingerprints taken at the embassy before or during the interview. Ensure fingers are clean and any cuts healed to avoid issues.", checked: false, nested: true },
        { label: "Arrival at Consulate:", textOnly: true, },
        { id: 10.23, label: "On interview day, arrive early (but not too early – some embassies only allow entry 15-30 min before appointment).", checked: false, nested: true },
        { id: 10.24, label: "Dress appropriately (business casual). Bring only allowed items (usually no phones, USBs, large bags). Go through security and follow instructions to the visa unit.", checked: false, nested: true },
        { label: "Honesty:", textOnly: true, },
        { id: 10.25, label: 'If the officer asks a question and your parent doesn’t know or is unsure, it’s okay to say “I don’t know” or ask for clarification.', checked: false, nested: true },
        { id: 10.26, label: 'Do not guess or lie. If needed, you as petitioner can respectfully clarify answers if your parent is confused (especially if there’s a language issue).', checked: false, nested: true },
        { section: 'Required Items at Interview:' },
        { id: 10.27, label: "Interview Notice / Appointment Letter (entry ticket to interview).", checked: false },
        { id: 10.28, label: "Passport (valid, plus any old passports if they contain U.S. visas or travel history – consular might ask for them).", checked: false },
        { id: 10.29, label: "Original civil documents: Birth, marriage, divorce, police certs, etc. (and translations).", checked: false },
        { id: 10.30, label: "Petitioner’s proof of citizenship: e.g., original U.S. birth cert or naturalization certificate of the child (for consular interview). For AOS, the officer might ask to see petitioner’s ID or citizenship proof as well, so have it if attending.", checked: false },
        { id: 10.31, label: "Medical exam results: Sealed I-693 for AOS if not submitted; panel physician envelope for consular if given.", checked: false },
        { id: 10.32, label: "Photos: Typically two passport photos (consular always; AOS sometimes not needed unless RFE, but bring 2 in case).", checked: false },
        { id: 10.33, label: "Financial updates: Recent pay stubs, job letter, latest tax return (optional but smart to have in case).", checked: false },
        { id: 10.34, label: "Supporting evidence of relationship: In parent cases, usually the birth certificate suffices. Rarely, if there’s any adoption or unusual family situation, any custody or adoption papers, family photos, etc., could be useful – but usually not required.", checked: false },
        { id: 10.35, label: "Interpreter (if applicable): and their ID, if USCIS interview and non-English speaking.", checked: false },
        { id: 10.36, label: "Pen and notepad: sometimes useful to jot info or in case forms need to be filled at consulate (usually not, but good to have).", checked: false },
        { id: 10.37, label: "Any other correspondence: For consular, print the CEAC confirmation for DS-260, and any NVC emails in case there’s confusion. For AOS, have your USCIS receipts handy.", checked: false }
    ],
    11: [
        { section: 'Task Checklist At Interview' },
        { id: 11.1, label: "Your parent will go through security and be directed to the immigrant visa unit. Typically, an initial clerk will collect required documents (passport, photos, originals of civil docs) and take fingerprints. Then your parent waits to be called by the consular officer.", checked: false },
        { id: 11.2, label: "The consular officer will have the whole file (including the I-130 petition, DS-260, medical report, etc.). The officer will place your parent under oath. They may start with casual questions (“How are you today?”) and then get into the specifics: verifying identity (name, DOB) and relationship (“So your son/daughter is petitioning you. They are a U.S. citizen?”). They might ask how the petitioner became a U.S. citizen (by birth or naturalization) to confirm petitioner’s status. They could ask the petitioner’s birth date or other biographical details to check consistency.", checked: false },
        { id: 11.3, label: "The officer will likely review the Affidavit of Support and might ask: “Who will you live with in the U.S.?” or “What does your son do for work? His affidavit shows $XX income, that meets the requirement.” If any concerns, they might ask if your parent understands that the petitioner will support them.", checked: false },
        { id: 11.4, label: "They will also review the medical results and ensure no inadmissibility issues. If something minor is missing (say a vaccine, the officer might just inform your parent to get it done in the U.S., or if the medical clearance is pending, they’ll hold the case).", checked: false },
        { id: 11.5, label: "If all is good, the officer will say something like, “Your visa is approved.” They will take your parent’s passport to place the visa. They usually give a paper with instructions on how the passport/visa will be returned (either a courier tracking info or pickup ticket). They might also hand out a “Welcome to the U.S.” flyer about paying the USCIS Immigrant Fee and important info for new immigrants. In some cases, they might return originals at this time. If any original is not returned, your parent can ask, but typically they hand everything back except the passport.", checked: false },
        { id: 11.6, label: "If the officer cannot approve the visa, they will explain why. Common outcomes: 221(g) administrative processing (they’ll give a letter, possibly asking for more documents or just stating it’s in AP). Or denial (very rare for a parent unless something like a serious inadmissibility that can’t be resolved came up). If denied, they’ll give reasons and whether a waiver is possible.", checked: false },
        { id: 11.7, label: "After Interview: For approved cases, the passport with the immigrant visa is usually ready within about a week (sometimes just 2-3 days). The visa will be a foil in the passport, and maybe a sealed packet or a note that the packet is electronic (since many consulates now send data electronically to CBP). The visa typically has an expiration date (usually 6 months from medical exam date or passport expiry, whichever earlier). Your parent must enter the U.S. before that visa expires (Step 12 covers arrival). If administrative processing, your parent must wait until the consulate contacts them for next steps or completion.", checked: false },
        { section: 'Post-Interview Outcome:' },
        { label: "If Approved: Congratulations! The visa is granted. You’ll proceed to Step 12 for entering the U.S.", textOnly: true, },
        { label: "If Pending/221(g): Address whatever is needed as quickly as possible. If it’s just administrative processing with no action required from you, then monitor the status online. Keep your parent’s petitioner contact info updated in case consulate needs to reach out.", textOnly: true, },
        { label: "If Denied: In parent cases, denials are uncommon unless there’s a major issue (like ineligibility or misrepresentation). If it happens, the letter will explain if there’s an appeal or waiver.", textOnly: true, }
    ],
    12: [
        { section: 'Task Checklist' },
        { id: 12.1, label: 'Pre-Travel: Once your parent has the passport with the IR-5 immigrant visa, double-check the information on the visa for accuracy (name, DOB, etc.). Note the expiration date – they must enter the U.S. before that date. Typically, the visa will be valid for 6 months from the medical exam date. Ensure your parent has paid or will pay the USCIS Immigrant Fee (mentioned earlier) to get their green card mailed. It’s best to pay it online before travel.', checked: false },
        { id: 12.2, label: 'Travel to U.S.: Your parent will travel with their passport (with the visa inside) and the sealed packet if one was given (often nowadays no physical packet, but if they have one do not open it). They should carry these in carry-on (not in checked luggage). If they have a chest X-ray CD from the medical, put that in carry-on too (usually not needed, but just in case CBP asks).', checked: false },
        { id: 12.3, label: 'Primary Inspection (Port of Entry): At the U.S. airport or land border, go in the line for Visitors/All Passports (not US citizen line). When meeting the Customs and Border Protection (CBP) officer, your parent will present the passport with the visa. If there’s a sealed envelope, hand it over as well. The officer will likely escort your parent to a secondary area for immigrant processing. This is routine for first-time immigrants.', checked: false },
        { id: 12.4, label: 'CBP Processing: In secondary, a CBP officer will open the sealed packet (or retrieve electronic documents) and finalize the entry. They will stamp the passport with an I-551 stamp (temporary proof of permanent residence). The stamp usually notes “IV admitted (ARC) until” one year later. This stamp plus the visa serves as proof of Green Card for up to a year, useful in case the physical card is delayed. CBP will take fingerprints and a photograph if not already taken. The officer might ask a couple of questions (to verify identity, or address where your parent will reside). This process typically takes some minutes.', checked: false },
        { id: 12.5, label: 'Welcome to America: The officer will return the passport (now with entry stamp) and say “Welcome to the United States” – at that moment, your parent is officially a U.S. Lawful Permanent Resident (LPR)! They can now proceed to baggage claim / exit. Make sure they don’t forget any documents.', checked: false },
        { id: 12.6, label: 'SSN (Social Security Number): If your parent opted on the DS-260 to have the SSA issue a Social Security number/card, the SSA will be notified after entry and the card should arrive at the U.S. address in a few weeks. If for some reason they did not opt in, or a month passes without an SSN, they can visit a Social Security office with passport and visa to apply for one. Often, though, the process is automatic now if requested. (AOS applicants can request SSN on the I-485 form as well.)', checked: false },
        { id: 12.7, label: 'Green Card Delivery: The USCIS Immigrant Fee you paid will trigger USCIS to mail the physical Green Card to the U.S. address you provided (either on DS-260 or at the Port of Entry). It usually arrives within 2 to 3 months of entry, often sooner. If 90 days pass after entry and no card, follow up with USCIS. The card is mailed by USPS, so check that the mailing address is correct and secure.', checked: false },
        { id: 12.8, label: 'Note on Visa Activation: The immigrant visa in the passport is stamped and annotated by CBP – it acts as a temporary Green Card for one year from entry. If your parent needs to travel abroad or prove work authorization before the physical card arrives, that visa + stamp is the evidence.', checked: false },
        { id: 12.9, label: 'Green Card Details: The card is typically valid for 10 years (if your parent is granted unconditional permanent residence, which IR-5 is – not conditional). Check the expiration date on the card when it arrives. Note: If your parent had any conditional status (not in this case), there’d be a 2-year card with conditions to remove. For IR-5, it’s a 10-year card.', checked: false },
        { id: 12.10, label: 'Name/Info: If there’s any error on the card (spelling, DOB), you’ll need to file for a replacement (Form I-90) to correct it. Double-check the card upon receipt.', checked: false },
        { id: 12.11, label: 'Rights and Responsibilities: Your parent can now live and work in the U.S. permanently. They should carry proof of status (the actual green card) at all times (the law requires it). They can work for any employer (no EAD needed). They can travel outside the U.S., but should not stay abroad for prolonged periods without precautions (see below).', checked: false },
        { id: 12.12, label: 'Address Change Requirement: If your parent moves, they must file Form AR-11 (Alien’s Change of Address) with USCIS within 10 days of moving, for the rest of their time as an LPR. It’s an online simple form or mail. This is required by law to keep address updated.', checked: false },
        { id: 12.13, label: 'Re-Entry and Trips Abroad: If your parent will travel abroad, trips under 6 months are generally fine. Trips over 6 months may raise questions of abandonment when re-entering; trips over 1 year without a Re-entry Permit can automatically trigger loss of residency. So, if your parent plans to be outside the U.S. for a long time (more than 6 months), consult about getting a re-entry permit (Form I-131, applied from within the U.S. before travel) to preserve status. They should ideally make the U.S. their primary home now.', checked: false },
        { id: 12.14, label: 'Benefits and Naturalization: As an LPR, your parent may qualify for certain benefits (like Medicare or Social Security if they worked enough, etc.) after some time, but note that using needs-based public assistance could invoke the I-864 obligations on you. They should consult before using any such benefits, though most federal benefits require 5 years of residency or citizenship. Importantly, after 5 years of being an LPR, your parent will be eligible to apply for U.S. citizenship (naturalization), provided they meet the residence and physical presence requirements (generally 30 months in US out of those 5 years, and no single trip out >6 months without preservation). If your parent wants to become a citizen, mark the date – they can file the N-400 application 90 days before the 5-year anniversary of residency. Naturalization will remove the need to renew the green card and also frees you from the affidavit of support obligations (since they’ll no longer be a “sponsored immigrant” once a citizen).', checked: false },
        { id: 12.15, label: 'Identification: Your parent should consider getting a state ID or driver’s license now that they are an LPR, which will be useful for daily identification. The green card itself is also an ID but safer to keep at home except when needed.', checked: false },
        { id: 12.16, label: 'Integration: Help your parent get settled – such as adding them to a bank account, or getting them enrolled in health insurance (new LPRs can buy insurance and may qualify for certain programs). This goes beyond immigration, but it’s part of the journey.', checked: false }
    ]
}