import Link from '@mui/material/Link';

export const sSteps = [
    { id: 1, label: 'Step 1: Check Eligibility ' },
    { id: 2, label: 'Step 2: File the Form I-130 Immigrant Petition' },
    { id: 3, label: 'Step 3: Wait for USCIS Processing' },
    { id: 4, label: 'Step 4: Case Transfer to NVC (Consular) or Adjustment Filing (Domestic)' },
    { id: 5, label: 'Step 5: Submit Affidavit of Support (Form I-864) and Financial Evidence' },
    { id: 6, label: 'Step 6: Submit Visa Application (DS-260) and Civil Documents' },
    { id: 7, label: 'Step 7: Case Complete – Interview Scheduling and Preparation' },
    { id: 8, label: 'Step 8: Complete the Medical Examination and Final Interview Prep' },
    { id: 9, label: 'Step 9: Attend the Interview' },
    { id: 10, label: 'Step 10: Post-Interview – Visa Issuance or Additional Actions' },
    { id: 11, label: 'Step 11: Travel to the United States – Port of Entry and Activation of Permanent Residence' },
    { id: 12, label: 'Step 12: Welcome to the USA – Receive Green Card and Conditional Residence Obligations' }
]

export const sChecklist = {
    1: [
        { section: 'Eligibility Criteria' },
        { label: 'Before filing the I-130, verify that both you and your spouse meet the eligibility criteria for this spousal petition.', textOnly: true },
        { label: 'Petitioner (Sponsor): ', textOnly: true },
        { id: 1.1, label: 'Must be a U.S. citizen or a lawful permanent resident', checked: false, nested: true },
        { id: 1.2, label: 'Should reside in the U.S. or plan to re-establish domicile in the U.S. by the time of the visa application', checked: false, nested: true },
        { id: 1.3, label: 'There is no minimum age to file the I-130, but the petitioner must be 18 or older to sign the Affidavit of Support later', checked: false, nested: true },
        { label: 'Beneficiary (Foreign Spouse):', textOnly: true },
        { id: 1.4, label: 'Must be legally married to the petitioner.', checked: false, nested: true },
        { id: 1.5, label: 'The marriage must be valid under the law of the place where it was performed,', checked: false, nested: true },
        { id: 1.6, label: 'Merely living together or being engaged is not sufficient for a spousal petition', checked: false, nested: true },
        { label: 'Legal Marriage:', textOnly: true },
        { id: 1.7, label: 'You and your spouse must have a legally valid marriage.', checked: false, nested: true },
        { id: 1.8, label: 'The marriage must be recognized in the country or state where it was performed.', checked: false, nested: true },
        { id: 1.9, label: 'Simply living together (common-law) generally does not qualify, unless it counts as a legal marriage in that jurisdiction.', checked: false, nested: true },
        { id: 1.101, label: 'Proxy marriages (where one or both parties were not physically present at the ceremony) are only valid for immigration if the marriage was later consummated (physically).', checked: false, nested: true },
        { id: 1.11, label: 'Only one spouse can be petitioned – polygamous marriages are not recognized, only the first marriage would be valid for immigration.', checked: false, nested: true },
        { id: 1.12, label: 'Same-sex marriages are recognized as long as the marriage is legally valid.', checked: false, nested: true },
        { label: 'Marital Status:', textOnly: true },
        { id: 1.13, label: 'Neither you nor your spouse can be currently married to anyone else.', checked: false, nested: true },
        { id: 1.14, label: 'Any prior marriages for either of you must have been legally terminated (by divorce, death, or annulment) before your current marriage.', checked: false, nested: true },
        { id: 1.15, label: 'You will need to show proof of termination for all prior marriages.', checked: false, nested: true },
        { label: 'Age Requirements:', textOnly: true },
        { id: 1.16, label: 'There is no minimum age to file an I-130 petition for a spouse.', checked: false, nested: true },
        { id: 1.17, label: 'However, note that to sign the required Affidavit of Support in a later step, the petitioner must be at least 18 and domiciled in the U.S.', checked: false, nested: true },
        { label: 'Petitioner’s Residence (Domicile):', textOnly: true },
        { id: 1.18, label: 'While you can file the I-130 petition even if you are temporarily abroad, you are generally expected to maintain a domicile (primary residence) in the United States by the time your spouse immigrates.', checked: false, nested: true },
        { label: 'Financial Ability (Affidavit of Support):', textOnly: true },
        { id: 1.19, label: 'The I-130 stage does not require proof of income or finances.', checked: false, nested: true },
        { id: 1.201, label: 'But be aware that in later steps you must demonstrate you meet income requirements to sponsor your spouse (by submitting Form I-864).', checked: false, nested: true },
        { id: 1.21, label: 'Ensure you either meet the income threshold or have a joint sponsor ready – this is not needed at I-130 filing, but is crucial for the visa/green card stage.', checked: false, nested: true },
        { label: 'Genuine Relationship:', textOnly: true },
        { id: 1.22, label: 'Your marriage should be in good faith, not solely for obtaining an immigration benefit.', checked: false, nested: true },
        { id: 1.23, label: 'USCIS will evaluate the bona fides of the marriage.', checked: false, nested: true },
        { id: 1.24, label: 'Petitions suspected to be fraudulent can be denied.', checked: false, nested: true },
        { id: 1.25, label: 'Be prepared to provide evidence of a real marriage (shared life) as described above.', checked: false, nested: true },
        { id: 1.26, label: 'Marriage fraud is a serious offense and can lead to denial and other penalties.', checked: false, nested: true },
        { section: 'Required Documents' },
        { label: 'When filing Form I-130 for a spouse, USCIS requires supporting documents to prove your eligibility and the family relationship. Prepare the following', textOnly: true },
        { id: 1.27, label: 'Proof of Petitioner’s U.S. Status: Documentation that you are a U.S. citizen (or LPR). ', checked: false },
        { label: 'Examples: a copy of your U.S. birth certificate, unexpired U.S. passport, Certificate of Naturalization, Certificate of Citizenship, or Consular Report of Birth Abroad. ', textOnly: true, nested: true },
        { label: 'If you are a lawful permanent resident, provide a copy of the front and back of your Green Card.', textOnly: true, nested: true },
        { id: 1.28, label: 'Marriage Certificate: A copy of your official marriage certificate showing the names of you and your spouse. This is proof of the legal marriage between petitioner and beneficiary. Ensure it is a civil marriage certificate from the appropriate government authority.', checked: false },
        { id: 1.29, label: 'Proof of Termination of Prior Marriages: If either you or your spouse were previously married, include copies of documents proving all prior marriages have ended. This can be divorce decrees, annulment orders, or death certificates, as applicable. (USCIS needs to confirm that both parties were free to marry each other.)', checked: false },
        { id: 1.301, label: 'Evidence of Bona Fide Marriage: It is strongly recommended to provide evidence that your marriage is genuine (even though this is not a formal requirement for initial filing, it can help avoid RFEs). Examples of bona fide marriage evidence include:', checked: false },
        { id: 1.31, label: 'Joint property deeds', checked: false, nested: true },
        { id: 1.32, label: 'Joint lease agreements', checked: false, nested: true },
        { id: 1.33, label: 'Joint bank account statements', checked: false, nested: true },
        { id: 1.34, label: 'Birth certificates of children you have together', checked: false, nested: true },
        { id: 1.35, label: 'Sworn affidavits from friends/family attesting to your relationship', checked: false, nested: true },
        { id: 1.36, label: 'Other documents showing you share a life (insurance, joint taxes, photos, etc.)', checked: false, nested: true },
        { id: 1.37, label: 'You do not need to send every possible item, but include a sample of solid evidence showing an ongoing marital union.', checked: false, nested: true },
        { id: 1.38, label: 'Passport Photos: Two passport-style photographs of you (petitioner) and two of your spouse (beneficiary) if your spouse is currently in the United States. Photos should be:', checked: false },
        { id: 1.39, label: '2x2 inches', checked: false, nested: true },
        { id: 1.401, label: 'Color', checked: false, nested: true },
        { id: 1.41, label: 'Taken within 30 days, with a white or off-white background.', checked: false, nested: true },
        { id: 1.42, label: '(Write names and A-numbers lightly on the back in pencil.)', checked: false, nested: true },
        { id: 1.43, label: 'If your spouse is abroad, you generally do not need to submit their photos with the I-130.', checked: false, nested: true },
        { id: 1.44, label: 'Proof of Legal Name Changes (if any): If either of you has changed your name (for example, after marriage or for any other reason), include legal evidence of the name change. This could be a marriage certificate (if the name change is shown there), court order, adoption decree, or other official documentation linking your old and new names.', checked: false },
        { id: 1.45, label: 'English Translations: For any document not in English, provide a complete English translation, certified by the translator as accurate. Include the translator’s certification letter with the translation.', checked: false },
        { id: 1.46, label: 'Copies, Not Originals: Unless explicitly required (rare), submit photocopies of documents, not original civil documents. You will later need originals for the visa interview or adjustment interview, but for now, USCIS usually only needs copies. (If USCIS ever needs to see an original, they will request it.)', checked: false },
        { label: 'Note: Always refer to the latest USCIS Form I-130 instructions for any specific document requirements or updates. USCIS may update requirements, so using the official instructions as a final check is wise.', textOnly: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://www.uscis.gov/i-130" target="_blank" rel="noopener">USCIS Form I-130 main page</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/sites/default/files/document/forms/i-130instr.pdf" target="_blank" rel="noopener">I-130 official instructions (PDF)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/family-immigration/immigrant-visa-for-a-spouse.html" target="_blank" rel="noopener">DOS IR-1 / CR-1 overview</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/forms/filing-guidance/tips-for-filing-forms-by-mail" target="_blank" rel="noopener">USCIS form-filing tips (mail)</Link>, textOnly: true, nested: false }
    ],
    2: [
        { section: 'Tasks' },
        { id: 2.1, label: 'Gather required supporting documents: Collect all required documents (see the Required Documents checklist below for details). This will include proof of your:', checked: false },
        { id: 2.2, label: 'U.S. citizenship status', checked: false, nested: true },
        { id: 2.3, label: 'Your marriage certificate', checked: false, nested: true },
        { id: 2.4, label: 'Other evidence noted by USCIS.', checked: false, nested: true },
        { id: 2.5, label: 'Ensure you have copies (and certified translations if not in English) of each document.', checked: false, nested: true },
        { id: 2.6, label: 'Prepare passport photos (if applicable): If your spouse is physically in the United States, include two recent passport-style color photos of each of you (petitioner and spouse), taken within 30 days of filing.', checked: false },
        { label: 'Photos are not required for a spouse living abroad at the I-130 stage.', textOnly: true, nested: true },
        { id: 2.7, label: 'Receive the USCIS receipt notice: After USCIS receives your petition, they will issue a Receipt Notice (Form I-797C, Notice of Action) by mail (or to your online account if filed electronically) typically within a few weeks. This notice confirms that your I-130 was accepted and gives you a receipt number to track your case. Keep this document safe.', checked: false },
        { id: 2.8, label: 'Respond to any USCIS requests: If USCIS needs more information, they will send a Request for Evidence (RFE). Respond promptly with the requested documents to avoid delays. (Carefully follow the instructions in any RFE letter.)', checked: false },
        { id: 2.9, label: 'Complete and sign Form I-130 (Petition for Alien Relative) with accurate information about you (the U.S. citizen petitioner) and your foreign spouse (the beneficiary).', checked: false },
        { id: 2.101, label: 'Double-check all names, dates, and answers to avoid delays.', checked: false, nested: true },
        { id: 2.11, label: 'Gather supporting evidence of your marriage and eligibility, including:', checked: false },
        { id: 2.12, label: 'A copy of your marriage certificate', checked: false, nested: true },
        { id: 2.13, label: 'Proof of your U.S. citizenship (birth certificate, passport, or naturalization certificate)', checked: false, nested: true },
        { id: 2.14, label: 'Documents showing any previous marriages were legally terminated.', checked: false, nested: true },
        { id: 2.15, label: 'It’s also helpful to prepare proof of a bona fide marriage (e.g. joint leases, photos, bank statements) to submit now or have ready for later stages.', checked: false, nested: true },
        { id: 2.16, label: 'Pay the required filing fee (check the current fee on USCIS’s website, as it can change).', checked: false },
        { label: 'As of 2025, the fee is around $535-$675, depending on online or paper filing.', textOnly: true, nested: true },
        { id: 2.17, label: 'Choose filing method: Decide how to submit your petition:', checked: false },
        { label: 'Online filing: Create a USCIS online account and submit Form I-130 (and upload scans of supporting documents) through the USCIS website. This is available for U.S. citizens filing for a spouse, and it includes a $50 fee discount', textOnly: true, nested: true },
        { label: 'Mail filing: Assemble a packet with the signed Form I-130, Form I-130A, supporting documents, photos, and payment. Mail it to the correct USCIS lockbox address. (The address depends on where you live and whether you are filing any other forms concurrently. Check the USCIS “Direct Filing Addresses for Form I-130” page for the current address.)', textOnly: true, nested: true },
        { label: '(If abroad:) U.S. citizens living outside the U.S. should generally file online or by mail. In rare cases, you may request to file directly at a U.S. Embassy or Consulate if you have an exceptional situation. Most petitioners abroad will still file through USCIS.', textOnly: true, nested: true },
        { id: 2.18, label: 'Double-check your packet: Before sending, review everything.', checked: false },
        { label: "Ensure all forms are signed and dated, the fee is correct, and required documents are included (copies, not originals, unless instructed).", textOnly: true, nested: true },
        { label: "Organize your packet per USCIS instructions (for example, you may attach a cover letter or checklist, though it’s optional).", textOnly: true, nested: true },
        { id: 2.19, label: 'Submit the I-130 petition to USCIS.', checked: false },
        { label: "Include all required forms (I-130 and, if required, the I-130A for the beneficiary spouse) and supporting documents per the instructions.", textOnly: true, nested: true },
        { label: "If filing by mail, send your packet via a trackable delivery service (USPS Priority Mail, FedEx, etc.) to the USCIS lockbox.", textOnly: true, nested: true },
        { label: "If filing online, follow the USCIS portal steps to submit. Once filed, you will receive a confirmation page or email.", textOnly: true, nested: true },
        { id: 2.201, label: '(AOS Only) Concurrent filing (if applicable): If your spouse is inside the U.S. and eligible to adjust status, you can file Form I-485 (green card application) at the same time as the I-130. Include all required AOS forms (I-485, I-864 Affidavit of Support, etc.) and fees in one package. (Concurrent filing is only for spouses in the U.S. pursuing Adjustment of Status – not for consular cases.)', checked: false },
        { id: 2.21, label: '(Consular Processing) Next steps after I-130: If your spouse is outside the U.S., you will first wait for the I-130 approval. Upon approval, USCIS will forward your petition to the National Visa Center (NVC) for visa processing. (You do not need to contact NVC until they send instructions. NVC processing will be covered in a later step.) For now, once the I-130 is filed, simply monitor its status and wait for a decision.', checked: false },
        { section: 'Required Documents' },
        { id: 2.22, label: 'Completed and signed Form I-130 (and Form I-130A if required for a spouse beneficiary).', checked: false },
        { id: 2.23, label: 'Proof of petitioner’s U.S. citizenship (copy of passport, birth certificate, or naturalization certificate).', checked: false },
        { id: 2.24, label: 'Marriage certificate (official copy).', checked: false },
        { id: 2.25, label: 'Proof of termination of any prior marriages for either spouse (divorce decrees, annulments, or death certificates, if applicable).', checked: false },
        { id: 2.26, label: '(If available) Evidence of a bona fide marriage (e.g. joint financial records, photos together, affidavits from family/friends) – optional but recommended to establish the marriage is genuine.', checked: false },
        { id: 2.27, label: 'Filing fee payment (check, money order, or credit card authorization if filing by mail; online payment if filing electronically).', checked: false },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-2-your-case-nvc.html" target="_blank" rel="noopener">Step 2: NVC Processing (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/i-485" target="_blank" rel="noopener">USCIS Form I-485 page</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/green-card/green-card-processes-and-procedures/concurrent-filing" target="_blank" rel="noopener">USCIS Concurrent-filing guidance</Link>, textOnly: true, nested: false },
        { label: <Link href="https://ceac.state.gov/CEACStatTracker/Status.aspx?App=IV" target="_blank" rel="noopener">CEAC IV status-checker</Link>, textOnly: true, nested: false }],
    3: [
        { section: 'Tasks' },
        { id: 3.1, label: 'Receive the Receipt Notice: After filing, USCIS will mail you a receipt notice (Form I-797C, Notice of Action) typically within a few weeks. This receipt includes a unique case number.', checked: false },
        { id: 3.2, label: 'Review the notice to ensure your name and address are correct.', checked: false },
        { id: 3.3, label: 'Track Your Case: Use the receipt number to check your case status on the USCIS online portal.', checked: false },
        { label: 'Initially, the status will be “Received.” You can also create/ log in to your USCIS account to see updates.', textOnly: true, nested: true },
        { id: 3.4, label: 'Respond to Any RFEs: If USCIS needs more evidence, they will send a Request for Evidence (RFE) by mail (and to your account if filed online).', checked: false },
        { label: 'The notice will list what additional documents or information are required.', textOnly: true, nested: true },
        { id: 3.5, label: 'Respond by the deadline with the requested evidence to avoid denial.', checked: false },
        { label: 'Common RFEs in spousal cases might ask for missing relationship evidence or clarify documents.', textOnly: true, nested: true },
        { id: 3.6, label: 'USCIS Background Process: While you wait, USCIS is verifying the information and conducting security checks.', checked: false },
        { label: 'Immediate relative petitions (IR category) are not subject to visa quotas, so they can be approved as soon as USCIS finishes processing.', nested: true, textOnly: true },
        { label: 'If everything is in order, USCIS will approve the I-130; if not, they may deny the petition (uncommon if all genuine) or issue additional requests.', nested: true, textOnly: true },
        { id: 3.7, label: 'Approval Notice: When a decision is made, USCIS will mail an approval notice (Form I-797).', checked: false },
        { label: 'If your spouse will do consular processing abroad, USCIS will automatically forward the approved petition to the National Visa Center (NVC) for the next phase.', nested: true, textOnly: true },
        { label: 'If your spouse is adjusting status in the U.S., the approved I-130 remains with USCIS to be paired with the I-485 process. In the rare case of a denial, the notice will explain the reasons and mention if an appeal is possible.', nested: true, textOnly: true },
        { section: 'Required Documents' },
        { id: 3.8, label: 'USCIS Receipt Notice (I-797C)', checked: false },
        { id: 3.9, label: 'Copy of the I-130 Petition', checked: false },
        { id: 3.101, label: 'Evidence for RFE (if expected)', checked: false },
        { label: ' If you anticipate USCIS might request more proof (e.g., bona fide marriage evidence), start gathering those documents (updated bank statements, more photos, letters from friends, etc.) so you can respond quickly if asked.', textOnly: true, nested: true },
        { id: 3.11, label: 'Address Change Confirmation', checked: false },
        { section: 'Estimated Time of Completion' },
        { label: 'This waiting step is largely dependent on USCIS’s workload. Receiving the I-130 approval can take several months to over a year (e.g. often around 9–15 months in recent times for U.S. citizen spouse petitions). The exact timeframe varies by USCIS service center and case complexity. There is little “to do” during this step except wait and periodically check status.', textOnly: true, },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-3-pay-fees.html" target="_blank" rel="noopener">Step 3: Pay Fees (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/nvc/immigrant-visas-processing-fees.html" target="_blank" rel="noopener">NVC fee-payment FAQ</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/forms/filing-fees" target="_blank" rel="noopener">USCIS fee-schedule</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/forms/uscis-fee-calculator" target="_blank" rel="noopener">USCIS online fee-calculator</Link>, textOnly: true, nested: false }
    ],
    4: [
        { section: 'Tasks' },
        { label: "Consular", textOnly: true },
        { id: 4.1, label: 'USCIS Approval & NVC Case Creation: If your I-130 has been approved and your spouse will be interviewing abroad, USCIS will send the petition to the National Visa Center (NVC).', checked: false },
        { label: 'You (the petitioner) will receive a notice when this happens.', textOnly: true, nested: true },
        { label: 'The NVC will assign a case number (typically starting with 3 letters for the embassy, e.g. DSP for Guangzhou, ABD for Abu Dhabi) and will email or mail a notice with instructions.', textOnly: true, nested: true },
        { label: 'The first task is often to log in to the State Department’s Consular Electronic Application Center (CEAC) using the case number and an invoice ID number provided.', textOnly: true, nested: true },
        { id: 4.2, label: 'Choose an Agent (DS-261) and Submit Fee: Through the CEAC portal, you may need to designate an “Agent” (the person who will receive correspondence, often the beneficiary or petitioner) by filing Form DS-261 (Choice of Address and Agent)', checked: false },
        { label: 'This is done online and in most cases is straightforward (if you have an attorney, this step is essentially skipped/handled by them).', textOnly: true, nested: true },
        { label: 'Next, pay the required NVC fees: the Immigrant Visa Application Processing Fee and the Affidavit of Support Fee.', textOnly: true, nested: true },
        { label: 'As of 2025, these total $445 ( $325 for the visa application (DS-260) and $120 for the affidavit support fee, subject to change).', textOnly: true, nested: true },
        { label: 'You will pay online in CEAC, and it can take a few days for payments to clear.', textOnly: true, nested: true },
        { id: 4.3, label: 'Maintain Communication: For consular cases, regularly check the email (including spam) that you provided to NVC. You will get messages when fees are invoiced, when they’re paid, and when further action is needed.', checked: false },
        { label: 'Adjusting of Status in U.S.', textOnly: true },
        { id: 4.4, label: 'File I-485 Package: If your spouse is in the U.S. and you did not already file a concurrent I-485, you should proceed with the Adjustment of Status (AOS) application now.', checked: false },
        { id: 4.5, label: 'File Form I-485 (plus accompanying forms like I-864 Affidavit of Support, I-944 if required in the current policy, I-765 for work permit, I-131 for travel permit). Immediate relatives don’t have to wait for visa availability, so you can file as soon as the I-130 is approved (or concurrently, as discussed earlier).', checked: false, nested: true },
        { id: 4.6, label: 'Include the required medical exam report (I-693) or be prepared to submit it later.', checked: false, nested: true },
        { id: 4.7, label: 'Pay the I-485 filing fee (currently $1,225 including biometrics for most adults).', checked: false, nested: true },
        { id: 4.8, label: 'After filing, USCIS will issue receipt notices and later schedule a biometrics appointment (fingerprinting) for the spouse at a local Application Support Center. (Note: If you already filed the I-485 concurrently, continue to Step 5, as the next steps will diverge from NVC process to the AOS process.)', checked: false, nested: true },
        { id: 4.9, label: 'Maintain Communication:  For AOS cases, keep an eye on your USCIS case status and mail for the biometric appointment notice.', checked: false },
        { section: 'Required Documents' },
        { id: 4.101, label: 'NVC Welcome Letter (case number and invoice ID) – needed to log into CEAC', checked: false },
        { id: 4.11, label: 'DS-261 (Agent Designation) – completed online (no separate physical document to send)', checked: false },
        { id: 4.12, label: 'Payment method for online fee payment (credit/debit card or bank info for ACH). Save the payment confirmation receipts from CEAC', checked: false },
        { id: 4.13, label: 'For AOS: Form I-485 and accompanying forms (I-864, I-944 if applicable, I-765, I-131) – completed and signed, ready to file with supporting documents (birth certificates, marriage certificate, etc., similar to NVC civil documents). I-485 filing fee (check or money order if by mail, or credit card form if applicable)', checked: false },
        { id: 4.14, label: 'Passport-style photos of the applicant (and petitioner for some forms like I-864) as required', checked: false },
        { id: 4.15, label: 'Medical Exam Form I-693 (if you have it ready, otherwise you will provide it later)', checked: false },
        { section: 'Eligibility Criteria' },
        { label: 'At this stage, immediate relatives (IR-1/CR-1) are eligible to proceed without waiting for a visa number (since visas are unlimited for this category).', textOnly: true },
        { label: 'NVC will not delay processing for quota reasons.', textOnly: true, nested: true },
        { label: 'However, if the petitioner was a green card holder who just became a U.S. citizen, make sure NVC knows to upgrade the case to IR-1 – this eliminates any wait line.', textOnly: true, nested: true },
        { label: 'Financial Eligibility: Starting now, especially for AOS (with the I-864) or soon at NVC, the petitioner must demonstrate meeting income requirements.', textOnly: true },
        { id: 4.16, label: 'Ensure you (the petitioner) are still domiciled in the U.S. (or will re-establish domicile)', checked: false, nested: true },
        { id: 4.17, label: 'Ensure you have income ≥125% of the federal poverty level for your household size, or have a joint sponsor or assets if not. (More on the Affidavit of Support in the next step.)', checked: false, nested: true },
        { label: 'For AOS Applicants: To file I-485, the spouse beneficiary must have entered the U.S. lawfully (inspection at entry) and not be barred from adjusting (certain visa overstays or violations are forgiven for immediate relatives, but if there was illegal entry, AOS is generally not possible without leaving and seeking a waiver).', textOnly: true },
        { id: 4.18, label: 'Have entered the U.S. lawfully (inspection at entry) and not be barred from adjusting certain visa overstays or violations are forgiven for immediate relatives', checked: false, nested: true },
        { id: 4.19, label: 'If there was illegal entry, AOS is generally not possible without leaving and seeking a waiver.', checked: false, nested: true },
        { id: 4.201, label: 'Also, the spouse should not have any serious criminal or immigration violation that makes them inadmissible.', checked: false, nested: true },
        { id: 4.21, label: 'Most spousal applicants are eligible, but it’s good to double-check eligibility for adjustment (e.g., if the spouse ever worked without authorization, it is forgiven for immediate relatives).', checked: false, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/affidavit-of-support.html" target="_blank" rel="noopener">Affidavit-of-Support hub (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/i-864" target="_blank" rel="noopener">USCIS Form I-864 page</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/sites/default/files/document/forms/i-864instr.pdf" target="_blank" rel="noopener">I-864 instructions (PDF)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/i-864p" target="_blank" rel="noopener">I-864P poverty-guidelines chart</Link>, textOnly: true, nested: false }
    ],
    5: [
        { section: 'Tasks' },
        { id: 5.1, label: 'Complete Form I-864 (Affidavit of Support): The petitioner (U.S. spouse) must fill out Form I-864, which is a legally binding sponsorship agreement.', checked: false },
        { label: 'This form demonstrates that the petitioner has sufficient financial means to support the spouse and prevent them from becoming a “public charge.”', textOnly: true, nested: true },
        { label: 'Fill in all sections accurately, including household size and income. If your income alone is insufficient, a joint sponsor or household member can complete a separate I-864 (or I-864A for a household member).', textOnly: true, nested: true },
        { id: 5.2, label: 'Gather Financial Documents: Collect the required evidence of income and assets to accompany the I-864.', checked: false },
        { label: 'Typically, you must provide your most recent federal tax return (IRS transcript or copy) and W-2s.', textOnly: true, nested: true },
        { label: 'It’s recommended to include proof of current income like an employment letter, recent pay stubs, and possibly past tax returns (the I-864 instructions list what to include).', textOnly: true, nested: true },
        { label: 'If using assets to meet the requirement, gather documentation of those assets (e.g., bank statements, property appraisals).', textOnly: true, nested: true },
        { id: 5.3, label: 'Submit I-864 and Documents to NVC (Consular Cases): Once the Affidavit of Support form is completed and you have the documents, upload them via the CEAC portal (for NVC) under the Affidavit of Support tab.', checked: false },
        { label: 'This includes uploading the signed I-864 (scan each page) and the financial evidence (merge into a PDF if possible).', textOnly: true, nested: true },
        { label: 'Submit the documents for NVC review. NVC will assess if the I-864 is complete and if you meet the income threshold.', textOnly: true, nested: true },
        { id: 5.4, label: 'For Adjustment of Status: If you are doing AOS, you will include the I-864 and supporting financial docs in the I-485 packet to USCIS.', checked: false },
        { label: 'If you filed the I-485 concurrently, ensure you sent these.', textOnly: true, nested: true },
        { label: 'If not, USCIS will issue an RFE for any missing Affidavit of Support.', textOnly: true, nested: true },
        { label: 'The requirements are essentially the same, but you’ll be dealing with USCIS instead of NVC.', textOnly: true, nested: true },
        { id: 5.5, label: 'Await Confirmation: For NVC cases, once you submit the I-864 and financials, the CEAC system will show them as “Submitted” and then “Accepted” or “Rejected” after review.', checked: false },
        { label: 'Check back periodically. If something is incomplete, NVC will send a message detailing the problem (such as needing a better copy, missing pages, or insufficient evidence).', textOnly: true, nested: true },
        { label: 'Respond by correcting the issue and resubmitting as needed.', textOnly: true, nested: true },
        { section: 'Required Documents' },
        { id: 5.6, label: 'Completed Form I-864: signed by the petitioner – original signature if mailed, or e-signature if uploaded via scan is acceptable for NVC.', checked: false },
        { id: 5.7, label: 'Federal Tax Documents: At minimum, the most recent year’s tax transcript or tax return (with W-2s/1099s).', checked: false },
        { label: 'NVC usually requires the most recent tax year and will accept optionally the two prior years if you want to provide a fuller financial picture.', textOnly: true, nested: true },
        { id: 5.8, label: 'Proof of Current Income: e.g., an employment verification letter from the petitioner’s employer stating position, salary and job stability; recent pay stubs (last 3–6 months);', checked: false },
        { label: 'If self-employed, maybe a letter from an accountant or business license.', textOnly: true, nested: true },
        { id: 5.9, label: 'Proof of Assets (if needed): Documents for any assets the sponsor is using to meet the shortfall', checked: false },
        { label: 'Examples: bank statements showing savings, property deeds and appraisals for real estate, etc.', textOnly: true, nested: true },
        { label: 'Assets need to be worth 3x the shortfall amount or 5x if a joint sponsor for the spouse of a citizen. This is if income doesn’t meet 125% of the poverty line.', textOnly: true, nested: true },
        { id: 5.101, label: 'Joint Sponsor’s Documents (if applicable): If a joint sponsor is used, that person must also submit a Form I-864 and all their supporting documents (proof of citizenship/residence, tax returns, income proof).', checked: false },
        { label: 'NVC will require the petitioner’s I-864 no matter what, plus joint sponsor’s I-864 if used.', textOnly: true, nested: true },
        { id: 5.11, label: 'Proof of U.S. Domicile: If the petitioner’s address on the I-864 is abroad, include evidence of U.S. domicile or plans to re-establish it (as discussed in Step 4’s FAQs).', checked: false },
        { label: 'This could be a rental agreement, job offer, or letter explaining domicile plans.', textOnly: true, nested: true },
        { section: 'Eligibility Criteria' },
        { id: 5.11, label: 'Income Requirement: The sponsor (petitioner) must have household income at or above 125% of the Federal Poverty Guidelines for the household size (including the intending immigrant).', checked: false },
        { label: 'If the sponsor is on active military duty and petitioning a spouse, the threshold is 100% of the poverty line.', textOnly: true, nested: true },
        { label: 'The exact dollar amount depends on household size – for example, for a household of 2 in 2025, 125% is around $22,887 (this number changes annually).', textOnly: true, nested: true },
        { id: 5.12, label: 'Joint Sponsor: If the petitioner’s income is below the required level, a joint sponsor (usually a friend or other relative who is a US citizen or LPR) can agree to co-sponsor.', checked: false },
        { label: 'The joint sponsor must independently meet the income requirement for their own household plus the immigrant.', textOnly: true, nested: true },
        { label: 'There can be up to two joint sponsors in spousal cases (each covering one immigrant).', textOnly: true, nested: true },
        { id: 5.13, label: 'Household Members: The sponsor can also count income of certain household members if they complete an I-864A contract.', checked: false },
        { label: 'For example, if the immigrant spouse has work income (in certain cases) or an adult child living in the household has income, their income can be included with a contract.', textOnly: true, nested: true },
        { id: 5.14, label: 'Legally Binding: The sponsor (and any joint sponsors) must be willing to accept legal responsibility – the I-864 is enforceable.', checked: false },
        { label: 'It stays in effect until the immigrant becomes a U.S. citizen, has 40 quarters of work (≈10 years) in the US, leaves the US permanently, or dies.', textOnly: true, nested: true },
        { label: 'This is an obligation, so ensure anyone who signs knows the commitment.', textOnly: true, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-5-collect-financial-evidence.html" target="_blank" rel="noopener">Step 5: Collect Financial Docs (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.irs.gov/individuals/get-transcript" target="_blank" rel="noopener">IRS – Request tax transcript</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/policy-manual/volume-12-part-g-chapter-5" target="_blank" rel="noopener">USCIS assets-substitution policy</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/forms/explore-my-options/affidavit-of-support-checklist" target="_blank" rel="noopener">USCIS I-864 evidence checklist</Link>, textOnly: true, nested: false }
    ],
    6: [
        { section: 'Tasks' },
        { id: 6.1, label: 'Complete Form DS-260 (Immigrant Visa Application): Log into the CEAC portal and fill out the DS-260 form for the beneficiary (and any accompanying children).', checked: false },
        { id: 6.2, label: 'Gather Civil Documents: Collect all required civil documents for the visa applicant (and petitioner, where required). “Civil documents” typically include', checked: false },
        { id: 6.3, label: 'The applicant’s birth certificate', checked: false, nested: true },
        { id: 6.4, label: 'Marriage certificate (and divorce decrees or death certificates for any prior marriages for either spouse)', checked: false, nested: true },
        { id: 6.5, label: 'Police clearance certificates from any country where the applicant lived 6+ months since age 16', checked: false, nested: true },
        { id: 6.6, label: 'Passport biographic page copy', checked: false, nested: true },
        { label: 'If applicable, court or military records.', textOnly: true, nested: true },
        { label: 'Refer to the specific list NVC provides and the country-specific guidelines for documents (some countries have unique requirements for how certificates are issued).', textOnly: true, nested: true },
        { id: 6.7, label: 'Obtain Translations: For any document not in English (or not in the official language of the U.S. embassy processing the case), get a certified translation.', checked: false },
        { label: 'The translator should provide a certification stating they are fluent in both languages and that the translation is accurate. Upload the original-language document and the translation together.', textOnly: true, nested: true },
        { id: 6.8, label: 'Upload and Submit Documents via CEAC: Scan each civil document clearly (follow NVC’s scanning guidelines – e.g., PDF format, file size limits).', checked: false },
        { label: 'Upload them to the CEAC system under the appropriate document type categories (Birth Certificate, Marriage Certificate, Police Certificate, etc.).', textOnly: true, nested: true },
        { label: 'If a required document is not available, you must upload: a written explanation and any proof of attempts to obtain it, and  a substitute if applicable (for example, a certificate of non-availability and secondary evidence).', textOnly: true, nested: true },
        { label: 'Once all required documents and the DS-260 are in, submit the case for NVC review (CEAC will show a “Submit Documents” button or automatically mark the case as documentarily complete when everything is uploaded).', textOnly: true, nested: true },
        { id: 6.9, label: 'For Adjustment of Status: Applicants doing AOS do not use DS-260.', checked: false },
        { label: 'Make sure you have the originals of all civil documents to bring to your AOS interview.', textOnly: true, nested: true },
        { section: 'Required Documents' },
        { id: 6.101, label: 'Form DS-260 Confirmation: after submitting DS-260, save the confirmation page (PDF or printout)', checked: false },
        { id: 6.11, label: 'Beneficiary’s Passport: need the biographic data page copy for NVC (and the physical passport for later interview).', checked: false },
        { label: 'Passport should be valid at least 6 months beyond the intended entry date.', textOnly: true, nested: true },
        { id: 6.12, label: 'Birth Certificate: Official birth certificate of the beneficiary (and any children immigrating).', checked: false },
        { label: 'Must be issued by the official civil registry. If unavailable, provide alternative evidence and a non-availability certificate.', textOnly: true, nested: true },
        { id: 6.13, label: 'Marriage Certificate: Certified copy of the marriage certificate.', checked: false },
        { label: 'If issued in a language not understood by the consulate, include a translation.', textOnly: true, nested: true },
        { id: 6.14, label: 'Divorce/Death Certificates: For each prior marriage that either the petitioner or beneficiary had, include proof of legal termination (e.g., divorce decree, annulment, or death certificate of previous spouse).', checked: false },
        { id: 6.15, label: 'Divorce/Death Certificates: For each prior marriage that either the petitioner or beneficiary had, include proof of legal termination (e.g., divorce decree, annulment, or death certificate of previous spouse).', checked: false },
        { label: 'The country of nationality (if lived there >6 months after age 16)', textOnly: true, nested: true },
        { label: 'The country of current residence (if different, >6 months)', textOnly: true, nested: true },
        { label: 'Any other country where lived >12 months (and for any country where ever arrested).', textOnly: true, nested: true },
        { label: 'Police certificates must be issued by the appropriate police authority and include all names used. Some countries’ police certs are not required or not available – check the U.S. State Department’s Reciprocity Schedule for country-specific info.', textOnly: true, nested: true },
        { id: 6.16, label: 'Court and Prison Records: If the beneficiary has a criminal record, obtain certified court records for each case, even if they were later expunged.', checked: false },
        { id: 6.17, label: 'Military Records: If applicable (beneficiary served in the military of any country), get military service records or discharge papers.', checked: false },
        { id: 6.18, label: 'Photographs: Two passport-style photos will be required at the interview', checked: false },
        { label: 'NVC doesn’t collect photos electronically for spousal visas, but some embassies ask you to upload digital photos; generally, just have physical photos ready for the interview per instructions.', textOnly: true, nested: true },
        { section: 'Eligibility Criteria' },
        { label: 'Documentation Compliance: Ensure all required documents meet the consulate’s criteria.', textOnly: true },
        { label: 'For example, some countries have multiple versions of birth certificates – you need the one the U.S. consulate specifies.', textOnly: true, nested: true },
        { label: 'If any required doc cannot be obtained, you must demonstrate why and provide secondary evidence.', textOnly: true, nested: true },
        { label: 'Failure to provide a required civil document can halt the case, so eligibility here means being able to furnish all civil docs or approved alternatives.', textOnly: true, nested: true },
        { label: 'Honesty on DS-260: The visa application will ask about inadmissibility factors (such as criminal history, immigration violations, misrepresentation, etc.).', textOnly: true, nested: true },
        { label: 'Eligibility to receive the visa depends on truthful disclosure. Certain answers (e.g., yes to previous overstays or crimes) won’t automatically disqualify you, but failing to disclose them can cause serious issues. The consular officer will ultimately determine eligibility at the interview, but a complete DS-260 and full set of documents ensures you’ve met the procedural eligibility for an interview.', textOnly: true, nested: true },
        { label: 'CSPA for Children: If a child is immigrating as a derivative, their age eligibility is determined by the Child Status Protection Act.', textOnly: true },
        { label: 'Make sure to pay fees and submit the child’s documents timely to “lock in” their CSPA age if needed. For IR-2 child of a citizen, CSPA is less relevant since immediate relative children don’t age out if under 21 when filed, but for derivatives of resident petitions upgrading, it can be relevant.', textOnly: true, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-6-submit-a-visa-application.html" target="_blank" rel="noopener">DS-260 instructions (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/dam/visas/pdfs/DS-260-Exemplar.pdf" target="_blank" rel="noopener">DS-260 exemplar PDF</Link>, textOnly: true, nested: false },
        { label: <Link href="https://ceac.state.gov" target="_blank" rel="noopener">CEAC login portal</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/i-485" target="_blank" rel="noopener">USCIS Form I-485</Link>, textOnly: true, nested: false }
    ],
    7: [
        { section: 'Tasks' },
        { id: 7.1, label: 'NVC Case Complete: Confirm that NVC has marked your case as documentarily qualified.', checked: false },
        { label: 'You may receive an email stating your case is complete and will be scheduled for an interview. In CEAC, all documents and forms should show as “Accepted”. Once case complete, there’s nothing further to submit to NVC.', textOnly: true, nested: true },
        { id: 7.2, label: 'Interview Appointment Notification: Wait for the appointment letter. NVC, in coordination with the U.S. Embassy/Consulate, will schedule the interview when a slot is available.', checked: false },
        { label: 'You will be notified by email (or mail) with the date, time, and location of the interview. This is typically a letter/email titled “Appointment Confirmation” that you should print. The wait for an interview depends on the consulate’s backlog – immediate relatives generally get priority, but it could be a few weeks to a few months after case complete. Keep checking your email and CEAC status.', textOnly: true, nested: true },
        { id: 7.3, label: 'Prepare Required Items for Interview: The appointment letter will list instructions, including scheduling a medical exam (Step 8) and what to bring.', checked: false },
        { label: 'Start organizing originals of all civil documents (the same ones you submitted electronically). lso gather supporting evidence of your relationship (album of wedding and other photos, chat logs, etc., especially if not already provided). If the beneficiary’s police certificate will expire by the interview date (many are valid for 1 year), obtain an updated one if needed.', textOnly: true, nested: true },
        { label: 'For AOS (USCIS interview): Once your I-485 is ready to be scheduled, USCIS will mail you an interview notice (with date and location at your local USCIS field office). Prepare similarly: collect originals of civil docs, updated Form I-864 if the one submitted is old (optional but sometimes advised if circumstances changed), and relationship evidence.', textOnly: true, nested: true },
        { id: 7.4, label: 'Plan Travel Logistics: If the interview is at a U.S. Consulate abroad, make necessary arrangements.', checked: false },
        { label: 'Ensure the beneficiary can travel to the city of the interview on that date. Some consulates require you to register for courier service or fingerprinting ahead of the interview – the appointment notice or embassy website will have those instructions. Follow any steps, like registering your address for passport delivery or creating a profile on the consulate’s appointment website if instructed.', textOnly: true, nested: true },
        { id: 7.5, label: 'Keep Visa Validity in Mind: Take note of your medical exam and police certificate dates.', checked: false },
        { label: 'An immigrant visa, once issued, is typically valid for 6 months from the medical exam date (or issuance date). Ensure you plan to attend the interview and, if approved, travel before those expire. If there’s any delay or you cannot attend on the scheduled date, inform NVC or the consulate as early as possible to reschedule (but rescheduling could mean a significant additional wait).', textOnly: true, nested: true },
        { label: 'For AOS, attending the USCIS interview as scheduled is crucial – rescheduling can add months of delay.', textOnly: true, nested: true },
        { section: 'Required Documents (For Interview scheduling/prep stage)' },
        { id: 7.6, label: 'Interview Appointment Letter from NVC or USCIS – this is essential to bring to the interview. It contains your case number and interview details.', checked: false },
        { id: 7.7, label: 'Original Civil Documents: Passport, birth certificate, marriage certificate, police certificates, etc. (the same set you submitted copies of).', checked: false },
        { id: 7.8, label: 'Updated Evidence: It’s good to bring updated financial documents for the petitioner (like latest pay stubs, job letter) especially if some time has passed since NVC.', checked: false },
        { label: 'If the petitioner changed jobs or income, an updated I-864 or at least proof of continued ability to support is wise to carry.', textOnly: true, nested: true },
        { id: 7.9, label: 'Relationship Proof: Photo album, chat/email logs, letters, jointly filed tax returns or joint accounts, etc.', checked: false },
        { label: 'Consular officers and USCIS officers may ask about your relationship, so having these on hand can help if they are needed to prove the marriage is genuine.', textOnly: true, nested: true },
        { id: 7.101, label: 'Passport (Beneficiary): Ensure the beneficiary’s passport is valid for at least 6 months beyond the interview date.', checked: false },
        { id: 7.11, label: 'For AOS:', textOnly: true },
        { id: 7.12, label: 'Government-issued ID for the interview (passport, driver’s license)', checked: false, nested: true },
        { id: 7.13, label: 'The I-485 interview notice', checked: false, nested: true },
        { id: 7.14, label: 'The I-693 medical (if not submitted or if a deficiency notice was issued telling you to bring it)', checked: false, nested: true },
        { id: 7.15, label: 'EAD/AP cards if any were issued', checked: false, nested: true },
        { section: 'Eligibility Criteria' },
        { label: 'Continued Marital Relationship: At the interview stage, one basic “eligibility” factor is that you are still legally married and intend to remain married.', textOnly: true },
        { label: 'If, for instance, the spouses divorced after the petition, the case cannot proceed. So it’s critical that the relationship basis remains valid.', textOnly: true, nested: true },
        { label: 'Good Standing: The beneficiary should avoid any incidents (arrests, etc.) between filing and interview that could affect admissibility.', textOnly: true },
        { label: 'If something does occur, be prepared to disclose it and have court documents.', textOnly: true, nested: true },
        { label: 'Medical Exam and Vaccinations: Eligibility to receive the visa includes being medically admissible.', textOnly: true },
        { label: 'The upcoming medical exam (Step 8) will evaluate this. Make sure you complete the exam and required vaccines; not doing so could delay visa issuance.', textOnly: true, nested: true },
        { label: 'No Changes in Qualifying Conditions: For example, the petitioner must remain a U.S. citizen.', textOnly: true },
        { label: 'If the petitioner were a permanent resident who became a U.S. citizen during the process, the case typically upgrades (which is positive). But if any key factor changed negatively (petitioner lost status or passed away – which can be handled under a different process), that would affect eligibility. For the majority, nothing changes – just ensure you update the consulate/USCIS if there’s something like a new address or the birth of a child, etc.', textOnly: true, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-7-collect-civil-documents.html" target="_blank" rel="noopener">Step 7: Civil Docs list (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/Visa-Reciprocity-and-Civil-Documents-by-Country.html" target="_blank" rel="noopener">Reciprocity & Civil-Docs finder</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/forms/forms-information/guidance-for-translators" target="_blank" rel="noopener">USCIS translation requirements</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.cdc.gov/immigrantrefugeehealth/exams/ti/civil-documents.html" target="_blank" rel="noopener">CDC civil doc guidance (medical tie-in)</Link>, textOnly: true, nested: false }
    ],
    8: [
        { section: 'Tasks' },
        { id: 8.1, label: 'Schedule the Immigrant Medical Exam: As soon as you receive your interview date, book your medical examination with a panel physician approved by the U.S. Embassy or Consulate.', checked: false },
        { label: 'The State Department or the embassy’s website lists the authorized clinics in your country. Schedule it timing-wise so that the exam is completed before your interview (often 1 to 2 weeks prior is ideal). For Adjustment of Status, if you haven’t done a medical with your I-485 filing or if you were told to bring it to the interview, schedule your exam with a civil surgeon (authorized USCIS doctor) about 4–6 weeks before the interview or as instructed (the sealed I-693 medical report should be less than 2 years old at time of interview to be valid).', textOnly: true, nested: true },
        { label: 'Prepare Required Items for the Medical:', textOnly: true },
        { id: 8.2, label: 'Passport (or other government ID)', checked: false },
        { id: 8.3, label: 'Vaccination records', checked: false },
        { id: 8.4, label: 'Interview appointment letter', checked: false },
        { id: 8.5, label: 'Any forms or photos the doctor’s office requires (some require passport-style photos for the medical forms).', checked: false },
        { label: 'The doctor will review your immunization history and administer any missing vaccines required by U.S. immigration law: MMR, Tdap, flu shot in season, COVID-19 vaccine, etc.). They will also do a physical exam and tests for communicable diseases (tuberculosis, syphilis, etc.). Be prepared to discuss your medical history.', textOnly: true, nested: true },
        { id: 8.6, label: 'Obtain Medical Exam Results: The panel physician will either give you a sealed envelope with your results or send it directly to the embassy.', checked: false },
        { label: 'Do not open any sealed envelope given to you – you will bring it to the interview and the consular officer will open it. If it’s an electronic transfer (some clinics now send results electronically), the clinic will inform you of that. For AOS, the civil surgeon will give you a sealed Form I-693 envelope to bring to your USCIS interview (if not already submitted).', textOnly: true, nested: true },
        { id: 8.7, label: 'Final Interview Preparations: In the days leading up to the interview, double-check that you have gathered all required documents (originals and photocopies if required by the embassy).', checked: false },
        { label: 'Organize them in a logical order (perhaps by category: identity docs, relationship docs, financial docs, etc.) for easy access during the interview. Practice answering possible interview questions with your spouse. Topics usually include the history of your relationship, basic biographical info about each other, etc.', textOnly: true, nested: true },
        { id: 8.8, label: 'Review the Rights & Protections Pamphlet: The U.S. government provides a pamphlet on the legal rights of immigrant spouses (related to domestic violence protections under the IMBRA law).', checked: false },
        { label: 'This is often sent with the interview notice or given at the medical. Make sure the beneficiary reads this Visa Rights pamphlet, as the consular officer may ask if you have read and understood it. It covers your rights in the U.S. and resources if you face abuse or trafficking.', textOnly: true, nested: true },
        { section: 'Required Documents' },
        { id: 8.9, label: 'Passport: Needed for the medical exam identification and obviously for the interview itself.', checked: false },
        { id: 8.101, label: 'Visa Interview Letter: Some clinics want to see the interview appointment letter to verify you have an interview scheduled.', checked: false },
        { id: 8.11, label: 'Vaccination Records: Any immunization records (childhood vaccination card, etc.) to help the panel physician determine which vaccines you need.', checked: false },
        { label: 'If you don’t have records, the doctor will generally vaccinate you according to U.S. requirements, which may result in multiple shots (and additional cost).', checked: false },
        { id: 8.12, label: 'Medical Reports: If you have significant medical history (past TB treatment, surgery, or chronic conditions), bring relevant medical letters or records for the physician to review.', checked: false },
        { label: 'For instance, if you had tuberculosis in the past, bring documentation as this will be important for clearance.', textOnly: true, nested: true },
        { id: 8.13, label: 'Fees for Medical: The medical exam fee, which varies by country/clinic.', checked: false },
        { label: 'It’s usually paid by the applicant at the time of the exam. Not a document, but something to be prepared for – bring the required payment and any passport photos if the doctor requires them.', textOnly: true, nested: true },
        { label: 'Rights Pamphlet: Although not a document to bring, ensure you have read the “USCIS Immigrant Rights and Responsibilities” pamphlet about domestic violence/trafficking. The officer may verbally confirm you received it.', textOnly: true },
        { section: "Eligibility Criteria" },
        { label: 'Health-Related Grounds: The medical exam is to check eligibility on health grounds.', textOnly: true },
        { label: 'Certain conditions can make someone inadmissible: active tuberculosis, untreated syphilis, drug addiction, not having required vaccines without reason). If a problem is found (say a positive TB test), the panel physician will guide you through additional steps (like a chest X-ray, or treatment plan). You generally must complete any required treatment or obtain a waiver if one is needed for vaccination refusal on religious/medical grounds. Eligibility to receive the visa will hinge on a “Class A” condition (like active TB) being resolved or waived. Pregnant applicants: can usually postpone certain vaccines or X-rays by signing a waiver, but discuss with the physician.', textOnly: true, nested: true },
        { label: 'Moral Character/Background: This is not directly part of the medical, but final prep involves ensuring nothing new jeopardizes eligibility (e.g., any new criminal issues).', textOnly: true },
        { label: 'At the interview, you’ll again affirm the truth of your DS-260 or I-485 answers. If something has changed (e.g., an arrest since filing), you must disclose it. If something has changed (e.g., an arrest since filing), you must disclose it. Eligibility can be affected by certain criminal or security issues, but those would typically have been screened earlier as well. Final prep is making sure you have documentation for any potentially complicating factors (e.g., court documents for past incidents, or evidence for any claimed waiver).', textOnly: true, nested: true },
        { label: 'Relationship Authenticity: In terms of eligibility at the interview, a big factor is convincing the officer your marriage is genuine.', textOnly: true },
        { label: 'Your eligibility for an IR-1/CR-1 visa is directly tied to being an immediate relative spouse – a sham marriage would mean ineligibility.', textOnly: true, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-9-submit-documents-to-the-nvc.html" target="_blank" rel="noopener">Step 9: Submit Docs (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/dam/visas/pdfs/scanning_guidelines.pdf" target="_blank" rel="noopener">NVC scanning-guidelines PDF</Link>, textOnly: true, nested: false },
        { label: <Link href="https://ceac.state.gov" target="_blank" rel="noopener">CEAC document-upload portal</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/nvc/email.html" target="_blank" rel="noopener">NVC public-inquiry directions</Link>, textOnly: true, nested: false }
    ],
    9: [
        { section: 'Tasks' },
        { id: 9.1, label: 'Arrive Early and Be Prepared', checked: false },
        { label: 'On the day of the interview, arrive at the embassy/consulate (or USCIS office for AOS) early – usually 15-30 minutes before your appointment time. Bring your passport, appointment letter, and the sealed medical exam report (if you have one). Expect to go through security screening (no electronics or bags, etc., at most consulates). For USCIS interviews, bring government-issued ID and the interview notice. Both spouses should attend USCIS (AOS) interviews. For consular, the beneficiary attends (petitioner can accompany if allowed).', textOnly: true, nested: true },
        { id: 9.2, label: 'Verification of Identity and Oath', checked: false },
        { label: 'When called up to the interview window or office, you (the beneficiary applicant) will typically be asked to provide fingerprints (fingerprint scans for consular, if not already taken) and swear an oath to tell the truth. The officer (consular or USCIS) will usually begin by verifying your identity and reviewing your documents. They might ask for originals of certain documents (birth certificate, marriage cert, police cert). Hand those over along with your passport.', textOnly: true, nested: true },
        { id: 9.3, label: 'Answer Questions Clearly and Truthfully', checked: false },
        { label: 'The interviewing officer will ask you a series of questions. These include confirming basic information from your application (dates of birth, address, etc.), as well as questions about your relationship and background. Common questions for spouses: “How did you meet?”, “When did you start dating/decide to marry?”, “How many people attended your wedding?”. If you don’t understand a question, politely ask for clarification. If you need translation, some consulates provide interpreters or allow one; USCIS allows interpreters in certain cases (except where English is required; marriage interviews can use interpreters if needed). Ensure your answers match the information in your forms – inconsistency can raise flags. It’s okay if you’re nervous, but try to stay calm.', textOnly: true, nested: true },
        { id: 9.4, label: 'Present Additional Evidence if Requested', checked: false },
        { label: 'The officer may ask for specific documents or evidence. For example, a consular officer might say, “Do you have photos of you and your spouse together?” or “Can you provide proof of your spouse’s domicile in the U.S.?” Be ready to provide those from your prepared file. They might flip through a photo album or glance at correspondence. If something is missing (e.g., you forgot a document), the officer might give you a 221(g) letter to submit it later – but try to have everything there. For USCIS, if some updated information is needed (like a new medical or an updated I-864), the officer may accept it on the spot.', textOnly: true, nested: true },
        { id: 9.5, label: 'Listen for the Decision or Next Steps', checked: false },
        { label: 'At the end of the interview, the officer will typically let you know the outcome. In consular cases, if approved, they often say something like “Your visa is approved” and will keep the passport to place the visa in it. They might hand you a paper with instructions for passport pickup and visa packet. If they cannot approve on the spot, they may hand you a 221(g) refusal sheet indicating what’s missing or if further administrative processing is needed. For USCIS (AOS), the officer may not always give an immediate decision; sometimes they hand you a paper stating the case is being held for review. Often, however, for straightforward cases they might verbally say “I’m going to approve your case” or you’ll see an update online within a day or two (and later get an approval notice). If there are issues, USCIS might issue an RFE or Notice of Intent to Deny after the interview. Before leaving, make sure you understand if anything else is required from you.', textOnly: true, nested: true },
        { section: 'Required Documents' },
        { id: 9.6, label: 'Passport: (Beneficiary’s passport, and petitioner’s ID for USCIS interviews)', checked: false },
        { id: 9.7, label: 'Interview Appointment Letter (from NVC or USCIS)', checked: false },
        { id: 9.8, label: 'Original Civil Documents: Birth, marriage, divorce certificates, police certificate, etc. (and copies if required by that embassy – some embassies keep a copy).', checked: false },
        { id: 9.9, label: 'Medical Exam Results: Sealed envelope or confirmation it was sent.', checked: false },
        { id: 9.101, label: 'Proof of Relationship: Photo album, chat logs, wedding album, etc. (Not officially “required” but highly recommended to bring).', checked: false },
        { id: 9.11, label: 'Petitioner’s Financial Evidence: If not already sufficient or updated, things like recent pay stubs, job letter, latest tax return.', checked: false },
        { label: 'Consular officers have the I-864, but updates can be provided if the situation has changed; USCIS officers might ask for the latest info if the I-864 on file is old.', textOnly: true, nested: true },
        { id: 9.12, label: 'Joint Sponsor Documents (if any): Originals or certified copies of things like their proof of U.S. status, in case the officer wants to see those.', checked: false },
        { id: 9.13, label: 'Other Supporting Docs', checked: false },
        { label: 'Anything pertinent to your case – e.g., proof of domicile if the petitioner lives abroad (a rental lease in the US, etc.), proof of relationship continuity (if long time since filing, maybe proof you stayed in touch or visited in between). It’s better to have and not need than need and not have.', textOnly: true, nested: true },
        { section: "Eligibility Criteria" },
        { label: 'Final Consular Determination', textOnly: true },
        { label: 'At the interview, the consular officer is determining if the applicant is eligible for an immigrant visa. They verify: the relationship is genuine and the marriage is valid; the Affidavit of Support is adequate; the applicant is not inadmissible on criminal, security, or medical grounds; and that all paperwork is in order. If all is good, you’re eligible for approval. If there’s a snag (like a missing document or a suspicion of fraud), the officer can refuse under section 221(g) (temporary refusal pending more info) or 212(e) etc., depending on the issue. Most common is 221(g) for missing items or administrative processing. Eligibility can also fail if the officer finds evidence the marriage might be a sham – they could then refuse under INA §212(a)(6)(C) for fraud/misrepresentation or INA §204(c) (permanent bar for attempted marriage fraud). This is rare, and usually only if there’s strong evidence of fraud. For AOS, the USCIS officer is doing a similar evaluation for granting permanent residence. If they feel the marriage is not bona fide, they could schedule a second, Stokes interview (a more intense interview) or issue a denial.', textOnly: true, nested: true },
        { label: 'Immigrant Intent', textOnly: true },
        { label: 'By attending this interview, it’s assumed the beneficiary intends to immigrate (for consular cases). The officer might confirm that the beneficiary indeed plans to live in the U.S. (since an IR-1/CR-1 visa is for permanent residence, not just a visit). As long as you affirm that, it’s fine.', textOnly: true, nested: true },
        { label: 'No Changes in Circumstances', textOnly: true },
        { label: 'The spouses should still be married and in a genuine relationship. If, hypothetically, a couple had separated or divorced after getting the petition approved, the applicant would no longer be eligible for the visa and should not proceed. The interview is essentially the last checkpoint for eligibility.', textOnly: true, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://www.uscis.gov/forms/filing-guidance/preparing-for-your-biometric-services-appointment" target="_blank" rel="noopener">USCIS biometrics prep</Link>, textOnly: true, nested: false },
        { label: <Link href="https://my.uscis.gov/findadoctor" target="_blank" rel="noopener">Civil-surgeon locator (AOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/medical-examination.html" target="_blank" rel="noopener">DOS medical-exam guide</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.cdc.gov/immigrantrefugeehealth/panel-physician.html" target="_blank" rel="noopener">CDC panel-physician instructions</Link>, textOnly: true, nested: false }
    ],
    10: [
        { section: 'Task Checklist' },
        { id: 10.1, label: 'If Visa Approved (Consular)', checked: false },
        { id: 10.14, label: 'Congratulations! The officer has approved your immigrant visa. Your passport will remain at the embassy for the visa to be printed. You’ll typically receive it back within a short period (often 1 to 2 weeks, sometimes even just a few days, depending on the consulate and chosen delivery method). Along with your passport (now containing the IR-1/CR-1 visa stamp), you may get a sealed envelope (unless the consulate sent your documents electronically). Do not open any sealed envelope. Check the visa stamp in your passport for accuracy – make sure your name, date of birth, and category (IR1 or CR1) are correct. Also note the expiration date of the visa and the “IV Case Number” on it. If you spot an error, contact the consulate immediately for correction.', checked: false, nested: true },
        { id: 10.2, label: 'Administrative Processing or Visa Delay', checked: false },
        { label: 'If you received a 221(g) sheet or were told your case needs administrative processing, follow any instructions given. This may include submitting additional documents (e.g., updated police certificate or more proof of relationship) or simply waiting while security checks are completed. Submit any requested documents promptly via the specified method (upload, email, or drop-off) and check your CEAC case status regularly. Administrative processing can take days or months; stay in touch with the consulate if delays extend beyond a reasonable timeframe.', textOnly: true, nested: true },
        { id: 10.3, label: 'If Deferred or Pending (USCIS AOS)', checked: false },
        { label: 'At some AOS interviews, the officer may defer a decision pending supervisor review or final background checks. If given a letter with instructions (e.g., to submit additional evidence), comply immediately. Otherwise, monitor your USCIS online account for updates like “New Card Is Being Produced.” If you receive a Notice of Intent to Deny (NOID) or RFE, respond by the deadline with the requested information and consider legal assistance if needed.', textOnly: true, nested: true },
        { id: 10.4, label: 'Passport and Visa Delivery', checked: false },
        { label: 'Once your visa is printed, you’ll retrieve your passport either by courier pickup or mail. Inspect the visa foil for your A-Number, DS-260 number, IV expiration date (typically 6 months from your medical exam date), and any CR-1 annotation. “IV Docs in CCD” indicates an electronic packet; if you received a physical packet, keep it sealed for CBP at entry.', textOnly: true, nested: true },
        { id: 10.5, label: 'Receive USCIS Approval Notice (AOS)', checked: false },
        { label: 'If approved at your AOS interview, USCIS will mail an Approval Notice (Form I-797) within 1–2 weeks, followed by your green card. If no update arrives after 30 days, contact USCIS for a status inquiry.', textOnly: true, nested: true },
        { section: 'Required Documents/Steps if Follow-Up Needed' },
        { id: 10.6, label: '221(g) Submission', checked: false },
        { label: 'If instructed to submit additional documents to the consulate, gather and deliver them promptly (e.g., original documents or updated joint sponsor evidence) following the 221(g) letter’s cover sheet and submission method.', textOnly: true, nested: true },
        { id: 10.7, label: 'Waiver Applications', checked: false },
        { label: 'In rare cases requiring a waiver (e.g., inadmissibility for past violation), you must file the appropriate waiver form (such as I-601), a process that can take many months and is discussed with you if applicable.', textOnly: true, nested: true },
        { id: 10.8, label: 'Passport Pickup Info', checked: false },
        { label: 'Bring a government-issued ID and any tracking number or receipt when retrieving your passport. If a third party collects on your behalf, ensure proper authorization per consulate instructions.', textOnly: true, nested: true },
        { id: 10.9, label: 'USCIS RFE/NOID Response', checked: false },
        { label: 'If USCIS issues an RFE or NOID after your interview, compile the requested evidence (e.g., additional bona fide marriage proof) and submit it by the deadline (typically 30 days for NOID, 87 days for RFE) with the cover page provided.', textOnly: true, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/step-10-preparing-for-your-interview.html" target="_blank" rel="noopener">Step 10: Prepare for Interview (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/green-card/after-we-grant-your-green-card/attend-your-appointment" target="_blank" rel="noopener">USCIS interview-day overview (AOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/i-693" target="_blank" rel="noopener">USCIS Form I-693 (medical)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/dam/visas/PDF-other/Interview-Preparation-Checklist.pdf" target="_blank" rel="noopener">DOS interview checklist PDF</Link>, textOnly: true, nested: false }
    ],
    11: [
        { section: 'Task Checklist' },
        { id: 11.1, label: 'Plan Your Entry: With visa in hand, book your travel to the United States.', checked: false },
        { label: "Remember, if your spouse (the petitioner) is not traveling with you, it’s okay – the beneficiary can travel alone.", textOnly: true, nested: true },
        { label: "However, if you have derivative children on separate visas, the primary applicant must enter before or at the same time as derivatives.", textOnly: true, nested: true },
        { label: "So, if both you and children got visas, you (the spouse) should not enter after your children.", textOnly: true, nested: true },
        { label: "Coordinate travel accordingly.", textOnly: true, nested: true },
        { id: 11.2, label: 'Carry All Necessary Documents: When you travel, carry your passport with the immigrant visa, and the sealed immigrant packet (if you were given one) in your hand luggage (do not check it in luggage).', checked: false },
        { label: "Also have any other relevant documents handy (e.g., the X-ray CD from your medical if provided – sometimes CBP might ask for it, though rarely).", textOnly: true, nested: true },
        { label: "It’s also good to carry a copy of your marriage certificate and contact information for your petitioner in case needed.", textOnly: true, nested: true },
        { label: "You will also need to fill out a CBP declaration form (standard customs form) on the plane or use the kiosks if available – state that you’re entering on an immigrant visa.", textOnly: true, nested: true },
        { id: 11.3, label: 'Presenting to CBP at Port of Entry: Upon arrival at the U.S. Port of Entry (airport or land border), inform the primary inspection officer that you are entering on an immigrant visa.', checked: false },
        { label: "They will likely escort you to secondary inspection for processing of your papers.", textOnly: true, nested: true },
        { label: "In secondary, a CBP officer will take your sealed envelope (or retrieve your electronic file) and your passport.", textOnly: true, nested: true },
        { label: "They will review your documents, maybe ask a couple of standard questions (confirming your U.S. address, etc.), and then process your admission.", textOnly: true, nested: true },
        { label: "They will stamp your passport with an I-551 stamp (valid for one year as proof of permanent residence).", textOnly: true, nested: true },
        { label: "This stamp, together with the visa foil, serves as your temporary green card.", textOnly: true, nested: true },
        { label: "The officer will tell you \"Welcome to the United States\" – at that moment, you become a U.S. lawful permanent resident!", textOnly: true, nested: true },
        { id: 11.4, label: 'Pay the USCIS Immigrant Fee (if not already paid): If you haven’t paid the $220 immigrant fee yet, do so as soon as possible after entry (you can pay it online from inside the U.S. as well).', checked: false },
        { label: "USCIS will not mail your physical green card until this fee is paid.", textOnly: true, nested: true },
        { label: "If you already paid it before traveling, you don’t need to do anything else regarding payment.", textOnly: true, nested: true },
        { id: 11.5, label: 'Arrange Social Security Number (SSN): On your DS-260 you had the option to apply for a Social Security Number.', checked: false },
        { label: "If you opted \"Yes,\" the SSA should automatically issue you an SSN card and mail it to the U.S. address you provided, usually within a few weeks of entry.", textOnly: true, nested: true },
        { label: "If you do not receive an SSN card after, say, 3–4 weeks of being in the U.S., you can visit a local SSA office with your passport and I-551 stamp to inquire or apply in person.", textOnly: true, nested: true },
        { label: "For AOS applicants, if you requested an SSN on the I-485, similar process; otherwise, you can apply at SSA once you have your green card or stamp.", textOnly: true, nested: true },
        { section: 'Required Documents' },
        { id: 11.6, label: 'Passport with Immigrant Visa: This is your key to enter. The visa will be used by the airline to board you on a one-way ticket as an immigrant.', checked: false },
        { id: 11.7, label: 'Sealed Immigrant Packet: (If provided by consulate) – must be in your carry-on and given to CBP.', checked: false },
        { id: 11.8, label: 'Copy of Visa Fee Payment Receipt: Not mandatory, but if you paid the USCIS Immigrant Fee online, having a printout of the receipt could be useful in case of any confusion (rarely needed).', checked: false },
        { id: 11.9, label: 'Address in the U.S.: You should have on hand the U.S. address where you will live or where you want your green card mailed (usually this is the address you gave in your application. If you need to change it, you can inform the CBP officer).', checked: false },
        { id: 11.101, label: 'Customs Declaration: As a new resident, you can bring your personal belongings duty-free.', checked: false },
        { label: "If you’re bringing in goods or cash over $10,000, declare appropriately.", textOnly: true, nested: true },
        { label: "There’s also a one-time exemption for moving household goods, etc., as a new immigrant (not taxed).", textOnly: true, nested: true },
        { label: "If you have a detailed list of items you shipped, you can present it if needed (usually not required at airport, more for land border or later shipments).", textOnly: true, nested: true },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/interview.html" target="_blank" rel="noopener">Applicant-interview page (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/administrative-processing-information.html" target="_blank" rel="noopener">Administrative-processing info</Link>, textOnly: true, nested: false },
        { label: <Link href="https://egov.uscis.gov/casestatus/landing.do" target="_blank" rel="noopener">USCIS online case-status</Link>, textOnly: true, nested: false },
        { label: <Link href="https://ceac.state.gov/ceac/" target="_blank" rel="noopener">CEAC visa-status portal</Link>, textOnly: true, nested: false }
    ],
    12: [
        { section: 'Task Checklist' },
        { id: 12.1, label: 'Receive Your Physical Green Card: After entering the U.S. as a new permanent resident (or after USCIS approves your status for AOS), your actual Green Card (Form I-551) will be mailed to the U.S. address you provided.', checked: false },
        { label: "This is a plastic ID card with your photo and USCIS number.", textOnly: true, nested: true },
        { label: "It typically arrives within a month or so of your entry/approval.", textOnly: true, nested: true },
        { label: "When it arrives, sign the card on the back (there’s a signature strip).", textOnly: true, nested: true },
        { label: "Keep it in a safe place – this is your primary proof of lawful permanent resident status.", textOnly: true, nested: true },
        { label: "If 90 days pass and you don’t get it, contact USCIS to inquire.", textOnly: true, nested: true },
        { id: 12.2, label: 'Check Green Card Details: Verify that the information on the card is correct:', checked: false },
        { id: 12.3, label: 'Your name (spelling)', checked: false, nested: true },
        { id: 12.4, label: 'Birthdate', checked: false, nested: true },
        { id: 12.5, label: 'Country of birth', checked: false, nested: true },
        { id: 12.6, label: '“Resident Since” date (which should be your entry or approval date)', checked: false, nested: true },
        { id: 12.7, label: 'Expiration date.', checked: false, nested: true },
        { label: "For IR-1 cards, you’ll have a 10-year expiration.", textOnly: true, nested: true },
        { label: "For CR-1 (conditional) cards, the expiration will be 2 years from the “resident since” date.", textOnly: true, nested: true },
        { label: "If there’s an error (like a wrong birthdate), you’ll need to apply for a replacement card with a correction (Form I-90) – do that as soon as possible.", textOnly: true, nested: true },
        { id: 12.8, label: 'Conditional Resident Next Steps (if applicable): If you entered on a CR-1 visa or your marriage was under 2 years at time of green card approval, you are a Conditional Permanent Resident.', checked: false },
        { label: "This means your status is valid for 2 years.", textOnly: true, nested: true },
        { label: "You and your spouse must file Form I-751, Petition to Remove Conditions on Residence during the 90-day period before your 2-year anniversary of residence.", textOnly: true, nested: true },
        { label: "Mark your calendar for that window. Example: Green card “Resident since” = Sept 1, 2025, then you must file I-751 between June 3, 2027 and Sept 1, 2027. The I-751 will convert your status to a full permanent resident (10-year card) once approved.", textOnly: true, nested: true },
        { label: "If you do not file I-751 in time, your status will terminate.", textOnly: true, nested: true },
        { id: 12.9, label: 'Maintain Your Permanent Residence: Now that you’re a green card holder, ensure to maintain your status. This includes:', checked: false },
        { label: "Residing in the U.S. (trips abroad of 6+ months can raise issues, over 1 year require a re-entry permit or special considerations)", textOnly: true, nested: true },
        { label: "Filing U.S. taxes as a resident, and obeying U.S. laws.", textOnly: true, nested: true },
        { label: "You should also carry proof of your status (your green card) when traveling or if required to show employment eligibility.", textOnly: true, nested: true },
        { label: "Update your address with USCIS (via AR-11) within 10 days whenever you move.", textOnly: true, nested: true },
        { label: "Your green card will need renewal every 10 years (like a driver’s license) by filing Form I-90, but that’s routine.", textOnly: true, nested: true },
        { label: "Conditional residents will replace their 2-year card with a 10-year after I-751.", textOnly: true, nested: true },
        { id: 12.101, label: 'Explore Benefits and Next Steps: As an LPR, you can now live and work freely in the U.S.', checked: false },
        { label: "You may consider things like getting a state ID or driver’s license using your green card and SSN, opening bank accounts, etc.", textOnly: true, nested: true },
        { label: "After a certain period, you might be eligible for naturalization (U.S. citizenship).", textOnly: true, nested: true },
        { label: "For spouses of U.S. citizens, you can apply for citizenship after 3 years of being an LPR, provided you have been living with your U.S. citizen spouse that whole time and meet other requirements.", textOnly: true, nested: true },
        { label: "It’s not mandatory, but an option.", textOnly: true, nested: true },
        { label: "Mark that possibility on your long-term calendar if interested.", textOnly: true, nested: true },
        { label: "Also, if you plan to travel frequently, once you have your green card, look into getting a Re-entry Permit if you’ll be away for more than a year, to protect your status.", textOnly: true, nested: true },
        { section: 'Required Ongoing Actions' },
        { id: 12.11, label: 'Form I-751 (Removal of Conditions): Prepare to file within 90-day window before 2-year card expiration (only for CR-1 cases).', checked: false },
        { label: "This requires evidence that the marriage is ongoing (similar to initial evidence, but updated: joint bills, leases, kids’ birth certs if any, etc.)", textOnly: true, nested: true },
        { label: "Both spouses sign (unless you qualify for a waiver due to divorce or other circumstances).", textOnly: true, nested: true },
        { label: "Mark the date so you don’t forget.", textOnly: true, nested: true },
        { id: 12.12, label: 'Address Updates: Use USCIS online AR-11 form whenever you move. This is legally required for LPRs.', checked: false },
        { id: 12.13, label: 'Green Card Renewal: In 10 years (if IR-1) you’ll file Form I-90 to renew the card (a simple process, no interview usually). Conditional residents will be filing I-751 well before that.', checked: false },
        { id: 12.14, label: 'Preserve Evidence: It’s wise to continue keeping evidence of your marital relationship (joint taxes, photos, etc.), not only for I-751 if applicable, but also sometimes helpful for citizenship application to show you were living together for the 3-year rule.', checked: false },
        { id: 12.15, label: 'Know Your Rights and Responsibilities: As a resident you can work in any job (no need for EAD), you can’t vote in federal elections (until citizenship), and you should avoid any actions that could jeopardize your status (e.g., crimes, long absences without re-entry permit). If you obey the law and make the U.S. your permanent home, your status is secure.', checked: false },
        { section: 'Links and Sources' },
        { label: <Link href="https://travel.state.gov/content/travel/en/us-visas/immigrate/the-immigrant-visa-process/after-the-interview.html" target="_blank" rel="noopener">After-the-Interview (DOS)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/file-online/uscis-immigrant-fee" target="_blank" rel="noopener">USCIS immigrant-fee payment</Link>, textOnly: true, nested: false },
        { label: <Link href="https://i94.cbp.dhs.gov/I94/" target="_blank" rel="noopener">CBP I-94 retrieval (proof of entry)</Link>, textOnly: true, nested: false },
        { label: <Link href="https://www.uscis.gov/ar-11" target="_blank" rel="noopener">USCIS change-of-address (AR-11)</Link>, textOnly: true, nested: false }
    ]
}