const SpouseGlossary = {
  "Green Card Process": "The steps involved in becoming a lawful permanent resident of the United States.",
  "Lawful nonimmigrant": "Not a U.S. citizen and not a lawful permanent resident. People who enter the U.S. on a temporary basis—for tourism, business, work, or study.",
  "Permanent Resident Card": "Also known as a Green Card.",
  "Green card": "Another term for Permanent Resident Card.",
  "A-Number": "Alien Registration Number assigned to non-citizens by USCIS.",
  "IRS": "Internal Revenue Service, the U.S. government agency responsible for tax collection.",
  "Statutory period": "The legally required period (usually 3–5 years) of continuous residence in the U.S. for naturalization.",
  "Civics": "U.S. history and government knowledge required for the naturalization test.",
  "VAWA": "Violence Against Women Act, which allows certain noncitizens to apply for immigration relief without their abuser's knowledge.",
  "Form N-470": "Application to Preserve Residence for Naturalization Purposes.",
  "Form N-648": "Medical Certification for Disability Exceptions.",
  "N-400": "Application for Naturalization.",
  "Form G-1450": "Authorization for Credit Card Transaction.",
  "Form I-90": "Application to Replace Permanent Resident Card.",
  "Form G-28": "Notice of Entry of Appearance as Attorney or Representative.",
  "Form FS-240": "Report of Birth Abroad of a Citizen of the United States of America.",
  "Form N-426": "Request for Certification of Military or Naval Service.",
  "DD Form 214": "Certificate of Release or Discharge from Active Duty.",
  "NGB Form 22": "National Guard Report of Separation and Record of Service.",
  "Form I-912": "Request for Fee Waiver.",
  "Form I-797C": "Notice of Action. Often used for appointment notices or receipt confirmations.",
  "Form N-14": "Request for Additional Information, Documents, or Forms.",
  "Form N-336": "Request for a Hearing on a Decision in Naturalization Proceedings.",
  "Form N-445": "Notice of Naturalization Oath Ceremony.",
  "Petitioner": "U.S. citizen or resident who files the family-based petition.",
  "Beneficiary": "Relative being sponsored for the green card.",
  "Immediate Relative": "Spouse, unmarried child < 21, or parent of a U.S. citizen; visas always available.",
  "Adjustment of Status": "Applying for the green card inside the U.S. with Form I-485.",
  "AOS": "Applying for the green card inside the U.S. with Form I-485.",
  "Affidavit of Support": "Contract in which the sponsor promises to support the immigrant financially.",
  "I-864": "Contract in which the sponsor promises to support the immigrant financially.",
  "NVC": "State-Department center that collects fees/docs and schedules consular interviews.",
  "Consular Processing": "Finishing the case at a U.S. embassy abroad and entering on an immigrant visa.",
  "USCIS": "Agency that adjudicates immigration petitions inside the U.S.",
  "Documentarily Qualified": "NVC has everything it needs; case awaits interview scheduling.",
  "DQ": "NVC has everything it needs; case awaits interview scheduling.",
  "Visa Number": "Available immigrant-visa slot; always current for immediate relatives.",
  "Form I-130": "Petition that proves the qualifying family relationship.",
  "Form I-130A": "Supplemental Information for Spouse Beneficiary",
  "Form I-864": "Affidavit of Support",
  "Form I-751": "Petition to Remove Conditions on Residence",
  "Form G-1145": "E-Notification of Application/Petition Acceptance",
  "Form I-485": "Application to Register Permanent Residence or Adjust Status",
  "Form I-797C": "Notice of Action. It is often an appointment notice or a receipt.",
  "Form I-797": "Notice of Action. Receipt or Approval of an Application or Petition.",
  "Form I-290B": "Notice of Appeal or Motion",
  "Form AR-11": "Alien’s Change of Address Card",
  "Form DS-261": "Choice of Address and Agent",
  "Form I-944": "Declaration of Self-Sufficiency",
  "Form I-765": "Application for Employment Authorization",
  "Form I-131": "Application for Travel Documents, Parole Documents, and Arrival/Departure Records",
  "Form I-693": "Report of Immigration Medical Examination and Vaccination Record",
  "Form DS-260": "Immigrant Visa Electronic Application",
  "Form I-824": "Application for Action on an Approved Application or Petition",
  "Form I-601": "Application for Waiver of Grounds of Inadmissibility",
  "Form I-94": "Electronic Arrival/Departure Form for foreign visitors",
  "Form I-551": "Permanent Resident Card, also known as the Green Card",
  "Form I-90": "Application to Replace Permanent Resident Card",
  "Request for Evidence": "USCIS letter asking for missing or clarifying documents.",
  "Service Center": "Specific USCIS facility processing the petition.",
  "Priority Date": "Filing date that marks a case’s place in line for quota categories.",
  "CEAC": "Online portal for paying fees, submitting forms, and tracking consular cases.",
  "Invoice ID Number": "Code from NVC used with the case number to log into CEAC.",
  "Affidavit of Support Fee": "NVC fee for processing Form I-864.",
  "Biometrics": "Fingerprints, photo, and signature collected for background checks.",
  "Federal Poverty Guidelines": "Income chart setting the sponsor’s minimum earnings (125%).",
  "Household Size": "People counted on the I-864 to determine the required income level.",
  "Joint Sponsor": "Second sponsor who meets the income rules when the primary sponsor does not.",
  "I-864A": "Contract letting a household member’s income or assets count toward sponsorship.",
  "Public Charge": "Standard assessing whether the immigrant is likely to rely on public aid.",
  "Civil Documents": "Official records (birth, marriage, police, etc.) supporting the case.",
  "Police Certificate": "Government record of an applicant’s criminal history (or lack thereof).",
  "Certified Translation": "Sworn statement that a non-English document is accurately translated.",
  "Interview Appointment Letter": "Notice giving the date, time, and place of the visa or AOS interview.",
  "Panel Physician": "Doctor authorized by an embassy to perform the immigrant medical exam.",
  "Civil Surgeon": "USCIS-designated doctor who performs the AOS medical exam in the U.S.",
  "Class A Condition": "Medical issue that makes an applicant inadmissible until resolved.",
  "Sealed Medical Envelope": "Tamper-proof packet of exam results given to immigration officers.",
  "Vaccination Requirements": "CDC-mandated shots that must be current for immigration.",
  "IMBRA Pamphlet": "Rights-and-resources sheet given to immigrant spouses and fiancés.",
  "Consular Officer": "State-Department official who interviews and decides visa cases.",
  "221(g)": "Temporary refusal pending documents or administrative checks.",
  "Administrative Processing": "Additional security or background review after the interview.",
  "Visa Issuance": "Printing and placing the immigrant visa in the passport.",
  "Green Card Stamp": "Passport stamp serving as temporary proof of permanent residence.",
  "I-551": "Passport stamp serving as temporary proof of permanent residence.",
  "Immigrant Visa": "Visa that, once used to enter the U.S., confers permanent-resident status.",
  "IV": "Visa that, once used to enter the U.S., confers permanent-resident status.",
  "USCIS Immigrant Fee": "Payment that funds production of the physical green card.",
  "Notice of Intent to Deny": "USCIS letter warning of a forthcoming denial unless issues are rebutted.",
  "NOID": "USCIS letter warning of a forthcoming denial unless issues are rebutted.",
  "Board of Immigration Appeals": "Administrative court that hears appeals of USCIS denials.",
  "BIA": "Administrative court that hears appeals of USCIS denials.",
  "Port of Entry": "Airport or border crossing where CBP admits the immigrant.",
  "CBP": "Agency that inspects travelers and activates immigrant visas at entry.",
  "I-94": "Arrival/Departure record showing entry date and status.",
  "Lawful Permanent Resident": "Person authorized to live and work in the U.S. indefinitely.",
  "Social Security Number": "Nine-digit identifier used for work, taxes, and credit.",
  "Conditional Permanent Resident": "Green-card holder with two-year conditional status.",
  "CPR": "Green-card holder with two-year conditional status.",
  "10-year Green Card": "Standard permanent-resident card, renewable every decade.",
  "Naturalization": "Process by which a permanent resident becomes a U.S. citizen.",
  "Continuous Residence": "Required span of U.S. residence before applying for citizenship.",
  "Good Moral Character": "Legal standard of behavior needed for naturalization approval.",
  "Selective Service": "Draft registration required of male permanent residents ages 18-25."
};

export default SpouseGlossary;